// GENERATED by chipinventor/scripts/gen_ci_firmware.py - do not hand-edit.
// This program is placed at 0x00400800 in the ChipInventor ROM; word 0
// belongs to the official validation firmware. EXP_JALR_LINK and
// EXP_AUIPC below are relocated by +0x800 accordingly.
localparam [31:0] SUPP_BASE = 32'h00400800;
// Generated by scripts/gen_firmware_test.py - do not hand-edit.
localparam NUM_SIG_TESTS  = 58;
localparam SIG_BASE_WORDS = 'h100/4;
localparam [31:0] EXP_JALR_LINK = 32'h00400F28;
localparam [31:0] EXP_AUIPC     = 32'h00405F3C;
localparam IMEM_WORDS_NEEDED = 483;

// ---- Expectations for the block gen_ci_firmware.py appends ----
localparam [31:0] EXP_IMEM_LOAD = 32'hCAFEBABE; // x22: load resolved into IMEM
localparam [31:0] EXP_DEP_SUM   = 32'd15;       // x24: 1+2+3+4+5
localparam [31:0] EXP_DEP_CTR   = 32'd6;        // x25: loop counter on exit
