// Generated by scripts/gen_firmware_test.py - do not hand-edit.
localparam NUM_SIG_TESTS  = 58;
localparam SIG_BASE_WORDS = 'h100/4;
localparam [31:0] EXP_JALR_LINK = 32'h00400728;
localparam [31:0] EXP_AUIPC     = 32'h0040573C;
localparam IMEM_WORDS_NEEDED = 471;
