# Auto-generated by scripts/gen_firmware_test.py - do not hand-edit.
# Comprehensive 47-instruction firmware test. Each test computes a
# diff (0=pass) into a dedicated DMEM signature slot; tb_firmware.v
# checks every slot is exactly 0 after the final ECALL.
    lui   x20, 0x10010        # x20 = DMEM base 0x10010000
    lui   x31, 0x10010        # x31 = DMEM base too
    addi  x31, x31, 256   # x31 = signature array base
    # ---- Arith/Logic(Reg): ADD ----
    addi x1, x0, 5
    addi x2, x0, 10
    add x30, x1, x2
    addi x29, x0, 15
    xor x28, x30, x29
    sw x28, 0(x31)   # sig[0] = ADD
    # ---- Arith/Logic(Reg): SUB ----
    addi x1, x0, 10
    addi x2, x0, 5
    sub x30, x1, x2
    addi x29, x0, 5
    xor x28, x30, x29
    sw x28, 4(x31)   # sig[1] = SUB
    # ---- Arith/Logic(Reg): SLL ----
    addi x1, x0, 1
    addi x2, x0, 31
    sll x30, x1, x2
    lui x29, 524288
    addi x29, x29, 0
    xor x28, x30, x29
    sw x28, 8(x31)   # sig[2] = SLL
    # ---- Arith/Logic(Reg): SLT ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, -1
    slt x30, x1, x2
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 12(x31)   # sig[3] = SLT
    # ---- Arith/Logic(Reg): SLTU ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, -1
    sltu x30, x1, x2
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 16(x31)   # sig[4] = SLTU
    # ---- Arith/Logic(Reg): XOR ----
    lui x1, 699051
    addi x1, x1, -1366
    addi x2, x0, -1
    xor x30, x1, x2
    lui x29, 349525
    addi x29, x29, 1365
    xor x28, x30, x29
    sw x28, 20(x31)   # sig[5] = XOR
    # ---- Arith/Logic(Reg): SRL ----
    lui x1, 524288
    addi x1, x1, 0
    addi x2, x0, 4
    srl x30, x1, x2
    lui x29, 32768
    addi x29, x29, 0
    xor x28, x30, x29
    sw x28, 24(x31)   # sig[6] = SRL
    # ---- Arith/Logic(Reg): SRA ----
    addi x1, x0, -1
    addi x2, x0, 5
    sra x30, x1, x2
    addi x29, x0, -1
    xor x28, x30, x29
    sw x28, 28(x31)   # sig[7] = SRA
    # ---- Arith/Logic(Reg): OR ----
    lui x1, 986895
    addi x1, x1, 240
    lui x2, 61681
    addi x2, x2, -241
    or x30, x1, x2
    addi x29, x0, -1
    xor x28, x30, x29
    sw x28, 32(x31)   # sig[8] = OR
    # ---- Arith/Logic(Reg): AND ----
    lui x1, 1044496
    addi x1, x1, -256
    lui x2, 65281
    addi x2, x2, -16
    and x30, x1, x2
    lui x29, 61441
    addi x29, x29, -256
    xor x28, x30, x29
    sw x28, 36(x31)   # sig[9] = AND
    # ---- Arith/Logic(Imm): ADDI ----
    addi x1, x0, 100
    addi x30, x1, -50
    addi x29, x0, 50
    xor x28, x30, x29
    sw x28, 40(x31)   # sig[10] = ADDI
    # ---- Arith/Logic(Imm): SLTI ----
    addi x1, x0, -5
    slti x30, x1, 0
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 44(x31)   # sig[11] = SLTI
    # ---- Arith/Logic(Imm): SLTIU ----
    addi x1, x0, 5
    sltiu x30, x1, 10
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 48(x31)   # sig[12] = SLTIU
    # ---- Arith/Logic(Imm): XORI ----
    lui x1, 61681
    addi x1, x1, -241
    xori x30, x1, -1
    lui x29, 986895
    addi x29, x29, 240
    xor x28, x30, x29
    sw x28, 52(x31)   # sig[13] = XORI
    # ---- Arith/Logic(Imm): ORI ----
    lui x1, 16
    addi x1, x1, -256
    ori x30, x1, 15
    lui x29, 16
    addi x29, x29, -241
    xor x28, x30, x29
    sw x28, 56(x31)   # sig[14] = ORI
    # ---- Arith/Logic(Imm): ANDI ----
    addi x1, x0, -1
    andi x30, x1, 15
    addi x29, x0, 15
    xor x28, x30, x29
    sw x28, 60(x31)   # sig[15] = ANDI
    # ---- Arith/Logic(Imm): SLLI ----
    addi x1, x0, 1
    slli x30, x1, 10
    addi x29, x0, 1024
    xor x28, x30, x29
    sw x28, 64(x31)   # sig[16] = SLLI
    # ---- Arith/Logic(Imm): SRLI ----
    lui x1, 524288
    addi x1, x1, 0
    srli x30, x1, 4
    lui x29, 32768
    addi x29, x29, 0
    xor x28, x30, x29
    sw x28, 68(x31)   # sig[17] = SRLI
    # ---- Arith/Logic(Imm): SRAI ----
    addi x1, x0, -8
    srai x30, x1, 2
    addi x29, x0, -2
    xor x28, x30, x29
    sw x28, 72(x31)   # sig[18] = SRAI
    # ---- Load: LW ----
    lui x2, 912092
    addi x2, x2, -273
    sw x2, 0(x20)
    lw x30, 0(x20)
    lui x29, 912092
    addi x29, x29, -273
    xor x28, x30, x29
    sw x28, 76(x31)   # sig[19] = LW
    # ---- Load: LH ----
    lui x2, 703705
    addi x2, x2, 564
    sw x2, 4(x20)
    lh x30, 4(x20)
    lui x29, 1048569
    addi x29, x29, 564
    xor x28, x30, x29
    sw x28, 80(x31)   # sig[20] = LH
    # ---- Load: LHU ----
    lui x2, 703704
    addi x2, x2, 0
    sw x2, 8(x20)
    lhu x30, 8(x20)
    lui x29, 8
    addi x29, x29, 0
    xor x28, x30, x29
    sw x28, 84(x31)   # sig[21] = LHU
    # ---- Load: LB ----
    lui x2, 699325
    addi x2, x2, -783
    sw x2, 12(x20)
    lb x30, 12(x20)
    addi x29, x0, -15
    xor x28, x30, x29
    sw x28, 88(x31)   # sig[22] = LB
    # ---- Load: LBU ----
    lui x2, 699325
    addi x2, x2, -897
    sw x2, 16(x20)
    lbu x30, 16(x20)
    addi x29, x0, 127
    xor x28, x30, x29
    sw x28, 92(x31)   # sig[23] = LBU
    # ---- Load: LB_lane1 ----
    lui x2, 699320
    addi x2, x2, 204
    sw x2, 32(x20)
    lb x30, 33(x20)
    addi x29, x0, -128
    xor x28, x30, x29
    sw x28, 96(x31)   # sig[24] = LB_lane1
    # ---- Load: LB_lane2 ----
    lui x2, 698364
    addi x2, x2, -1076
    sw x2, 36(x20)
    lb x30, 38(x20)
    addi x29, x0, 127
    xor x28, x30, x29
    sw x28, 100(x31)   # sig[25] = LB_lane2
    # ---- Load: LB_lane3 ----
    lui x2, 596652
    addi x2, x2, -1076
    sw x2, 40(x20)
    lb x30, 43(x20)
    addi x29, x0, -111
    xor x28, x30, x29
    sw x28, 104(x31)   # sig[26] = LB_lane3
    # ---- Load: LBU_lane1 ----
    lui x2, 699320
    addi x2, x2, 204
    sw x2, 44(x20)
    lbu x30, 45(x20)
    addi x29, x0, 128
    xor x28, x30, x29
    sw x28, 108(x31)   # sig[27] = LBU_lane1
    # ---- Load: LBU_lane3 ----
    lui x2, 596652
    addi x2, x2, -1076
    sw x2, 48(x20)
    lbu x30, 51(x20)
    addi x29, x0, 145
    xor x28, x30, x29
    sw x28, 112(x31)   # sig[28] = LBU_lane3
    # ---- Load: LH_lane2 ----
    lui x2, 554587
    addi x2, x2, -1075
    sw x2, 52(x20)
    lh x30, 54(x20)
    lui x29, 1048568
    addi x29, x29, 1893
    xor x28, x30, x29
    sw x28, 116(x31)   # sig[29] = LH_lane2
    # ---- Load: LHU_lane2 ----
    lui x2, 554587
    addi x2, x2, -1075
    sw x2, 56(x20)
    lhu x30, 58(x20)
    lui x29, 8
    addi x29, x29, 1893
    xor x28, x30, x29
    sw x28, 120(x31)   # sig[30] = LHU_lane2
    # ---- Store: SW ----
    addi x2, x0, -1
    sw x2, 20(x20)
    lui x2, 831468
    addi x2, x2, -1346
    sw x2, 20(x20)
    lw x30, 20(x20)
    lui x29, 831468
    addi x29, x29, -1346
    xor x28, x30, x29
    sw x28, 124(x31)   # sig[31] = SW
    # ---- Store: SH ----
    addi x2, x0, -1
    sw x2, 24(x20)
    lui x2, 11
    addi x2, x2, -1075
    sh x2, 24(x20)
    lhu x30, 24(x20)
    lui x29, 11
    addi x29, x29, -1075
    xor x28, x30, x29
    sw x28, 128(x31)   # sig[32] = SH
    # ---- Store: SB ----
    addi x2, x0, -1
    sw x2, 28(x20)
    addi x2, x0, 239
    sb x2, 28(x20)
    lbu x30, 28(x20)
    addi x29, x0, 239
    xor x28, x30, x29
    sw x28, 132(x31)   # sig[33] = SB
    # ---- Store: SB_lane1 ----
    addi x2, x0, -1
    sw x2, 64(x20)
    addi x2, x0, 90
    sb x2, 65(x20)
    lbu x30, 65(x20)
    addi x29, x0, 90
    xor x28, x30, x29
    sw x28, 136(x31)   # sig[34] = SB_lane1
    # ---- Store: SB_lane2 ----
    addi x2, x0, -1
    sw x2, 68(x20)
    addi x2, x0, 165
    sb x2, 70(x20)
    lbu x30, 70(x20)
    addi x29, x0, 165
    xor x28, x30, x29
    sw x28, 140(x31)   # sig[35] = SB_lane2
    # ---- Store: SB_lane3 ----
    addi x2, x0, -1
    sw x2, 72(x20)
    addi x2, x0, 60
    sb x2, 75(x20)
    lbu x30, 75(x20)
    addi x29, x0, 60
    xor x28, x30, x29
    sw x28, 144(x31)   # sig[36] = SB_lane3
    # ---- Store: SH_lane2 ----
    addi x2, x0, -1
    sw x2, 76(x20)
    lui x2, 1
    addi x2, x2, 564
    sh x2, 78(x20)
    lhu x30, 78(x20)
    lui x29, 1
    addi x29, x29, 564
    xor x28, x30, x29
    sw x28, 148(x31)   # sig[37] = SH_lane2
    # ---- Branch: BEQ ----
    addi x1, x0, 7
    addi x2, x0, 7
    addi x30, x0, 0
    beq x1, x2, br_BEQ
    addi x30, x0, 1
    br_BEQ:
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 152(x31)   # sig[38] = BEQ
    # ---- Branch: BEQ_NT ----
    addi x1, x0, 7
    addi x2, x0, 8
    addi x30, x0, 0
    beq x1, x2, br_BEQ_NT
    addi x30, x0, 1
    br_BEQ_NT:
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 156(x31)   # sig[39] = BEQ_NT
    # ---- Branch: BNE ----
    addi x1, x0, 7
    addi x2, x0, 8
    addi x30, x0, 0
    bne x1, x2, br_BNE
    addi x30, x0, 1
    br_BNE:
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 160(x31)   # sig[40] = BNE
    # ---- Branch: BNE_NT ----
    addi x1, x0, 7
    addi x2, x0, 7
    addi x30, x0, 0
    bne x1, x2, br_BNE_NT
    addi x30, x0, 1
    br_BNE_NT:
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 164(x31)   # sig[41] = BNE_NT
    # ---- Branch: BLT ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, -1
    addi x30, x0, 0
    blt x1, x2, br_BLT
    addi x30, x0, 1
    br_BLT:
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 168(x31)   # sig[42] = BLT
    # ---- Branch: BLT_NT ----
    lui x1, 524288
    addi x1, x1, -1
    lui x2, 524288
    addi x2, x2, 0
    addi x30, x0, 0
    blt x1, x2, br_BLT_NT
    addi x30, x0, 1
    br_BLT_NT:
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 172(x31)   # sig[43] = BLT_NT
    # ---- Branch: BGE ----
    lui x1, 524288
    addi x1, x1, -1
    lui x2, 524288
    addi x2, x2, 0
    addi x30, x0, 0
    bge x1, x2, br_BGE
    addi x30, x0, 1
    br_BGE:
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 176(x31)   # sig[44] = BGE
    # ---- Branch: BGE_NT ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, -1
    addi x30, x0, 0
    bge x1, x2, br_BGE_NT
    addi x30, x0, 1
    br_BGE_NT:
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 180(x31)   # sig[45] = BGE_NT
    # ---- Branch: BLTU ----
    lui x1, 524288
    addi x1, x1, -1
    lui x2, 524288
    addi x2, x2, 0
    addi x30, x0, 0
    bltu x1, x2, br_BLTU
    addi x30, x0, 1
    br_BLTU:
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 184(x31)   # sig[46] = BLTU
    # ---- Branch: BLTU_NT ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, -1
    addi x30, x0, 0
    bltu x1, x2, br_BLTU_NT
    addi x30, x0, 1
    br_BLTU_NT:
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 188(x31)   # sig[47] = BLTU_NT
    # ---- Branch: BGEU ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, -1
    addi x30, x0, 0
    bgeu x1, x2, br_BGEU
    addi x30, x0, 1
    br_BGEU:
    addi x29, x0, 0
    xor x28, x30, x29
    sw x28, 192(x31)   # sig[48] = BGEU
    # ---- Branch: BGEU_NT ----
    lui x1, 524288
    addi x1, x1, -1
    lui x2, 524288
    addi x2, x2, 0
    addi x30, x0, 0
    bgeu x1, x2, br_BGEU_NT
    addi x30, x0, 1
    br_BGEU_NT:
    addi x29, x0, 1
    xor x28, x30, x29
    sw x28, 196(x31)   # sig[49] = BGEU_NT
    # ---- Upper Immediate: LUI ----
    lui x30, 74565
    lui x29, 74565
    addi x29, x29, 0
    xor x28, x30, x29
    sw x28, 200(x31)   # sig[50] = LUI
    # ---- Multiplication: MUL ----
    lui x1, 30
    addi x1, x1, 576
    lui x2, 2
    addi x2, x2, -1403
    mul x30, x1, x2
    lui x29, 204625
    addi x29, x29, -1216
    xor x28, x30, x29
    sw x28, 204(x31)   # sig[51] = MUL
    # ---- Multiplication: MULH ----
    lui x1, 524288
    addi x1, x1, 0
    lui x2, 524288
    addi x2, x2, 0
    mulh x30, x1, x2
    lui x29, 262144
    addi x29, x29, 0
    xor x28, x30, x29
    sw x28, 208(x31)   # sig[52] = MULH
    # ---- Multiplication: MULHSU ----
    addi x1, x0, -2
    addi x2, x0, -1
    mulhsu x30, x1, x2
    addi x29, x0, -2
    xor x28, x30, x29
    sw x28, 212(x31)   # sig[53] = MULHSU
    # ---- Multiplication: MULHU ----
    addi x1, x0, -1
    addi x2, x0, -1
    mulhu x30, x1, x2
    addi x29, x0, -2
    xor x28, x30, x29
    sw x28, 216(x31)   # sig[54] = MULHU
    # ---- CRC: CRCB ----
    addi x1, x0, 97
    lui x2, 16
    addi x2, x2, -1
    crcb x30, x1, x2
    lui x29, 10
    addi x29, x29, -649
    xor x28, x30, x29
    sw x28, 220(x31)   # sig[55] = CRCB
    # ---- CRC: CRCH ----
    lui x1, 6
    addi x1, x1, 354
    lui x2, 16
    addi x2, x2, -1
    crch x30, x1, x2
    lui x29, 7
    addi x29, x29, -1552
    xor x28, x30, x29
    sw x28, 224(x31)   # sig[56] = CRCH
    # ---- CRC: CRCW ----
    lui x1, 398886
    addi x1, x1, 868
    lui x2, 16
    addi x2, x2, -1
    crcw x30, x1, x2
    lui x29, 3
    addi x29, x29, -778
    xor x28, x30, x29
    sw x28, 228(x31)   # sig[57] = CRCW

    # ---- Jump: JAL ----
    jal   x6, jal_target
    addi  x7, x0, 1              # must be SKIPPED by JAL
jal_target:
    addi  x8, x0, 1              # proves JAL landed

    # ---- Jump: JALR ----
    auipc x10, 0
    addi  x10, x10, %pcrel(jalr_target)   # target address, PC-relative so it
                                          # stays in range however large the
                                          # generated test program grows
    jalr  x9, 0(x10)
jalr_link:
    addi  x11, x0, 1              # NOT skipped overall: jalr_target's own
                                   # return jump lands exactly here, since
                                   # x9 (the link) points at this address
    j     after_jalr
jalr_target:
    addi  x12, x0, 1             # proves JALR landed
    jalr  x0, 0(x9)               # returns to x9 = address of the addi above
after_jalr:
    addi  x13, x0, 1             # proves control flow rejoined correctly

    # ---- Upper Immediate: AUIPC ----
auipc_site:
    auipc x14, 5                 # x14 = this_pc + (5<<12)

    # ---- System/Synchronization: FENCE must be a pure no-op ----
    addi  x15, x0, 0x77
    fence
    addi  x16, x15, 0             # must still read 0x77

    # ---- System/Synchronization: EBREAK must be a pure no-op (control-flow-wise) ----
    addi  x17, x0, 0x88
    ebreak
    addi  x18, x17, 0             # must still read 0x88

    ecall                         # final completion marker

