#!/usr/bin/env python3
"""Generate chipinventor/blocks/crc_unit.v: the Xicrc unit written as
byte updates (the standard CRC-CCITT byte formula, shifts and XORs only), and
prove it equal to the frozen Phase 2 block.

The logic is identical; only the description changes. The reason is the
simulator: the Phase 2 form (a bit-by-bit function loop, evaluated for all
three widths) makes Icarus Verilog re-run 56 interpreted LFSR steps whenever a
register operand changes, nearly every instruction. On the lane firmware the
byte form simulates the whole chip about 2.7 times faster, which is what fits
the application into the ChipInventor simulator's time window.

The proof: the CRC is linear over GF(2) (no initial value or final XOR inside
the unit), and so are both descriptions by construction, so they are equal on
all inputs exactly when they agree on the zero vector and every basis vector.
`masks()` computes the same linear map from the bit-serial definition, for
reference.

    python gen_crc_xor.py            # write blocks/crc_unit.v
    python gen_crc_xor.py --check    # fail if blocks/crc_unit.v is stale
    python gen_crc_xor.py --prove    # equal to rtl_ref on every input (basis vectors)
    python gen_crc_xor.py --prove-sat  # the same by Yosys SAT (slow, optional)
"""
import argparse
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "blocks", "crc_unit.v")
REF = os.path.join(ROOT, "rtl_ref", "crc_unit.v")
POLY = 0x1021


def lfsr(seed, data, nbits):
    """The bit-serial definition: MSB-first, one step per data bit."""
    c = seed
    for i in range(nbits - 1, -1, -1):
        fb = ((c >> 15) ^ (data >> i)) & 1
        c = ((c << 1) & 0xFFFF) ^ (POLY if fb else 0)
    return c


def masks(nbits):
    """Per output bit: (seed mask, data mask)."""
    seed_out = [lfsr(1 << j, 0, nbits) for j in range(16)]
    data_out = [lfsr(0, 1 << k, nbits) for k in range(nbits)]
    res = []
    for i in range(16):
        sm = sum(1 << j for j in range(16) if seed_out[j] >> i & 1)
        dm = sum(1 << k for k in range(nbits) if data_out[k] >> i & 1)
        res.append((sm, dm))
    return res


HEADER = """// ============================================================================
// crc_unit.v - CRCB/CRCH/CRCW (Xicrc). Combinational, zero-latency.
//
// GENERATED by chipinventor/scripts/gen_crc_xor.py; do not hand-edit.
//
// Structure follows Block Guide S3.1.3: three independent CRC blocks, one per
// input width (8 / 16 / 32 bits), each an algebraically unrolled XOR network,
// feeding a single output multiplexer selected per Table 11. Each block is
// written as byte updates - the eight LFSR steps of one byte already combined
// into the standard CRC-CCITT formula - so it is shifts and XORs only, and
// synthesis flattens it into the same XOR network as the bit-serial form.
// `gen_crc_xor.py --prove` shows this block and the Phase 2 one
// (rtl_ref/crc_unit.v, the same CRC as a bit-by-bit function loop) equal on
// every input: both are GF(2)-linear, and they agree on every basis vector.
//
// Why not the bit loop: in a simulator it re-runs 56 interpreted LFSR steps
// whenever a register operand changes, nearly every instruction. On the lane
// firmware that made simulating the chip about 2.7 times slower, which is the
// difference between fitting the ChipInventor simulator's time window or not.
//
// Algorithm: CRC-16-CCITT-FALSE (poly 0x1021, MSB-first, no input/output
// reflection, no final XOR), confirmed against the official validation
// firmware - all three widths chain to its expected 0x1E82.
//
// OPERAND ROLES (rs1 = data, rs2 = accumulator)
// -------------------------------------------------------------------
// The official validation firmware accumulates the CRC in rs2 and passes the
// new data in rs1:
//
//     crcb s0, s1, s0     # rd=s0, rs1=s1 (data byte), rs2=s0 (CRC so far)
//
// CRCB/CRCH/CRCW select how many bits of rs1 (8/16/32, MSB-first) are folded
// into one CRC-16 update - one shared CRC-16 algorithm over three input
// widths, not three different CRC algorithms.
// ============================================================================
module crc_unit (
    input  wire [31:0] rs1_data, // data to fold in
    input  wire [31:0] rs2_data, // running CRC / seed (low 16 bits used)
    input  wire [2:0]  funct3,   // 000=CRCB(8b) 001=CRCH(16b) 010=CRCW(32b)
    output reg  [31:0] result
);
    wire [15:0] seed = rs2_data[15:0];
"""

FOOTER = """
    // ---- Output multiplexer (Block Guide Table 11) ----------------------
    always @(*) begin
        case (funct3[1:0])
            2'b00:   result = {16'b0, crc_b}; // CRCB
            2'b01:   result = {16'b0, crc_h}; // CRCH
            2'b10:   result = {16'b0, crc_w}; // CRCW
            default: result = {16'b0, seed};  // unused encoding: seed passes through
        endcase
    end
endmodule
"""


BODY = """
    // One byte folded in, MSB first: the CRC-16/CCITT byte update, which is
    // the eight LFSR steps of the bit-serial definition already combined
    // (x is the byte's feedback; x << 12, x << 5 and x are where the
    // polynomial 0x1021 puts it). Shifts and XORs only.
    function [15:0] step8;
        input [15:0] c;
        input [7:0]  b;
        reg   [7:0]  x;
        begin
            x = c[15:8] ^ b;
            x = x ^ (x >> 4);
            step8 = {c[7:0], 8'h00} ^ {x[3:0], 12'h000} ^ {3'b000, x, 5'b00000} ^ {8'h00, x};
        end
    endfunction

    // ---- Block 1: CRCB, 8-bit input ------------------------------------
    // ---- Block 2: CRCH, 16-bit input: its two bytes, high first ----------
    // ---- Block 3: CRCW, 32-bit input: its four bytes, high first ---------
    // ---- Output multiplexer (Block Guide Table 11) ----------------------
    // Only the selected block is evaluated, which is what keeps a simulator
    // from recomputing three CRCs on every register-operand change.
    always @(*) begin
        case (funct3[1:0])
            2'b00:   result = {16'b0, step8(seed, rs1_data[7:0])};                        // CRCB
            2'b01:   result = {16'b0, step8(step8(seed, rs1_data[15:8]), rs1_data[7:0])}; // CRCH
            2'b10:   result = {16'b0, step8(step8(step8(step8(seed, rs1_data[31:24]),
                                                        rs1_data[23:16]),
                                                  rs1_data[15:8]),
                                            rs1_data[7:0])};                            // CRCW
            default: result = {16'b0, seed};  // unused encoding: seed passes through
        endcase
    end
endmodule
"""


def render():
    return HEADER + BODY


PROOF_TB = r"""
`timescale 1ns/1ps
module prove;
    reg [31:0] a, b; reg [2:0] f;
    wire [31:0] r_ref, r_new;
    crc_ref u_ref (.rs1_data(a), .rs2_data(b), .funct3(f), .result(r_ref));
    crc_new u_new (.rs1_data(a), .rs2_data(b), .funct3(f), .result(r_new));
    integer i, k, bad = 0, n = 0;
    task t; begin #1 n = n + 1; if (r_ref !== r_new) bad = bad + 1; end endtask
    initial begin
        for (k = 0; k < 8; k = k + 1) begin     // every funct3, 4..7 included
            f = k;
            // the zero vector and every basis vector: 16 seed bits, 32 data bits
            a = 0; b = 0; t;
            for (i = 0; i < 16; i = i + 1) begin a = 0; b = 32'd1 << i; t; end
            for (i = 0; i < 32; i = i + 1) begin a = 32'd1 << i; b = 0; t; end
            // and random vectors, upper rs2 bits included (both must ignore them)
            for (i = 0; i < 5000; i = i + 1) begin a = $random; b = $random; t; end
        end
        $display("PROOF %0d inputs, %0d differ", n, bad);
        $finish;
    end
endmodule
"""


def prove():
    """Both blocks are GF(2)-linear by construction: the reference is the
    bit-serial LFSR (shifts, XOR, and AND with the constant polynomial) and the
    new one is masked XORs; the output mux is the same text in both. Two
    linear maps are equal exactly when they agree on a basis, so running the
    zero vector and every basis vector of (seed, data) through both modules, for
    each funct3, proves them equal on all 2^48 inputs. Random vectors are added
    as a cross-check."""
    import shutil
    if not shutil.which("iverilog"):
        print("SKIP equivalence proof (needs iverilog)")
        return 0
    with tempfile.TemporaryDirectory() as d:
        open(os.path.join(d, "ref.v"), "w").write(open(REF).read().replace("module crc_unit", "module crc_ref", 1))
        open(os.path.join(d, "new.v"), "w").write(open(OUT).read().replace("module crc_unit", "module crc_new", 1))
        open(os.path.join(d, "tb.v"), "w").write(PROOF_TB)
        vvp = os.path.join(d, "p.vvp")
        r = subprocess.run(["iverilog", "-g2005", "-s", "prove", "-o", vvp, os.path.join(d, "ref.v"),
                            os.path.join(d, "new.v"), os.path.join(d, "tb.v")], capture_output=True, text=True)
        if r.returncode:
            print("FAIL could not build the proof: " + r.stderr[:500])
            return 1
        out = subprocess.run(["vvp", "-n", vvp], capture_output=True, text=True).stdout
    line = next((l for l in out.splitlines() if l.startswith("PROOF")), "PROOF ? inputs, ? differ")
    if not line.endswith(" 0 differ"):
        print("FAIL blocks/crc_unit.v differs from rtl_ref/crc_unit.v: " + line)
        return 1
    print("OK   blocks/crc_unit.v equals rtl_ref/crc_unit.v on every input: both linear, equal on "
          "the zero vector and all 48 basis vectors for each funct3 (+ random), %s"
          % line.split("PROOF ")[1].replace(", 0 differ", " checked"))
    return 0


def prove_sat():
    """Yosys: the new block against rtl_ref's, all inputs, by SAT (slow: XOR
    networks are hard for plain SAT; kept for completeness, --prove-sat)."""
    import shutil
    tool = shutil.which("yosys") or shutil.which("yowasp-yosys")
    if not tool:
        print("SKIP formal equivalence (install Yosys, or: python -m pip install yowasp-yosys)")
        return 0
    exe = [tool]
    with tempfile.TemporaryDirectory() as d:
        ref = open(REF).read().replace("module crc_unit", "module crc_ref", 1)
        new = open(OUT).read().replace("module crc_unit", "module crc_new", 1)
        open(os.path.join(d, "ref.v"), "w").write(ref)
        open(os.path.join(d, "new.v"), "w").write(new)
        script = ("read_verilog ref.v new.v; proc; flatten; opt_clean; "
                  "miter -equiv -flatten -make_assert crc_ref crc_new miter; hierarchy -top miter; "
                  "sat -verify -prove-asserts -set-init-zero miter")
        r = subprocess.run(exe + ["-q", "-p", script], cwd=d, capture_output=True, text=True)
        if r.returncode:
            print("FAIL the generated block is NOT equivalent to rtl_ref/crc_unit.v")
            print((r.stdout + r.stderr)[-2000:])
            return 1
    print("OK   blocks/crc_unit.v equals rtl_ref/crc_unit.v for every input (Yosys SAT miter)")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--prove", action="store_true")
    ap.add_argument("--prove-sat", action="store_true")
    a = ap.parse_args()
    if a.prove_sat:
        return prove_sat()
    text = render()
    if a.check:
        if open(OUT).read() != text:
            sys.exit("FAIL blocks/crc_unit.v is stale: run scripts/gen_crc_xor.py")
        print("OK   blocks/crc_unit.v is current")
    elif not a.prove:
        with open(OUT, "w", newline="\n") as fh:
            fh.write(text)
        print("wrote blocks/crc_unit.v (byte-update form)")
    if a.prove:
        return prove()
    return 0


if __name__ == "__main__":
    sys.exit(main())
