#!/usr/bin/env python3
"""Print the testbench's instance-alias block for an exported ChipInventor top.

The platform names block instances automatically - blk2116_47, blk2523_59 and
so on - and those names change every time the project is regenerated. The
exported netlist already disagrees with the example project's own testbench
about them. Every hierarchical reference in tb_chipinventor.v therefore goes
through a small set of `define aliases at the top of the file, and this
regenerates that block so re-aliasing is one command instead of a manual hunt
through a 1200-line generated file.

Only five aliases are needed, which is deliberate: the unit suites instantiate
blocks directly by module name rather than reaching into the project, so the
only instances that have to be located are the ones holding observable state.

Usage:
    python gen_ci_aliases.py path/to/exported/top.v [--dut-name dut]
    python gen_ci_aliases.py path/to/exported/top.v --write ../tb_chipinventor.v

Ambiguity is reported rather than guessed at: if a module turns out to have
more than one instance, the script says so instead of picking one.
"""

import argparse
import os
import re
import sys

# alias -> module name whose instance holds the state that alias reaches.
WANTED = [
    ("CTRL", "control_unit",  "FSM state and the firmware-completion event"),
    ("PC",   "pc_reg",        "program counter"),
    ("IR",   "ir_reg",        "instruction register"),
    ("RF",   "register_file", "the 32 general-purpose registers"),
    ("DMEM", "dmem",          "the data memory array"),
]

BEGIN = "// >>> BEGIN GENERATED ALIASES"
END = "// <<< END GENERATED ALIASES"

# `module_name [#(params)] instance_name (`  at the start of a line.
INST_RE = re.compile(
    r"(?m)^[ \t]*([A-Za-z_]\w*)[ \t]*(?:#\s*\([^;]*?\)\s*)?([A-Za-z_]\w*)[ \t]*\(")

# Keywords that INST_RE would otherwise mistake for a module instantiation.
NOT_MODULES = {
    "module", "always", "if", "else", "case", "casez", "casex", "for", "while",
    "initial", "assign", "function", "task", "begin", "end", "endmodule",
    "wire", "reg", "input", "output", "inout", "parameter", "localparam",
    "posedge", "negedge", "repeat", "forever",
}


def find_instances(text):
    """Map module name -> list of instance names, from a generated top.v."""
    # Only look inside the structural `top` module: the file also inlines every
    # block's own source, which contains no instantiations but does contain
    # plenty of constructs that look like one.
    m = re.search(r"(?m)^\s*module\s+top\s*\(", text)
    body = text[m.start():] if m else text

    out = {}
    for mod, inst in INST_RE.findall(body):
        if mod in NOT_MODULES or inst in NOT_MODULES:
            continue
        out.setdefault(mod, []).append(inst)
    return out


def build_block(instances, dut_name):
    lines = [
        BEGIN,
        "// Regenerated by scripts/gen_ci_aliases.py from the exported top.v.",
        "// Platform instance names change on every export; re-run that script",
        "// and replace this block whenever the project is regenerated.",
        "`define DUT   %s" % dut_name,
    ]
    problems = []
    width = max(len(a) for a, _, _ in WANTED)
    for alias, module, what in WANTED:
        found = instances.get(module, [])
        if len(found) == 1:
            lines.append("`define %-*s `DUT.%-14s // %s" % (width, alias, found[0], what))
        elif not found:
            lines.append("`define %-*s `DUT.<NOT FOUND>   // %s" % (width, alias, what))
            problems.append("no instance of module '%s' found" % module)
        else:
            lines.append("`define %-*s `DUT.<AMBIGUOUS>   // %s" % (width, alias, what))
            problems.append("module '%s' has %d instances (%s) - disambiguate by hand"
                            % (module, len(found), ", ".join(found)))
    lines.append(END)
    return "\n".join(lines) + "\n", problems


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("top_v", help="the top.v exported from ChipInventor")
    ap.add_argument("--dut-name", default="dut",
                    help="the name the testbench gives the top instance (default: dut)")
    ap.add_argument("--write", metavar="TB",
                    help="rewrite the alias block in this testbench in place")
    args = ap.parse_args()

    with open(args.top_v) as fh:
        text = fh.read()

    instances = find_instances(text)
    if not instances:
        sys.exit("found no instantiations in %s - is this a generated top.v?" % args.top_v)

    block, problems = build_block(instances, args.dut_name)

    for note in problems:
        print("WARNING: %s" % note, file=sys.stderr)

    if not args.write:
        print(block, end="")
        if problems:
            sys.exit(1)
        return

    with open(args.write) as fh:
        tb = fh.read()
    if BEGIN not in tb or END not in tb:
        sys.exit("%s has no %s / %s markers to replace between" % (args.write, BEGIN, END))
    if problems:
        sys.exit("refusing to write an alias block with unresolved instances")

    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n",
                 block, tb, flags=re.DOTALL)
    with open(args.write, "w") as fh:
        fh.write(new)
    print("updated the alias block in %s" % os.path.basename(args.write))


if __name__ == "__main__":
    main()
