#!/usr/bin/env python3
"""Produce the netlist that goes through OpenLane, from the exported top.v.

The functional netlist and the netlist you tape out are deliberately not the
same file:

  * top.v          742-word ROM, DMEM_WORDS=2048 - what the testbench runs
  * openlane/src/  3-word mock ROM, small DMEM   - what P&R sees

The firmware repository's own README asks for the first substitution ("you do
not need to synthesize the complete firmware ... a large case block can
generate unnecessary cells"). The second is the DMEM area knob.

Doing it here rather than by swapping Code fields on the canvas means the
exported top.v stays the verified artifact - the one check_export.py audits and
the one the suite runs against - and the P&R variant is regenerated from it on
demand, so the two cannot silently drift apart.

Usage:
    python gen_pnr_netlist.py [--dmem-words 8] [--out openlane/src/top.v]
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

DEFAULT_TOP = os.path.join(ROOT, "top.v")
DEFAULT_MOCK = os.path.join(ROOT, "blocks", "imem_mock.v")
DEFAULT_OUT = os.path.join(ROOT, "openlane", "src", "top.v")


def module_span(text, name):
    """(start, end) of `module <name> ... endmodule`, or None."""
    m = re.search(r"(?ms)^module\s+%s\s*[#(].*?^endmodule" % re.escape(name), text)
    return (m.start(), m.end()) if m else None


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--top", default=DEFAULT_TOP)
    ap.add_argument("--mock", default=DEFAULT_MOCK)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--dmem-words", type=int, default=8)
    args = ap.parse_args()

    for p in (args.top, args.mock):
        if not os.path.exists(p):
            sys.exit("FAIL %s does not exist" % p)

    text = open(args.top).read()

    # ---- swap the full ROM for the mock -------------------------------
    span = module_span(text, "imem")
    if span is None:
        sys.exit("FAIL no `imem` module found in %s" % args.top)
    mock = open(args.mock).read()
    mock_span = module_span(mock, "imem")
    if mock_span is None:
        sys.exit("FAIL %s does not declare a module named `imem`" % args.mock)
    rom_words = len(re.findall(r"20'd\d+\s*:\s*data_o", text[span[0]:span[1]]))
    text = text[:span[0]] + mock[mock_span[0]:mock_span[1]] + text[span[1]:]
    mock_words = len(re.findall(r"20'd\d+\s*:\s*data_o", mock))

    # ---- resize DMEM on the instance ----------------------------------
    new, n = re.subn(r"(dmem\s*#\(\s*\.DMEM_WORDS\s*\()\s*\d+\s*(\))",
                     r"\g<1>%d\g<2>" % args.dmem_words, text)
    if n != 1:
        sys.exit("FAIL expected exactly one dmem #(.DMEM_WORDS(...)) instance, found %d" % n)
    text = new

    header = (
        "// GENERATED by chipinventor/scripts/gen_pnr_netlist.py - do not hand-edit.\n"
        "// Source: %s\n"
        "// ROM:    %d words replaced by the %d-word mock (firmware repo README)\n"
        "// DMEM:   DMEM_WORDS = %d\n"
        "// This is the P&R variant. The functional netlist is ../../top.v.\n\n"
        % (os.path.basename(args.top), rom_words, mock_words, args.dmem_words))

    d = os.path.dirname(args.out)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    with open(args.out, "w", newline="\n") as fh:
        fh.write(header + text)

    # sanity: exactly one module of each name, and no leftover ROM
    names = re.findall(r"(?m)^module\s+(\w+)", text)
    dupes = sorted(set(n for n in names if names.count(n) > 1))
    if dupes:
        sys.exit("FAIL duplicate module definitions: %s" % ", ".join(dupes))
    print("wrote %s" % args.out)
    print("  modules: %d, ROM %d -> %d words, DMEM_WORDS = %d"
          % (len(names), rom_words, mock_words, args.dmem_words))


if __name__ == "__main__":
    main()
