#!/usr/bin/env python3
"""Write build/mock_export.v: ci_top.v re-emitted the way ChipInventor exports.

The real export only exists once the canvas is wired, but check_export.py,
gen_ci_aliases.py and gate 12 all have to work on it the first time. This
rebuilds the mirror in the platform's own format, as observed in the smoke
exports (build/smoke_export*.v):

  * every block's source under `//  ---------- INLCUDED BLOCK: name  ----------`
    (the platform's spelling), then the SoC project under
    `// ---------- INCLUDED IP: rvbl2_soc ----------`, then `top`;
  * nets renamed w_1, w_2, ...; instances renamed blk<id>_<n>, the IP instance
    blkProj<id>_<n>; each instance's ports listed in a different order;
  * a pin wired straight to one port appears by name (`.tx_o (tx_o)`, a bus as
    `.gpio_o (gpio_o[7:0])`); a pin that also feeds blocks becomes
    `assign pin = w_n;`; an Inout Pin becomes `assign pin = D ? C : 1'bZ ;`.

scripts/test_check_export.py uses it to prove the checker passes a correct
export and fails the wiring mistakes that matter; run_ci.sh also runs the full
testbench against it, re-aliased, as a dry run of gate 12.

Usage: python gen_mock_export.py [--out PATH]
"""

import argparse
import importlib.util
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BLOCKS = os.path.join(ROOT, "blocks")
CI_TOP = os.path.join(ROOT, "ci_top.v")
DEFAULT_OUT = os.path.join(ROOT, "build", "mock_export.v")

_spec = importlib.util.spec_from_file_location("ce", os.path.join(HERE, "check_export.py"))
ce = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(ce)

BANNER = ("// Automatically generated by ChipInventor Cloud EDA Tool - 3.15\n"
          "// Careful: this file (hdl.v) will be automatically replaced\n"
          "// when you ask tool to generate top Verilog code by clicking\n"
          "// at BLOCKS button.\n\n")


def wire_widths(text, module):
    body = re.search(r"(?ms)^module\s+%s\b.*?^endmodule" % module, ce.strip_comments(text)).group(0)
    out = {}
    for w, names in re.findall(r"(?m)^\s*wire\s*(\[[^\]]+\])?\s*([^;]+);", body):
        for n in names.split(","):
            if n.strip():
                out[n.strip()] = (w or "").replace(" ", "")
    return out


def emit_project(name, proj, widths, soc_module, id_base):
    pins = {n: (d, w) for d, w, n in proj["ports"]}
    alias_of = {net: pin for pin, net in proj["aliases"]}
    tri_pins = {pin for pin, _, _ in proj["tris"]}

    # Every internal net gets a w_N name, in first-use order.
    wname = {}

    def net(n):
        if n in pins and n not in alias_of.values() and n not in tri_pins:
            return n + pins[n][1]                       # pin wired straight in
        if n in pins:                                   # an Inout Pin's pad net
            return n
        if n not in wname:
            wname[n] = "w_%d" % (len(wname) + 1)
        return wname[n]

    inst_lines = []
    for k, (mod, _inst, params, conns) in enumerate(proj["instances"]):
        iname = ("blkProj%d_%d" if mod == soc_module else "blk%d_%d") % (id_base + k, k + 2)
        ports = sorted(conns, reverse=(k % 2 == 0))      # a different order each time
        body = ",\n".join("         .%s (%s)" % (p, net(conns[p])) for p in ports)
        inst_lines.append("%s %s%s (\n%s\n     );\n" % (mod, params + " " if params else "", iname, body))
    assigns = ["assign %s = %s;" % (pin, net(n)) for pin, n in proj["aliases"]]
    assigns += ["\tassign %s = %s ? %s : 1'bZ ;" % (pin, net(en), net(data))
                for pin, en, data in proj["tris"]]

    decl = []
    for n, (d, w) in pins.items():
        decl.append("  %s %s%s" % (d, "" if d == "inout" else "wire ", (w + " " if w else "") + n))
    out = [BANNER, "module %s (\n\n%s\n\n);\n\n//Internal Wires\n" % (name, ",\n".join(decl))]
    for n, w in sorted(wname.items(), key=lambda kv: int(kv[1][2:])):
        out.append(" wire %s%s;\n" % ((widths.get(n, "") + " ") if widths.get(n) else "", w))
    if assigns:
        out.append("\n//Interface Assigns\n" + "\n".join(assigns) + "\n")
    out.append("\n//Instances of Modules\n" + "\n".join(inst_lines) + "\n\nendmodule\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    ref = open(CI_TOP).read()
    parts = []
    for fn in sorted(os.listdir(BLOCKS)):
        if fn.endswith(".v") and fn not in ce.SKIP_BLOCKS:
            parts.append("\n\n\n//  ---------- INLCUDED BLOCK: %s  ---------- \n" % fn[:-2])
            parts.append(open(os.path.join(BLOCKS, fn)).read())
    soc = ce.parse_project(ref, ce.SOC_NAME)
    top = ce.parse_project(ref, "top")
    parts.append("\n\n\n// ---------- INCLUDED IP: %s ---------- \n\n\n" % ce.SOC_NAME)
    parts.append(emit_project(ce.SOC_NAME, soc, wire_widths(ref, ce.SOC_NAME), None, 3650))
    parts.append("\n\n\n")
    parts.append(emit_project("top", top, wire_widths(ref, "top"), ce.SOC_NAME, 14800))

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", newline="\n") as fh:
        fh.write("".join(parts))
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
