#!/usr/bin/env python3
"""Print the testbench's instance-alias block for an exported ChipInventor top.

The platform names block instances automatically - blk2116_47, blkProj14800_2
and so on - and those names change every time a project is regenerated. Every
hierarchical reference in tb_chipinventor.v therefore goes through a small set
of `define aliases at the top of the file, and this regenerates that block so
re-aliasing is one command instead of a manual hunt through a generated file.

Stage 3 has two projects: `top` (the chip) instantiates the SoC project, which
the export includes as its own module. So the aliases are resolved in two
steps - the SoC instance inside `top`, then each block instance inside the SoC
module - and every block alias is written relative to `SOC.

Only the instances holding state the testbench observes are aliased; the unit
suites instantiate blocks directly by module name.

Usage:
    python gen_ci_aliases.py path/to/exported/top.v [--dut-name dut]
    python gen_ci_aliases.py path/to/exported/top.v --write ../tb_chipinventor.v
    python gen_ci_aliases.py ci_top.v --check ../tb_chipinventor.v

--check fails unless the testbench's alias block is exactly what this script
generates, which is how run_ci.sh proves the committed block matches ci_top.v.

Ambiguity is reported rather than guessed at: if a module turns out to have
more than one instance, the script says so instead of picking one.
"""

import argparse
import os
import re
import sys

# alias -> module name whose instance (inside the SoC) holds that state.
WANTED = [
    ("CTRL", "control_unit",  "FSM state and the firmware-completion event"),
    ("PC",   "pc_reg",        "program counter"),
    ("IR",   "ir_reg",        "instruction register"),
    ("RF",   "register_file", "the 32 general-purpose registers"),
    ("DMEM", "dmem",          "the data memory array"),
    ("GPIO", "gpio",          "PIN controller registers"),
    ("UART", "uart",          "serial controller registers"),
]
# The SoC module is recognised by what it contains, not by its project name.
SOC_MARKER = "control_unit"

BEGIN = "// >>> BEGIN GENERATED ALIASES"
END = "// <<< END GENERATED ALIASES"

# `module_name [#(params)] instance_name (`  at the start of a line.
INST_RE = re.compile(
    r"(?m)^[ \t]*([A-Za-z_]\w*)[ \t]*(?:#\s*\([^;]*?\)\s*)?([A-Za-z_]\w*)[ \t]*\(")

# Keywords that INST_RE would otherwise mistake for a module instantiation.
NOT_MODULES = {
    "module", "always", "if", "else", "case", "casez", "casex", "for", "while",
    "initial", "assign", "function", "task", "begin", "end", "endmodule",
    "wire", "reg", "input", "output", "inout", "parameter", "localparam",
    "posedge", "negedge", "repeat", "forever",
}


def module_bodies(text):
    """module name -> body text, comments removed."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return {m.group(1): m.group(0)
            for m in re.finditer(r"(?ms)^\s*module\s+(\w+)\b.*?^\s*endmodule", text)}


def find_instances(body):
    """Map module name -> list of instance names inside one module body."""
    out = {}
    for mod, inst in INST_RE.findall(body):
        if mod in NOT_MODULES or inst in NOT_MODULES:
            continue
        out.setdefault(mod, []).append(inst)
    return out


def build_block(text, dut_name):
    problems = []
    bodies = module_bodies(text)
    if "top" not in bodies:
        return None, ["no `module top` in the export"]
    top_insts = find_instances(bodies["top"])

    # The SoC: the module instantiated in top that itself contains the core.
    soc = [(mod, insts) for mod, insts in top_insts.items()
           if mod in bodies and SOC_MARKER in find_instances(bodies[mod])]
    lines = [
        BEGIN,
        "// Regenerated by scripts/gen_ci_aliases.py from the exported top.v.",
        "// Platform instance names change on every export; re-run that script",
        "// and replace this block whenever the project is regenerated.",
        "`define %-5s %s" % ("DUT", dut_name),
    ]
    if len(soc) != 1 or len(soc[0][1]) != 1:
        problems.append("expected exactly one SoC instance in top, found %s"
                        % ([(m, i) for m, i in soc] or "none"))
        lines.append("`define SOC   `DUT.<NOT FOUND>    // the SoC project, reused as IP")
        soc_insts = {}
    else:
        soc_mod, (soc_inst,) = soc[0]
        lines.append("`define SOC   `DUT.%-14s // the %s project, reused as IP"
                     % (soc_inst, soc_mod))
        soc_insts = find_instances(bodies[soc_mod])

    width = 5   # "`define NAME  " columns line up with DUT and SOC
    for alias, module, what in WANTED:
        found = soc_insts.get(module, [])
        if len(found) == 1:
            lines.append("`define %-*s `SOC.%-14s // %s" % (width, alias, found[0], what))
        elif not found:
            lines.append("`define %-*s `SOC.<NOT FOUND>   // %s" % (width, alias, what))
            problems.append("no instance of module '%s' in the SoC" % module)
        else:
            lines.append("`define %-*s `SOC.<AMBIGUOUS>   // %s" % (width, alias, what))
            problems.append("module '%s' has %d instances (%s) - disambiguate by hand"
                            % (module, len(found), ", ".join(found)))
    lines.append(END)
    return "\n".join(lines) + "\n", problems


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("top_v", help="the top.v exported from ChipInventor (or ci_top.v)")
    ap.add_argument("--dut-name", default="dut",
                    help="the name the testbench gives the top instance (default: dut)")
    group = ap.add_mutually_exclusive_group()
    group.add_argument("--write", metavar="TB",
                       help="rewrite the alias block in this testbench in place")
    group.add_argument("--check", metavar="TB",
                       help="fail unless this testbench's alias block matches")
    args = ap.parse_args()

    with open(args.top_v) as fh:
        block, problems = build_block(fh.read(), args.dut_name)
    for note in problems:
        print("WARNING: %s" % note, file=sys.stderr)
    if block is None:
        sys.exit(1)

    if not args.write and not args.check:
        print(block, end="")
        sys.exit(1 if problems else 0)

    path = args.write or args.check
    with open(path) as fh:
        tb = fh.read()
    if BEGIN not in tb or END not in tb:
        sys.exit("%s has no %s / %s markers" % (path, BEGIN, END))
    if problems:
        sys.exit("refusing to use an alias block with unresolved instances")
    current = tb[tb.index(BEGIN):tb.index(END) + len(END) + 1]

    if args.check:
        if current != block:
            sys.exit("FAIL the alias block in %s does not match %s - run with --write"
                     % (os.path.basename(path), os.path.basename(args.top_v)))
        print("OK   alias block matches %s (%d aliases)"
              % (os.path.basename(args.top_v), len(WANTED) + 2))
        return

    with open(path, "w", newline="\n") as fh:
        fh.write(tb.replace(current, block))
    print("updated the alias block in %s" % os.path.basename(path))


if __name__ == "__main__":
    main()
