#!/usr/bin/env python3
"""Emit build/ref_renamed.v: rtl_ref/*.v with every module renamed ref_*.

The mirror-equivalence testbench elaborates the ChipInventor blocks and the
original design side by side, but they define modules of the same names (alu,
dmem, control_unit, ...). Rather than maintain a second hand-edited copy of the
reference - which would defeat the point of comparing against it - this rewrites
the frozen rtl_ref snapshot mechanically at build time.

Only two things are rewritten, both anchored so they cannot touch anything else:
  * `module NAME`           -> `module ref_NAME`
  * a line that starts with NAME followed by whitespace or `#`, which in this
    codebase is always an instantiation (every instance is named u_*)

Signal names are never touched: word boundaries mean `alu` does not match
`alu_op`, and no port connection in this codebase begins a line with a bare
module name.
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "rtl_ref")
OUT = os.path.join(ROOT, "build", "ref_renamed.v")


def main():
    files = sorted(f for f in os.listdir(SRC) if f.endswith(".v"))
    if not files:
        sys.exit("no .v files in %s" % SRC)

    names = []
    bodies = {}
    for fname in files:
        with open(os.path.join(SRC, fname)) as fh:
            text = fh.read()
        bodies[fname] = text
        names.extend(re.findall(r"(?m)^\s*module\s+([A-Za-z_]\w*)", text))

    if not names:
        sys.exit("found no module declarations in %s" % SRC)

    out = ["// GENERATED by scripts/make_ref.py - do not edit.\n",
           "// rtl_ref/*.v with every module renamed ref_* so the mirror-equivalence\n",
           "// testbench can elaborate it alongside the ChipInventor blocks.\n\n"]

    renamed = 0
    for fname in files:
        text = bodies[fname]
        for name in names:
            text, n1 = re.subn(r"(?m)^(\s*)module\s+%s\b" % re.escape(name),
                               r"\1module ref_%s" % name, text)
            text, n2 = re.subn(r"(?m)^(\s*)%s(\s+|\s*#)" % re.escape(name),
                               r"\1ref_%s\2" % name, text)
            renamed += n1 + n2
        out.append("// ---- from rtl_ref/%s ----\n" % fname)
        out.append(text)
        out.append("\n")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("".join(out))

    # Every module must have been renamed, or the elaboration will collide.
    leftover = re.findall(r"(?m)^\s*module\s+(?!ref_)([A-Za-z_]\w*)", "".join(out))
    if leftover:
        sys.exit("FAIL: these modules were not renamed: %s" % ", ".join(sorted(set(leftover))))

    print("wrote %s: %d modules, %d rewrites" % (OUT, len(names), renamed))


if __name__ == "__main__":
    main()
