#!/usr/bin/env python3
"""Emit build/ref_renamed.v: rtl_ref/*.v with every module renamed ref_*.

The mirror-equivalence testbench elaborates the ChipInventor blocks and the
original design side by side, but they define modules of the same names (alu,
dmem, control_unit, ...). Rather than maintain a second hand-edited copy of the
reference - which would defeat the point of comparing against it - this rewrites
the frozen rtl_ref snapshot mechanically at build time.

With --src/--prefix/--out it renames any other RTL directory the same way; the
repository-root flow uses that to elaborate the current rtl/ (as s3ref_*)
beside the ChipInventor mirror for the Stage 3 flat-versus-hierarchical check.

Only two things are rewritten, both anchored so they cannot touch anything else:
  * `module NAME`           -> `module PREFIXNAME`
  * a line that starts with NAME followed by whitespace or `#`, which in this
    codebase is always an instantiation (every instance is named u_*)

Signal names are never touched: word boundaries mean `alu` does not match
`alu_op`, and no port connection in this codebase begins a line with a bare
module name.
"""

import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "rtl_ref")
OUT = os.path.join(ROOT, "build", "ref_renamed.v")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default=SRC)
    ap.add_argument("--prefix", default="ref_")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    files = sorted(f for f in os.listdir(args.src) if f.endswith(".v"))
    if not files:
        sys.exit("no .v files in %s" % args.src)

    names = []
    bodies = {}
    for fname in files:
        with open(os.path.join(args.src, fname), encoding="utf-8") as fh:
            text = fh.read()
        bodies[fname] = text
        names.extend(re.findall(r"(?m)^\s*module\s+([A-Za-z_]\w*)", text))

    if not names:
        sys.exit("found no module declarations in %s" % args.src)

    src_name = os.path.basename(os.path.normpath(args.src))
    out = ["// GENERATED by scripts/make_ref.py - do not edit.\n",
           "// %s/*.v with every module renamed %s* so an equivalence\n" % (src_name, args.prefix),
           "// testbench can elaborate it alongside the ChipInventor blocks.\n\n"]

    renamed = 0
    for fname in files:
        text = bodies[fname]
        for name in names:
            text, n1 = re.subn(r"(?m)^(\s*)module\s+%s\b" % re.escape(name),
                               r"\1module %s%s" % (args.prefix, name), text)
            text, n2 = re.subn(r"(?m)^(\s*)%s(\s+|\s*#)" % re.escape(name),
                               r"\1%s%s\2" % (args.prefix, name), text)
            renamed += n1 + n2
        out.append("// ---- from %s/%s ----\n" % (src_name, fname))
        out.append(text)
        out.append("\n")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("".join(out))

    # Every module must have been renamed, or the elaboration will collide.
    leftover = re.findall(r"(?m)^\s*module\s+(?!%s)([A-Za-z_]\w*)" % re.escape(args.prefix),
                          "".join(out))
    if leftover:
        sys.exit("FAIL: these modules were not renamed: %s" % ", ".join(sorted(set(leftover))))

    print("wrote %s: %d modules, %d rewrites" % (args.out, len(names), renamed))


if __name__ == "__main__":
    main()
