// ============================================================================
// crc_unit.v - CRCB/CRCH/CRCW (Xicrc). Combinational, zero-latency.
//
// GENERATED by chipinventor/scripts/gen_crc_xor.py; do not hand-edit.
//
// Structure follows Block Guide S3.1.3: three independent CRC blocks, one per
// input width (8 / 16 / 32 bits), each an algebraically unrolled XOR network,
// feeding a single output multiplexer selected per Table 11. Each block is
// written as byte updates - the eight LFSR steps of one byte already combined
// into the standard CRC-CCITT formula - so it is shifts and XORs only, and
// synthesis flattens it into the same XOR network as the bit-serial form.
// `gen_crc_xor.py --prove` shows this block and the Phase 2 one
// (rtl_ref/crc_unit.v, the same CRC as a bit-by-bit function loop) equal on
// every input: both are GF(2)-linear, and they agree on every basis vector.
//
// Why not the bit loop: in a simulator it re-runs 56 interpreted LFSR steps
// whenever a register operand changes, nearly every instruction. On the lane
// firmware that made simulating the chip about 2.7 times slower, which is the
// difference between fitting the ChipInventor simulator's time window or not.
//
// Algorithm: CRC-16-CCITT-FALSE (poly 0x1021, MSB-first, no input/output
// reflection, no final XOR), confirmed against the official validation
// firmware - all three widths chain to its expected 0x1E82.
//
// OPERAND ROLES (rs1 = data, rs2 = accumulator)
// -------------------------------------------------------------------
// The official validation firmware accumulates the CRC in rs2 and passes the
// new data in rs1:
//
//     crcb s0, s1, s0     # rd=s0, rs1=s1 (data byte), rs2=s0 (CRC so far)
//
// CRCB/CRCH/CRCW select how many bits of rs1 (8/16/32, MSB-first) are folded
// into one CRC-16 update - one shared CRC-16 algorithm over three input
// widths, not three different CRC algorithms.
// ============================================================================
module crc_unit (
    input  wire [31:0] rs1_data, // data to fold in
    input  wire [31:0] rs2_data, // running CRC / seed (low 16 bits used)
    input  wire [2:0]  funct3,   // 000=CRCB(8b) 001=CRCH(16b) 010=CRCW(32b)
    output reg  [31:0] result
);
    wire [15:0] seed = rs2_data[15:0];

    // One byte folded in, MSB first: the CRC-16/CCITT byte update, which is
    // the eight LFSR steps of the bit-serial definition already combined
    // (x is the byte's feedback; x << 12, x << 5 and x are where the
    // polynomial 0x1021 puts it). Shifts and XORs only.
    function [15:0] step8;
        input [15:0] c;
        input [7:0]  b;
        reg   [7:0]  x;
        begin
            x = c[15:8] ^ b;
            x = x ^ (x >> 4);
            step8 = {c[7:0], 8'h00} ^ {x[3:0], 12'h000} ^ {3'b000, x, 5'b00000} ^ {8'h00, x};
        end
    endfunction

    // ---- Block 1: CRCB, 8-bit input ------------------------------------
    // ---- Block 2: CRCH, 16-bit input: its two bytes, high first ----------
    // ---- Block 3: CRCW, 32-bit input: its four bytes, high first ---------
    // ---- Output multiplexer (Block Guide Table 11) ----------------------
    // Only the selected block is evaluated, which is what keeps a simulator
    // from recomputing three CRCs on every register-operand change.
    always @(*) begin
        case (funct3[1:0])
            2'b00:   result = {16'b0, step8(seed, rs1_data[7:0])};                        // CRCB
            2'b01:   result = {16'b0, step8(step8(seed, rs1_data[15:8]), rs1_data[7:0])}; // CRCH
            2'b10:   result = {16'b0, step8(step8(step8(step8(seed, rs1_data[31:24]),
                                                        rs1_data[23:16]),
                                                  rs1_data[15:8]),
                                            rs1_data[7:0])};                            // CRCW
            default: result = {16'b0, seed};  // unused encoding: seed passes through
        endcase
    end
endmodule
