// ============================================================================
// wb_mux_32.v - writeback source multiplexer.
//
// Selects which unit's result is committed to the register file, from
// control_unit's wb_src_sel. This was the `case (wb_src_sel)` block inside
// riscv_core.v; the project canvas holds no logic of its own, so it becomes a
// real block.
//
// Encoding is control_unit's, unchanged:
//   000  alu_result     ALU-reg / ALU-imm / LUI / AUIPC
//   001  mult_result    Zmmul
//   010  crc_result     Xicrc
//   011  lsu_load_data  loads
//   100  pc_plus_4      JAL / JALR link
//
// The inputs are named for their sources rather than A..H so the canvas shows
// what is actually being selected. Selects 101/110/111 are never generated by
// control_unit; they fall through to alu_result, matching the original
// `default:` leg exactly rather than producing a distinct undefined value.
// ============================================================================
module wb_mux_32 (
    input  wire [31:0] alu_result,
    input  wire [31:0] mult_result,
    input  wire [31:0] crc_result,
    input  wire [31:0] lsu_load_data,
    input  wire [31:0] pc_plus_4,
    input  wire [2:0]  wb_src_sel,
    output reg  [31:0] wb_data
);
    always @(*) begin
        case (wb_src_sel)
            3'b001:  wb_data = mult_result;
            3'b010:  wb_data = crc_result;
            3'b011:  wb_data = lsu_load_data;
            3'b100:  wb_data = pc_plus_4;
            default: wb_data = alu_result;
        endcase
    end
endmodule
