// GENERATED by chipinventor/scripts/gen_pnr_netlist.py - do not hand-edit.
// Source: top.v
// ROM:    742 words replaced by the 3-word mock (firmware repo README)
// DMEM:   DMEM_WORDS = 8
// This is the P&R variant. The functional netlist is ../../top.v.



//  ---------- INLCUDED BLOCK: address_decoder  ---------- 
// ============================================================================
// address_decoder.v - routes the core's single memory-transaction interface
// to IMEM or DMEM based on address range, and muxes read data back.
//
// Every signal routed to a memory is explicitly qualified by that memory's
// own select (imem_sel / dmem_sel) - NOT just "routed to DMEM" in general -
// otherwise an out-of-range store could alias into a real DMEM write
// ============================================================================
module address_decoder (
    input  wire [31:0] address_i,
    input  wire        we_i,
    input  wire        oe_i,
    input  wire [3:0]  bw_i,
    input  wire [31:0] imem_rdata,
    input  wire [31:0] dmem_rdata,
    output wire        imem_oe_o,
    output wire        dmem_we_o,
    output wire        dmem_oe_o,
    output wire [3:0]  dmem_bw_o,
    output wire [31:0] data_o
);
    localparam [31:0] IMEM_BASE = 32'h0040_0000;
    localparam [31:0] IMEM_LAST = 32'h007F_FFFF; // 4MB architectural window
    localparam [31:0] DMEM_BASE = 32'h1001_0000;
    localparam [31:0] DMEM_LAST = 32'h1001_1FFF; // 8kB window

    wire imem_sel = (address_i >= IMEM_BASE) && (address_i <= IMEM_LAST);
    wire dmem_sel = (address_i >= DMEM_BASE) && (address_i <= DMEM_LAST);

    // IMEM has no write port at all (Block Guide §4.4) - we_o never routed there.
    assign imem_oe_o = oe_i & imem_sel;
    assign dmem_oe_o = oe_i & dmem_sel;
    assign dmem_we_o = we_i & dmem_sel;
    assign dmem_bw_o = bw_i & {4{dmem_sel}};

    assign data_o = dmem_sel ? dmem_rdata : (imem_sel ? imem_rdata : 32'b0);
endmodule



//  ---------- INLCUDED BLOCK: alu  ---------- 
// ============================================================================
// alu.v - Arithmetic/Logic Unit
// Implements Block Guide Table 9 (11 ops). Shared by ALU-reg, ALU-imm,
// LUI (PASS_B), AUIPC/branch-target/jump-target/load-store address (ADD).
// Purely combinational.
// ============================================================================
module alu (
    input  wire [31:0] a,
    input  wire [31:0] b,
    input  wire [3:0]  alu_op,
    output reg  [31:0] result
);
    localparam [3:0]
        ALU_PASS_B = 4'h0,
        ALU_ADD    = 4'h1,
        ALU_SUB    = 4'h2,
        ALU_AND    = 4'h3,
        ALU_OR     = 4'h4,
        ALU_XOR    = 4'h5,
        ALU_SLL    = 4'h6,
        ALU_SRL    = 4'h7,
        ALU_SRA    = 4'h8, // "MRS" in Block Guide Table 9
        ALU_SLT    = 4'h9,
        ALU_SLTU   = 4'hA;

    always @(*) begin
        case (alu_op)
            ALU_PASS_B: result = b;
            ALU_ADD:    result = a + b;
            ALU_SUB:    result = a - b;
            ALU_AND:    result = a & b;
            ALU_OR:     result = a | b;
            ALU_XOR:    result = a ^ b;
            ALU_SLL:    result = a << b[4:0];
            ALU_SRL:    result = a >> b[4:0];
            ALU_SRA:    result = $signed(a) >>> b[4:0];
            ALU_SLT:    result = ($signed(a) < $signed(b)) ? 32'd1 : 32'd0;
            ALU_SLTU:   result = (a < b) ? 32'd1 : 32'd0;
            default:    result = 32'd0; // safe default, no latch
        endcase
    end
endmodule



//  ---------- INLCUDED BLOCK: branch_comparator  ---------- 
// ============================================================================
// branch_comparator.v - evaluates the 6 RV32I branch conditions.
// Purely combinational, kept separate from the ALU.
// ============================================================================
module branch_comparator (
    input  wire [31:0] rs1_data,
    input  wire [31:0] rs2_data,
    input  wire [2:0]  funct3,
    output reg         branch_taken
);
    always @(*) begin
        case (funct3)
            3'b000: branch_taken = (rs1_data == rs2_data);                       // BEQ
            3'b001: branch_taken = (rs1_data != rs2_data);                       // BNE
            3'b100: branch_taken = ($signed(rs1_data) <  $signed(rs2_data));     // BLT
            3'b101: branch_taken = ($signed(rs1_data) >= $signed(rs2_data));     // BGE
            3'b110: branch_taken = (rs1_data <  rs2_data);                       // BLTU
            3'b111: branch_taken = (rs1_data >= rs2_data);                       // BGEU
            default: branch_taken = 1'b0; // funct3 010/011 unused by RV32I branches
        endcase
    end
endmodule



//  ---------- INLCUDED BLOCK: control_unit  ---------- 
// ============================================================================
// control_unit.v - Central FSM. Decodes instruction class from `ir` (full
// {opcode,funct3,funct7} tuple matching, not opcode alone), sequences
// the 6 states, and generates every datapath control signal.
//
// States: RESET, FETCH, DECODE, EXECUTE, MEMORY, WRITEBACK.
// Cycle counts: branch=3, store=4, ALU/mul/crc/jump/fence/
// ecall/ebreak/illegal=4, load=5.
//
// Every combinational output is gated by rst_i directly (not only via the
// state register having reached RESET) so an in-flight operation is
// aborted the same cycle reset asserts, not one cycle later.
// ============================================================================
module control_unit (
    input  wire        clk_i,
    input  wire        rst_i,
    input  wire [31:0] ir,
    input  wire        branch_taken,

    output wire [2:0]  state_o,

    output wire        alu_src_a_sel,   // 0=rs1_data, 1=pc
    output wire        alu_src_b_sel,   // 0=rs2_data, 1=imm
    output reg  [3:0]  alu_op,
    output wire        addr_src_sel,    // 0=pc, 1=alu_result
    output reg  [2:0]  wb_src_sel,      // 000=alu 001=mult 010=crc 011=lsu_load 100=pc+4
    output wire        pc_src_sel,      // 0=pc+4, 1=alu_result(target)

    output wire        pc_write,
    output wire        reg_write,
    output wire        we_o,
    output wire        oe_o,
    output wire        ir_write,
    output wire sys_event_o,

    output wire        is_valid_store,
    output wire [2:0]  op_size
);
    localparam [2:0]
        S_RESET     = 3'd0,
        S_FETCH     = 3'd1,
        S_DECODE    = 3'd2,
        S_EXECUTE   = 3'd3,
        S_MEMORY    = 3'd4,
        S_WRITEBACK = 3'd5;

    // (* keep *) - see dmem.v for why this is needed (zero-output top level).
    (* keep *) reg [2:0] state, next_state;
    assign state_o = state;

    // ---------------- Instruction fields --------------------------------
    wire [6:0]  opcode = ir[6:0];
    wire [2:0]  funct3 = ir[14:12];
    wire [6:0]  funct7 = ir[31:25];

    // ---------------- Full-tuple instruction class decode (§9.1) --------
    wire op_rtype  = (opcode == 7'b0110011);
    wire op_itype  = (opcode == 7'b0010011);
    wire op_load   = (opcode == 7'b0000011);
    wire op_store  = (opcode == 7'b0100011);
    wire op_branch = (opcode == 7'b1100011);
    wire op_jal    = (opcode == 7'b1101111);
    wire op_jalr   = (opcode == 7'b1100111);
    wire op_lui    = (opcode == 7'b0110111);
    wire op_auipc  = (opcode == 7'b0010111);
    wire op_fence  = (opcode == 7'b0001111);

    // ALU-reg: funct7=0000000 for all 8 base funct3 values; SUB(000)/SRA(101)
    // may additionally use funct7=0100000. Any other funct7 is illegal.
    wire alu_reg_f7_ok = (funct7 == 7'b0000000) ||
                         ((funct7 == 7'b0100000) && (funct3 == 3'b000 || funct3 == 3'b101));
    wire is_alu_reg = op_rtype && alu_reg_f7_ok;

    wire is_mul = op_rtype && (funct7 == 7'b0000001) && !funct3[2]; // Zmmul: funct3 000-011 only
    wire is_crc = op_rtype && (funct7 == 7'b1000000) &&
                  (funct3 == 3'b000 || funct3 == 3'b001 || funct3 == 3'b010);

    // ALU-imm: SLLI/SRLI/SRAI need imm[11:5] to be exactly 0000000/0100000;
    // every other funct3 has no funct7-equivalent constraint.
    wire shift_f7_ok = (funct3 == 3'b001) ? (ir[31:25] == 7'b0000000)
                                          : ((ir[31:25] == 7'b0000000) || (ir[31:25] == 7'b0100000));
    wire is_shift_imm = (funct3 == 3'b001) || (funct3 == 3'b101);
    wire is_alu_imm = op_itype && (!is_shift_imm || shift_f7_ok);

    wire is_load  = op_load  && (funct3 == 3'b000 || funct3 == 3'b001 || funct3 == 3'b010 ||
                                  funct3 == 3'b100 || funct3 == 3'b101);
    wire is_store = op_store && (funct3 == 3'b000 || funct3 == 3'b001 || funct3 == 3'b010);
    wire is_branch = op_branch && (funct3 == 3'b000 || funct3 == 3'b001 || funct3 == 3'b100 ||
                                    funct3 == 3'b101 || funct3 == 3'b110 || funct3 == 3'b111);
    wire is_jal  = op_jal;
    wire is_jalr = op_jalr && (funct3 == 3'b000);
    wire is_lui  = op_lui;
    wire is_auipc = op_auipc;
    // ECALL/EBREAK are single fixed encodings in RV32I - match them exactly
    // (rs1/rd/funct7 all zero) so no other SYSTEM-opcode word can pulse
    // sys_event_o and be mistaken for a firmware validation checkpoint.
    wire is_ecall_ebreak = (ir == 32'h0000_0073) || (ir == 32'h0010_0073);
    wire is_fence = op_fence; // NOP regardless of fm/pred/succ fields

    wire is_recognized = is_alu_reg || is_mul || is_crc || is_alu_imm || is_load || is_store ||
                         is_branch || is_jal || is_jalr || is_lui || is_auipc ||
                         is_ecall_ebreak || is_fence;
    wire is_illegal = ~is_recognized;

    assign is_valid_store = is_store;
    assign op_size = funct3;

    // ---------------- ALU op select (Table 9 decode) ---------------------
    always @(*) begin
        if (is_alu_reg) begin
            case (funct3)
                3'b000:  alu_op = funct7[5] ? 4'h2 : 4'h1; // SUB : ADD
                3'b001:  alu_op = 4'h6;                    // SLL
                3'b010:  alu_op = 4'h9;                    // SLT
                3'b011:  alu_op = 4'hA;                    // SLTU
                3'b100:  alu_op = 4'h5;                    // XOR
                3'b101:  alu_op = funct7[5] ? 4'h8 : 4'h7; // SRA : SRL
                3'b110:  alu_op = 4'h4;                    // OR
                3'b111:  alu_op = 4'h3;                    // AND
                default: alu_op = 4'h0;
            endcase
        end else if (is_alu_imm) begin
            case (funct3)
                3'b000:  alu_op = 4'h1; // ADDI
                3'b010:  alu_op = 4'h9; // SLTI
                3'b011:  alu_op = 4'hA; // SLTIU
                3'b100:  alu_op = 4'h5; // XORI
                3'b110:  alu_op = 4'h4; // ORI
                3'b111:  alu_op = 4'h3; // ANDI
                3'b001:  alu_op = 4'h6; // SLLI
                3'b101:  alu_op = ir[30] ? 4'h8 : 4'h7; // SRAI : SRLI
                default: alu_op = 4'h0;
            endcase
        end else if (is_lui) begin
            alu_op = 4'h0; // PASS_B
        end else begin
            alu_op = 4'h1; // ADD: AUIPC / branch target / jump target / load-store addr / JALR
        end
    end

    // ---------------- Datapath mux selects --------------------------------
    assign alu_src_a_sel = is_auipc || is_branch || is_jal;         // else rs1_data (incl. JALR)
    assign alu_src_b_sel = ~(is_alu_reg || is_mul || is_crc);       // else rs2_data

    assign addr_src_sel = (state == S_EXECUTE && (is_load || is_store)) ||
                          (state == S_MEMORY) ||
                          (state == S_WRITEBACK && is_load);

    always @(*) begin
        if (is_mul)              wb_src_sel = 3'b001;
        else if (is_crc)         wb_src_sel = 3'b010;
        else if (is_load)        wb_src_sel = 3'b011;
        else if (is_jal||is_jalr) wb_src_sel = 3'b100;
        else                     wb_src_sel = 3'b000; // ALU-class default
    end

    assign pc_src_sel = (is_branch && branch_taken) || is_jal || is_jalr;

    // ---------------- State register --------------------------------------
    always @(posedge clk_i) begin
        if (rst_i) state <= S_RESET;
        else       state <= next_state;
    end

    // ---------------- Next-state logic (§8.2) ------------------------------
    always @(*) begin
        case (state)
            S_RESET:     next_state = S_FETCH;
            S_FETCH:     next_state = S_DECODE;
            S_DECODE:    next_state = S_EXECUTE;
            S_EXECUTE: begin
                if (is_load || is_store) next_state = S_MEMORY;
                else if (is_branch)      next_state = S_FETCH;
                else                      next_state = S_WRITEBACK;
            end
            S_MEMORY: begin
                if (is_load) next_state = S_WRITEBACK;
                else         next_state = S_FETCH; // store
            end
            S_WRITEBACK: next_state = S_FETCH;
            default:     next_state = S_FETCH;
        endcase
    end

    // ---------------- Output logic, gated by rst_i directly (§9.1 fix) -----
    // FSM guarantees only branch reaches EXECUTE-terminal, only store
    // reaches MEMORY-terminal, and every other class (incl. load) reaches
    // WRITEBACK - so "state==S_WRITEBACK" alone is sufficient for those.
    assign ir_write = ~rst_i && (state == S_FETCH);

    assign pc_write = ~rst_i && ( (state == S_EXECUTE && is_branch) ||
                                  (state == S_MEMORY  && is_store) ||
                                  (state == S_WRITEBACK) );

    assign reg_write = ~rst_i && (state == S_WRITEBACK) &&
                       !(is_fence || is_illegal || is_ecall_ebreak);

    assign we_o = ~rst_i && (state == S_MEMORY) && is_store;

    assign oe_o = ~rst_i && ( (state == S_FETCH) ||
                              (state == S_MEMORY   && is_load) ||
                              (state == S_WRITEBACK && is_load) );

    assign sys_event_o = ~rst_i && (state == S_EXECUTE) && is_ecall_ebreak;

endmodule



//  ---------- INLCUDED BLOCK: crc_unit  ---------- 
// ============================================================================
// crc_unit.v - CRCB/CRCH/CRCW (Xicrc). Combinational, zero-latency
//
// Structure follows Block Guide S3.1.3: three independent CRC
// blocks, one per input width (8 / 16 / 32 bits), each an algebraically
// unrolled parallel-XOR network, feeding a single output multiplexer
// selected per Table 11. Each block's `for` loop has constant bounds, so it
// flattens at elaboration into a flat XOR tree with no per-stage bypass
// muxing and no variable bit-selects.
//
// Algorithm: CRC-16-CCITT-FALSE (poly 0x1021, MSB-first, no input/output
// reflection, no final XOR), confirmed against the official validation
// firmware - all three widths chain to its expected 0x1E82.
//
// OPERAND ROLES (rs1 = data, rs2 = accumulator)
// -------------------------------------------------------------------
// The official validation firmware accumulates the CRC in rs2 and passes the
// new data in rs1:
//
//     crcb s0, s1, s0     # rd=s0, rs1=s1 (data byte), rs2=s0 (CRC so far)
//
// CRCB/CRCH/CRCW select how many bits of rs1 (8/16/32, MSB-first) are folded
// into one CRC-16 update - one shared CRC-16 algorithm over three input
// widths, not three different CRC algorithms.
// ============================================================================
module crc_unit (
    input  wire [31:0] rs1_data, // data to fold in
    input  wire [31:0] rs2_data, // running CRC / seed (low 16 bits used)
    input  wire [2:0]  funct3,   // 000=CRCB(8b) 001=CRCH(16b) 010=CRCW(32b)
    output reg  [31:0] result
);
    localparam [15:0] CRC16_POLY = 16'h1021;

    // One bit-serial LFSR step, MSB-first. Unrolling this over a constant
    // number of data bits is what turns the bit-serial definition into the
    // combinational XOR network each of the three blocks below is.
    function [15:0] crc16_step;
        input [15:0] crc_in;
        input        data_bit;
        reg          fb;
        begin
            fb = crc_in[15] ^ data_bit;
            crc16_step = {crc_in[14:0], 1'b0} ^ (fb ? CRC16_POLY : 16'h0000);
        end
    endfunction

    // ---- Block 1: CRCB, 8-bit input ------------------------------------
    function [15:0] crc16_b;
        input [15:0] seed;
        input [7:0]  data;
        integer i;
        reg [15:0] c;
        begin
            c = seed;
            for (i = 7; i >= 0; i = i - 1) c = crc16_step(c, data[i]);
            crc16_b = c;
        end
    endfunction

    // ---- Block 2: CRCH, 16-bit input -----------------------------------
    function [15:0] crc16_h;
        input [15:0] seed;
        input [15:0] data;
        integer i;
        reg [15:0] c;
        begin
            c = seed;
            for (i = 15; i >= 0; i = i - 1) c = crc16_step(c, data[i]);
            crc16_h = c;
        end
    endfunction

    // ---- Block 3: CRCW, 32-bit input -----------------------------------
    function [15:0] crc16_w;
        input [15:0] seed;
        input [31:0] data;
        integer i;
        reg [15:0] c;
        begin
            c = seed;
            for (i = 31; i >= 0; i = i - 1) c = crc16_step(c, data[i]);
            crc16_w = c;
        end
    endfunction

    wire [15:0] seed  = rs2_data[15:0];
    wire [15:0] crc_b = crc16_b(seed, rs1_data[7:0]);
    wire [15:0] crc_h = crc16_h(seed, rs1_data[15:0]);
    wire [15:0] crc_w = crc16_w(seed, rs1_data[31:0]);

    // ---- Output multiplexer (Block Guide Table 11) ----------------------
    always @(*) begin
        case (funct3[1:0])
            2'b00:   result = {16'b0, crc_b}; // CRCB
            2'b01:   result = {16'b0, crc_h}; // CRCH
            2'b10:   result = {16'b0, crc_w}; // CRCW
            default: result = {16'b0, seed};  // unused encoding: seed passes through
        endcase
    end
endmodule



//  ---------- INLCUDED BLOCK: dmem  ---------- 
// ============================================================================
// dmem.v - Data SRAM, word-addressed internally, byte-writable via bw_i.
// Synchronous 1-cycle read AND write (Block Guide S4.3, MANDATORY) - the
// registered read is what the no-ALUOut/no-MDR datapath timing relies on.
//
// Block Guide S4.3: "the memory maintains n 4-byte words, where n is the
// total size of the memory in bytes divided by 4", with the architectural
// window fixed at 8kB (Table 13). DMEM_WORDS therefore sets the instantiated
// capacity while the decoder keeps range-checking the full 8kB window; the
// impl_sel guard below is what makes an address inside that window but beyond
// the instantiated array read back 0 and write nothing, instead of aliasing
// into a real word. That guard is also the resize knob: if place-and-route
// cannot absorb 2048 words (65,536 flip-flops), DMEM_WORDS drops to 1024 or
// 512 with no other edit anywhere and no rewiring.
//
// rst_i is unused by this realization and is kept only so the block's port
// list stays stable if a reset-aware memory is substituted later.
// ============================================================================
module dmem #(
    parameter DMEM_WORDS = 2048 // 8kB / 4 bytes-per-word (architectural max)
) (
    input  wire        clk_i,
    input  wire        rst_i,
    input  wire [31:0] address_i, // full byte address
    input  wire        we_i,
    input  wire        oe_i,
    input  wire [3:0]  bw_i,
    input  wire [31:0] data_i,
    output wire [31:0] data_o
);
    // Full architectural word index within the 8kB window (Table 13), plus the
    // implemented-range guard.
    wire [10:0] word_addr = address_i[12:2];
    wire        impl_sel  = (word_addr < DMEM_WORDS);

    // (* keep *) prevents synthesis tools from concluding this array is
    // unobservable dead logic. `top` deliberately has zero data outputs
    // (Block Guide S2.2), so a flow that eliminates logic with no path to a
    // primary output would otherwise remove this entire design. Purely a
    // synthesis hint; has no effect on simulation.
    (* keep *) reg [31:0] mem [0:DMEM_WORDS-1];
    localparam AWIDTH = (DMEM_WORDS <= 1) ? 1 : $clog2(DMEM_WORDS);
    wire [AWIDTH-1:0] phys_addr = word_addr[AWIDTH-1:0];

    reg [31:0] data_r;
    assign data_o = data_r;

    always @(posedge clk_i) begin
        if (we_i && impl_sel) begin
            if (bw_i[0]) mem[phys_addr][7:0]   <= data_i[7:0];
            if (bw_i[1]) mem[phys_addr][15:8]  <= data_i[15:8];
            if (bw_i[2]) mem[phys_addr][23:16] <= data_i[23:16];
            if (bw_i[3]) mem[phys_addr][31:24] <= data_i[31:24];
        end else if (oe_i) begin
            data_r <= impl_sel ? mem[phys_addr] : 32'b0;
        end
    end
endmodule



//  ---------- INLCUDED BLOCK: imem  ---------- 
// ============================================================================
// imem.v - Instruction/constant ROM. Combinational read: "Upon receiving the
// memory address to be accessed and a read signal (output enable), the 32-bit
// instruction that was in that position is received by the kernel" (Block
// Guide S4.2 - no cycle-latency language, unlike DMEM's S4.3).
//
// The official firmware MUST stay at word 0: it is position-dependent, and
// derives its .bss base from the PC (auipc s0, 0xfc10 at 0x0040011C gives
// 0x10010000, which is DMEM_BASE). The supplementary program is
// position-independent and is placed above it.
//
// The *architectural* window is the full 4MB at 0x00400000 (Table 13), which
// address_decoder range-checks against. The ROM below covers only the words
// the images actually occupy; any address inside the 4MB window but past or
// between them falls to the `default` leg and reads back 0 rather than
// aliasing into a real word. That is the same guarantee the file-driven
// version's impl_sel comparison gave.
// ============================================================================
module imem (
    input  wire [31:0] address_i,    // full byte address (already imem_sel-gated by decoder)
    input  wire        oe_i,
    output reg  [31:0] data_o
);
    // Word index within the 4MB architectural window, identical to imem.v.
    wire [19:0] word_addr = address_i[21:2];

    always @(*) begin
        if (!oe_i) data_o = 32'b0;
        else begin
            case (word_addr)
                20'd0     : data_o = 32'h00a00293; // addi x5, x0, 10
                20'd1     : data_o = 32'h00500313; // addi x6, x0, 5
                20'd2     : data_o = 32'h006283b3; // add  x7, x5, x6
                default   : data_o = 32'h00000013; // nop
            endcase
        end
    end
endmodule



//  ---------- INLCUDED BLOCK: immediate_generator  ---------- 
// ============================================================================
// immediate_generator.v - extracts & sign-extends I/S/B/U/J immediates.
// Purely combinational.
// ============================================================================
module immediate_generator (
    input  wire [31:0] ir,
    output reg  [31:0] imm
);
    wire [6:0] opcode = ir[6:0];

    localparam [6:0]
        OPC_LOAD   = 7'b0000011,
        OPC_ALUIMM = 7'b0010011,
        OPC_JALR   = 7'b1100111,
        OPC_STORE  = 7'b0100011,
        OPC_BRANCH = 7'b1100011,
        OPC_LUI    = 7'b0110111,
        OPC_AUIPC  = 7'b0010111,
        OPC_JAL    = 7'b1101111;

    always @(*) begin
        case (opcode)
            OPC_LOAD, OPC_ALUIMM, OPC_JALR: // I-type
                imm = {{20{ir[31]}}, ir[31:20]};
            OPC_STORE: // S-type
                imm = {{20{ir[31]}}, ir[31:25], ir[11:7]};
            OPC_BRANCH: // B-type, imm[0] architecturally 0
                imm = {{19{ir[31]}}, ir[31], ir[7], ir[30:25], ir[11:8], 1'b0};
            OPC_LUI, OPC_AUIPC: // U-type
                imm = {ir[31:12], 12'b0};
            OPC_JAL: // J-type, imm[0] architecturally 0
                imm = {{11{ir[31]}}, ir[31], ir[19:12], ir[20], ir[30:21], 1'b0};
            default:
                imm = 32'b0; // R-type / SYSTEM / FENCE: don't-care, datapath won't select it
        endcase
    end
endmodule



//  ---------- INLCUDED BLOCK: ir_fields  ---------- 
// ============================================================================
// ir_fields.v - extracts the three register-address fields from the
// instruction register.
//
// This block exists only because the project canvas cannot slice a bus: every
// connection it generates is a whole bus of exactly matching width, so
// `ir[19:15]` cannot be drawn as a wire. Keeping the extraction here lets
// register_file.v stay byte-identical to the verified original rather than
// growing an instruction port and slicing internally.
// ============================================================================
module ir_fields (
    input  wire [31:0] ir,
    output wire [4:0]  rs1_addr,
    output wire [4:0]  rs2_addr,
    output wire [4:0]  rd_addr
);
    assign rs1_addr = ir[19:15];
    assign rs2_addr = ir[24:20];
    assign rd_addr  = ir[11:7];
endmodule



//  ---------- INLCUDED BLOCK: ir_reg  ---------- 
// ============================================================================
// ir_reg.v - instruction register. Loaded exactly once per instruction,
// at the Fetch->Decode edge (ir_write asserted only during FETCH). This is
// the linchpin of the no-ALUOut/no-MDR datapath.
// ============================================================================
module ir_reg (
    input  wire        clk_i,
    input  wire        rst_i,
    input  wire        ir_write,
    input  wire [31:0] imem_data,
    // (* keep *) - see dmem.v for why this is needed (zero-output top level).
    output reg  [31:0] ir
);
    localparam [31:0] NOP = 32'h0000_0013; // ADDI x0,x0,0 - waveform readability only

    always @(posedge clk_i) begin
        if (rst_i)
            ir <= NOP;
        else if (ir_write)
            ir <= imem_data;
    end
endmodule



//  ---------- INLCUDED BLOCK: lsu  ---------- 
// ============================================================================
// lsu.v - Load/Store Unit. Converts between the core's byte/half/word
// transaction view and the flat word-addressed, byte-writable memory
// interface. Purely combinational.
//
// op_size is funct3 directly: op_size[1:0] = width (00/01/10 =
// byte/half/word), op_size[2] = unsigned-load flag.
//
// Misaligned half/word accesses are deliberately made a clean, deterministic
// no-op rather than left undefined: misaligned stores assert byte_write_o=0000
// (no write), misaligned loads return 0.
// ============================================================================
module lsu (
    input  wire [31:0] alu_result,     // effective address
    input  wire [31:0] rs2_data,       // register value to store
    input  wire [2:0]  op_size,        // = funct3
    input  wire        is_valid_store, // gates byte_write_o (§9.1 full-tuple decode)
    input  wire [31:0] mem_data_o,     // raw word read back from memory
    output reg  [31:0] core_data_i,    // extended load data -> WBSrc mux
    output reg  [3:0]  byte_write_o,   // bw_o
    output reg  [31:0] store_data_o    // positioned store data -> mem
);
    wire [1:0] addr_lsb        = alu_result[1:0];
    wire [1:0] size            = op_size[1:0];
    wire       load_unsigned   = op_size[2];

    // ---------------- Store path: byte-write mask + data positioning -----
    always @(*) begin
        byte_write_o = 4'b0000;
        store_data_o = 32'b0;
        if (is_valid_store) begin
            case (size)
                2'b00: begin // byte
                    case (addr_lsb)
                        2'b00: begin byte_write_o = 4'b0001; store_data_o = {24'b0, rs2_data[7:0]}; end
                        2'b01: begin byte_write_o = 4'b0010; store_data_o = {16'b0, rs2_data[7:0], 8'b0}; end
                        2'b10: begin byte_write_o = 4'b0100; store_data_o = {8'b0, rs2_data[7:0], 16'b0}; end
                        2'b11: begin byte_write_o = 4'b1000; store_data_o = {rs2_data[7:0], 24'b0}; end
                    endcase
                end
                2'b01: begin // half
                    case (addr_lsb)
                        2'b00: begin byte_write_o = 4'b0011; store_data_o = {16'b0, rs2_data[15:0]}; end
                        2'b10: begin byte_write_o = 4'b1100; store_data_o = {rs2_data[15:0], 16'b0}; end
                        default: begin byte_write_o = 4'b0000; store_data_o = 32'b0; end // misaligned
                    endcase
                end
                2'b10: begin // word
                    if (addr_lsb == 2'b00) begin byte_write_o = 4'b1111; store_data_o = rs2_data; end
                    else begin byte_write_o = 4'b0000; store_data_o = 32'b0; end // misaligned
                end
                default: begin byte_write_o = 4'b0000; store_data_o = 32'b0; end
            endcase
        end
    end

    // ---------------- Load path: extraction + sign/zero extension --------
    always @(*) begin
        case (size)
            2'b00: begin // byte
                case (addr_lsb)
                    2'b00: core_data_i = load_unsigned ? {24'b0, mem_data_o[7:0]}   : {{24{mem_data_o[7]}},  mem_data_o[7:0]};
                    2'b01: core_data_i = load_unsigned ? {24'b0, mem_data_o[15:8]}  : {{24{mem_data_o[15]}}, mem_data_o[15:8]};
                    2'b10: core_data_i = load_unsigned ? {24'b0, mem_data_o[23:16]} : {{24{mem_data_o[23]}}, mem_data_o[23:16]};
                    2'b11: core_data_i = load_unsigned ? {24'b0, mem_data_o[31:24]} : {{24{mem_data_o[31]}}, mem_data_o[31:24]};
                endcase
            end
            2'b01: begin // half
                case (addr_lsb)
                    2'b00: core_data_i = load_unsigned ? {16'b0, mem_data_o[15:0]}  : {{16{mem_data_o[15]}}, mem_data_o[15:0]};
                    2'b10: core_data_i = load_unsigned ? {16'b0, mem_data_o[31:16]} : {{16{mem_data_o[31]}}, mem_data_o[31:16]};
                    default: core_data_i = 32'b0; // misaligned
                endcase
            end
            2'b10: core_data_i = (addr_lsb == 2'b00) ? mem_data_o : 32'b0; // word / misaligned
            default: core_data_i = 32'b0;
        endcase
    end
endmodule



//  ---------- INLCUDED BLOCK: multiplier  ---------- 
// ============================================================================
// multiplier.v - MUL/MULH/MULHSU/MULHU (Zmmul). Combinational, single
// Execute cycle. funct3 directly drives operand-signedness
// and result-half selection per Table 10:
//
//   funct3   op       A signed   B signed   result
//   000      MUL      yes        yes        product[31:0]
//   001      MULH     yes        yes        product[63:32]
//   010      MULHSU   yes        no         product[63:32]
//   011      MULHU    no         no         product[63:32]
//
// NOTE: result_sel_upper must be (funct3[1] | funct3[0]), NOT funct3[0]
// alone -- funct3[0] alone is wrong specifically for MULHSU (funct3=010),
// where it evaluates to 0 (lower half) instead of the correct 1 (upper
// half).
// ============================================================================
module multiplier (
    input  wire [31:0] rs1_data,
    input  wire [31:0] rs2_data,
    input  wire [2:0]  funct3,
    output reg  [31:0] result
);
    wire a_signed    = ~(funct3[1] & funct3[0]); // 0 only for MULHU (011)
    wire b_signed    = ~funct3[1];               // 1 only for MUL/MULH (00x)
    wire sel_upper   = funct3[1] | funct3[0];    // 0 only for MUL (000)

    wire [63:0] a_ext = a_signed ? {{32{rs1_data[31]}}, rs1_data} : {32'b0, rs1_data};
    wire [63:0] b_ext = b_signed ? {{32{rs2_data[31]}}, rs2_data} : {32'b0, rs2_data};

    // Widen the assignment context to 128 bits so Icarus/Yosys evaluate the
    // multiply at full precision rather than truncating at 64 bits before
    // the low-64 slice is taken (standard Verilog context-width practice).
    wire [127:0] product_full = a_ext * b_ext;
    wire [63:0]  product      = product_full[63:0];

    always @(*) begin
        result = sel_upper ? product[63:32] : product[31:0];
    end
endmodule



//  ---------- INLCUDED BLOCK: mux2_32  ---------- 
// ============================================================================
// mux2_32.v - generic 2-to-1 32-bit multiplexer.
//
// The project canvas holds no logic of its own: every wire drawn on it is a
// whole-bus point-to-point connection, so a selection that used to be a single
// `assign x = s ? a : b;` inside riscv_core.v has to exist as a real block.
// Four instances cover every such selection in the datapath:
//
//   alu_a     S=alu_src_a_sel   A=rs1_data    B=pc
//   alu_b     S=alu_src_b_sel   A=rs2_data    B=imm
//   address   S=addr_src_sel    A=pc          B=alu_result
//   pc_next   S=pc_src_sel      A=pc_plus_4   B=alu_result
//
// Polarity matters when wiring: S=0 selects A, S=1 selects B. Every control
// signal above is named for the thing it selects when asserted, so the
// asserted case is always the B leg.
// ============================================================================
module mux2_32 (
    input  wire [31:0] a,
    input  wire [31:0] b,
    input  wire        s,
    output wire [31:0] z
);
    assign z = s ? b : a;
endmodule



//  ---------- INLCUDED BLOCK: pc_incrementer  ---------- 
// ============================================================================
// pc_incrementer.v - dedicated PC+4 adder, deliberately not the shared ALU,
// so it is available every cycle without needing an ALU cycle.
// ============================================================================
module pc_incrementer (
    input  wire [31:0] pc,
    output wire [31:0] pc_plus_4
);
    assign pc_plus_4 = pc + 32'd4;
endmodule



//  ---------- INLCUDED BLOCK: pc_reg  ---------- 
// ============================================================================
// pc_reg.v - program counter. Reset vector = IMEM base (0x00400000).
// Bits [1:0] forced to 0 on every load (covers JALR's
// "clear LSB" requirement and keeps PC always word-aligned, matching
// IMEM's word-only addressing).
// ============================================================================
module pc_reg (
    input  wire        clk_i,
    input  wire        rst_i,
    input  wire        pc_write,
    input  wire [31:0] pc_next,
    // (* keep *) - see dmem.v for why this is needed (zero-output top level).
    output reg  [31:0] pc
);
    localparam [31:0] RESET_VECTOR = 32'h0040_0000;

    always @(posedge clk_i) begin
        if (rst_i)
            pc <= RESET_VECTOR;
        else if (pc_write)
            pc <= {pc_next[31:2], 2'b00};
    end
endmodule



//  ---------- INLCUDED BLOCK: register_file  ---------- 
// ============================================================================
// register_file.v - 32 x 32-bit GPRs. x0 hardwired zero. Async read,
// synchronous write scoped to WriteBack by control_unit.
// ============================================================================
module register_file (
    input  wire        clk_i,
    input  wire        rst_i,
    input  wire [4:0]  rs1_addr,
    input  wire [4:0]  rs2_addr,
    input  wire [4:0]  rd_addr,
    input  wire [31:0] rd_data,
    input  wire        reg_write,
    output wire [31:0] rs1_data,
    output wire [31:0] rs2_data
);
    // (* keep *) - see dmem.v for why this is needed (zero-output top level).
    (* keep *) reg [31:0] regs [0:31];
    integer i;

    // Async reads; x0 read-side default is defense-in-depth (§9.8), the
    // write-guard below is what actually makes x0 permanently zero.
    assign rs1_data = (rs1_addr == 5'd0) ? 32'b0 : regs[rs1_addr];
    assign rs2_data = (rs2_addr == 5'd0) ? 32'b0 : regs[rs2_addr];

    always @(posedge clk_i) begin
        if (rst_i) begin
            for (i = 0; i < 32; i = i + 1) regs[i] <= 32'b0;
        end else if (reg_write && rd_addr != 5'd0) begin
            regs[rd_addr] <= rd_data;
        end
    end
endmodule



//  ---------- INLCUDED BLOCK: wb_mux_32  ---------- 
// ============================================================================
// wb_mux_32.v - writeback source multiplexer.
//
// Selects which unit's result is committed to the register file, from
// control_unit's wb_src_sel. This was the `case (wb_src_sel)` block inside
// riscv_core.v; the project canvas holds no logic of its own, so it becomes a
// real block.
//
// Encoding is control_unit's, unchanged:
//   000  alu_result     ALU-reg / ALU-imm / LUI / AUIPC
//   001  mult_result    Zmmul
//   010  crc_result     Xicrc
//   011  lsu_load_data  loads
//   100  pc_plus_4      JAL / JALR link
//
// The inputs are named for their sources rather than A..H so the canvas shows
// what is actually being selected. Selects 101/110/111 are never generated by
// control_unit; they fall through to alu_result, matching the original
// `default:` leg exactly rather than producing a distinct undefined value.
// ============================================================================
module wb_mux_32 (
    input  wire [31:0] alu_result,
    input  wire [31:0] mult_result,
    input  wire [31:0] crc_result,
    input  wire [31:0] lsu_load_data,
    input  wire [31:0] pc_plus_4,
    input  wire [2:0]  wb_src_sel,
    output reg  [31:0] wb_data
);
    always @(*) begin
        case (wb_src_sel)
            3'b001:  wb_data = mult_result;
            3'b010:  wb_data = crc_result;
            3'b011:  wb_data = lsu_load_data;
            3'b100:  wb_data = pc_plus_4;
            default: wb_data = alu_result;
        endcase
    end
endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire clk_i,
  input wire rst_i

);

//Internal Wires
 wire [31:0] w_1;
 wire [31:0] w_2;
 wire w_3;
 wire [31:0] w_4;
 wire [31:0] w_5;
 wire w_9;
 wire [31:0] w_10;
 wire w_13;
 wire w_14;
 wire [3:0] w_15;
 wire [31:0] w_16;
 wire [31:0] w_17;
 wire w_18;
 wire w_19;
 wire w_20;
 wire [3:0] w_21;
 wire [31:0] w_22;
 wire [31:0] w_24;
 wire [31:0] w_25;
 wire [4:0] w_26;
 wire [4:0] w_27;
 wire [4:0] w_28;
 wire [31:0] w_30;
 wire [31:0] w_31;
 wire w_32;
 wire [31:0] w_33;
 wire [31:0] w_37;
 wire w_43;
 wire [31:0] w_44;
 wire w_45;
 wire [31:0] w_46;
 wire [2:0] w_47;
 wire w_48;
 wire [3:0] w_49;
 wire [31:0] w_53;
 wire [31:0] w_55;
 wire w_57;
 wire [31:0] w_58;
 wire [2:0] w_59;
 wire w_60;
 wire w_62;

//Instances of Modules
mux2_32 blk3669_1 (
         .a (w_1),
         .b (w_2),
         .s (w_3),
         .z (w_4)
     );

pc_incrementer blk3670_3 (
         .pc_plus_4 (w_1),
         .pc (w_5)
     );

mux2_32 blk3669_4 (
         .a (w_5),
         .b (w_2),
         .s (w_9),
         .z (w_10)
     );

address_decoder blk3655_5 (
         .address_i (w_10),
         .we_i (w_13),
         .oe_i (w_14),
         .bw_i (w_15),
         .imem_rdata (w_16),
         .dmem_rdata (w_17),
         .imem_oe_o (w_18),
         .dmem_we_o (w_19),
         .dmem_oe_o (w_20),
         .dmem_bw_o (w_21),
         .data_o (w_22)
     );

imem blk3661_6 (
         .address_i (w_10),
         .data_o (w_16),
         .oe_i (w_18)
     );

dmem #(.DMEM_WORDS(8)) blk3660_7 (
         .clk_i (clk_i),
         .rst_i (rst_i),
         .address_i (w_10),
         .data_o (w_17),
         .we_i (w_19),
         .oe_i (w_20),
         .bw_i (w_21),
         .data_i (w_24)
     );

ir_fields blk3663_9 (
         .ir (w_25),
         .rs1_addr (w_26),
         .rs2_addr (w_27),
         .rd_addr (w_28)
     );

immediate_generator blk3662_10 (
         .ir (w_25),
         .imm (w_30)
     );

register_file blk3672_11 (
         .clk_i (clk_i),
         .rst_i (rst_i),
         .rs1_addr (w_26),
         .rs2_addr (w_27),
         .rd_addr (w_28),
         .rd_data (w_31),
         .reg_write (w_32),
         .rs1_data (w_33),
         .rs2_data (w_37)
     );

mux2_32 blk3669_12 (
         .a (w_33),
         .b (w_5),
         .s (w_43),
         .z (w_44)
     );

mux2_32 blk3669_13 (
         .b (w_30),
         .a (w_37),
         .s (w_45),
         .z (w_46)
     );

branch_comparator blk3657_14 (
         .rs1_data (w_33),
         .rs2_data (w_37),
         .funct3 (w_47),
         .branch_taken (w_48)
     );

alu blk3656_15 (
         .result (w_2),
         .a (w_44),
         .b (w_46),
         .alu_op (w_49)
     );

multiplier blk3666_16 (
         .rs1_data (w_33),
         .rs2_data (w_37),
         .funct3 (w_47),
         .result (w_53)
     );

crc_unit blk3659_17 (
         .rs1_data (w_33),
         .rs2_data (w_37),
         .funct3 (w_47),
         .result (w_55)
     );

lsu blk3665_18 (
         .byte_write_o (w_15),
         .mem_data_o (w_22),
         .store_data_o (w_24),
         .rs2_data (w_37),
         .alu_result (w_2),
         .op_size (w_47),
         .is_valid_store (w_57),
         .core_data_i (w_58)
     );

wb_mux_32 blk3673_19 (
         .pc_plus_4 (w_1),
         .wb_data (w_31),
         .alu_result (w_2),
         .mult_result (w_53),
         .crc_result (w_55),
         .lsu_load_data (w_58),
         .wb_src_sel (w_59)
     );

ir_reg blk3664_23 (
         .clk_i (clk_i),
         .rst_i (rst_i),
         .imem_data (w_22),
         .ir (w_25),
         .ir_write (w_60)
     );

pc_reg blk3671_24 (
         .clk_i (clk_i),
         .rst_i (rst_i),
         .pc_next (w_4),
         .pc (w_5),
         .pc_write (w_62)
     );

control_unit blk3658_25 (
         .clk_i (clk_i),
         .rst_i (rst_i),
         .pc_src_sel (w_3),
         .addr_src_sel (w_9),
         .we_o (w_13),
         .oe_o (w_14),
         .reg_write (w_32),
         .alu_src_a_sel (w_43),
         .alu_src_b_sel (w_45),
         .op_size (w_47),
         .branch_taken (w_48),
         .alu_op (w_49),
         .is_valid_store (w_57),
         .wb_src_sel (w_59),
         .ir_write (w_60),
         .ir (w_25),
         .pc_write (w_62)
     );


endmodule
