`timescale 1ns/1ps
// ============================================================================
//  RVBL-2 MULTICYCLE RISC-V CORE - COMBINED VERIFICATION SUITE
//  RV32I + Zmmul + Xicrc, 47 instructions
// ----------------------------------------------------------------------------
//  ChipInventor runs testbenches only at project level, so the sixteen
//  separate testbenches this design was verified with are combined here into
//  one file. Nothing is instantiated twice: the project's own `top` runs the
//  integration suites, and the unit suites instantiate individual blocks
//  directly, which works because the generated project file defines every
//  block module alongside `top`.
//
//  SUITE 0  Unit tests - every block on its own, directed corners plus
//           randomised sweeps against reference models written independently
//           of the RTL. Runs while the core is held in reset.
//  SUITE 1  Control FSM - a standalone control_unit driven through every
//           {opcode, funct3, funct7} combination the ISA can express.
//  SUITE 2A OFFICIAL VALIDATION FIRMWARE - the competition's own image, run
//           from the reset vector. Verdict is x4: 0 = PASS, -1 = FAIL.
//  SUITE 2B Integration - this project's supplementary program, covering what
//           the official firmware does not reach (FENCE, ECALL, EBREAK,
//           illegal instructions, misaligned access, 58 signatures).
//  SUITE 3  Reset stress - reset injected at forty different points in a
//           running program, checking in-flight writes are actually aborted,
//           then requiring both programs to still complete correctly.
//
//  THE ROM HOLDS TWO PROGRAMS
//  --------------------------
//    word   0..258  official validation firmware   (0x00400000, fixed)
//    word 259..511  gap, reads back 0
//    word 512..994  supplementary coverage program (0x00400800)
//
//  The official firmware cannot be relocated - it derives its .bss base from
//  the PC - so it owns the reset vector and 2B enters its program by pointing
//  the PC at SUPP_BASE while the core is still in reset.
//
//  DIFFERENCES FROM THE FILE-DRIVEN SUITE
//  --------------------------------------
//  * Golden vectors are computed here rather than read from files. The CRC and
//    immediate-generator tests used Python-generated vector files, which the
//    platform has no filesystem to read; the ref_* functions below replace
//    them and sweep further than the fixed vector sets did.
//  * The programs tb_core and tb_soc ran are folded into the one firmware
//    image, since a fixed case-ROM cannot be swapped between tests.
//  * DMEM is zeroed here rather than by an initial block inside the memory,
//    which keeps that initialisation out of synthesis.
//  * Gate-level equivalence is not here. It co-simulated the RTL against a
//    locally synthesised netlist; the platform runs its own synthesis and
//    exposes no netlist to this field.
// ============================================================================

// ============================================================================
//  INSTANCE ALIASES
//  ---------------------------------------------------------------------------
//  REGENERATE THESE AFTER EVERY "BLOCKS" EXPORT. The platform names instances
//  automatically (blk2116_47 and the like) and those names change whenever the
//  project is regenerated. `scripts/gen_ci_aliases.py <exported top.v>` prints
//  a replacement for this block.
//
//  The values below are the local-mirror names, so this file runs unmodified
//  against chipinventor/ci_top.v before it ever reaches the platform.
// ============================================================================
// >>> BEGIN GENERATED ALIASES
// Regenerated by scripts/gen_ci_aliases.py from the exported top.v.
// Platform instance names change on every export; re-run that script
// and replace this block whenever the project is regenerated.
`define DUT   dut
`define CTRL  `DUT.u_ctrl        // FSM state and the firmware-completion event
`define PC    `DUT.u_pc          // program counter
`define IR    `DUT.u_ir          // instruction register
`define RF    `DUT.u_rf          // the 32 general-purpose registers
`define DMEM  `DUT.u_dmem        // the data memory array
// <<< END GENERATED ALIASES

// Reaching a DMEM word. `top` has no data pins (Block Guide 2.2), so every
// memory check in this file goes through the array by hierarchical reference.
`define DMEM_WORD(idx) `DMEM.mem[idx]

module testbench;

// ---------------------------------------------------------------------------
// Expected values produced alongside the supplementary firmware image.
// Mirrored from firmware/ci_prog_expected.vh - scripts/run_ci.sh fails the run
// if the two ever disagree, so these cannot silently go stale.
//
// SUPP_BASE is where that program sits in the ROM. Word 0 belongs to the
// official validation firmware, which is position-dependent and cannot move,
// so this one was placed above it and EXP_JALR_LINK / EXP_AUIPC are relocated
// to match.
// ---------------------------------------------------------------------------
localparam [31:0] SUPP_BASE      = 32'h00400800;
localparam        NUM_SIG_TESTS  = 58;
localparam        SIG_BASE_WORDS = 'h100/4;
localparam [31:0] EXP_JALR_LINK  = 32'h00400F28;
localparam [31:0] EXP_AUIPC      = 32'h00405F3C;
localparam [31:0] EXP_IMEM_LOAD  = 32'hCAFEBABE;
localparam [31:0] EXP_DEP_SUM    = 32'd15;
localparam [31:0] EXP_DEP_CTR    = 32'd6;

// ---------------------------------------------------------------------------
// The official validation firmware (CCX_Malaysia_Edition_Firmware_Stage_2).
// 259 words at 0x00400000, vendored at firmware/validation_firmware.txt.
//
// It does not signal completion with ECALL or EBREAK - it falls into a
// one-instruction self-loop (`j .`) and leaves the verdict in x4. Both exit
// loops are listed so a failing run can be told apart from a hung one.
// ---------------------------------------------------------------------------
localparam [31:0] FW_PASS_LOOP = 32'h004003EC; // all_good:  li x4, 0  ; j .
localparam [31:0] FW_ERROR_PC  = 32'h004003F0; // _error:    li x4, -1 ; j .
localparam [31:0] FW_FAIL_LOOP = 32'h004003F4;
localparam [4:0]  FW_VERDICT_REG = 5'd4;       // x4 / tp
localparam [31:0] FW_PASS       = 32'h00000000;
localparam [31:0] FW_FAIL       = 32'hFFFFFFFF;
localparam        FW_CYCLE_CAP  = 20000;
localparam        FW_SETTLE     = 40;  // cycles the PC must hold in a self-loop

// What the firmware leaves in DMEM. These are architectural facts read off its
// own source, not observations of our run: .bss is at 0x10010000, test_ram is
// 16 bytes and dest_data the 12 bytes after it.
//   word 0  sw   0x12345678      word 4..6  the IMEM-to-DMEM copy loop
//   word 1  sh   0xAABB          (source_data lives in IMEM at 0x00400400)
//   word 2  sb   0xCC
localparam [31:0] FW_DM0 = 32'h12345678,
                  FW_DM1 = 32'h0000AABB,
                  FW_DM2 = 32'h000000CC,
                  FW_DM4 = 32'h11111111,
                  FW_DM5 = 32'h22222222,
                  FW_DM6 = 32'h33333333;

reg clk = 0;
reg rst = 1;

top dut (.clk_i(clk), .rst_i(rst));

always #5 clk = ~clk;

// ---- FSM states (control_unit's own encoding) ------------------------------
localparam [2:0] S_RESET     = 3'd0,
                 S_FETCH     = 3'd1,
                 S_DECODE    = 3'd2,
                 S_EXECUTE   = 3'd3,
                 S_MEMORY    = 3'd4,
                 S_WRITEBACK = 3'd5;

// ---- opcodes ---------------------------------------------------------------
localparam [6:0] OP_LUI     = 7'b0110111,
                 OP_AUIPC   = 7'b0010111,
                 OP_JAL     = 7'b1101111,
                 OP_JALR    = 7'b1100111,
                 OP_BRANCH  = 7'b1100011,
                 OP_LOAD    = 7'b0000011,
                 OP_STORE   = 7'b0100011,
                 OP_ALU_IMM = 7'b0010011,
                 OP_ALU_REG = 7'b0110011,
                 OP_SYSTEM  = 7'b1110011,
                 OP_FENCE   = 7'b0001111;

// ---- memory map (Block Guide Table 13) -------------------------------------
localparam [31:0] IMEM_BASE = 32'h0040_0000,
                  IMEM_LAST = 32'h007F_FFFF,
                  DMEM_BASE = 32'h1001_0000,
                  DMEM_LAST = 32'h1001_1FFF;

integer pass, fail;
integer fail_budget;
integer i, k, n, f0;

// ===========================================================================
//  REPORTING
// ===========================================================================
task pass_msg(input [8*96-1:0] label);
    begin
        pass = pass + 1;
        $display("[PASS] %0s", label);
    end
endtask

task fail_msg(input [8*96-1:0] label);
    begin
        fail = fail + 1;
        if (fail_budget > 0) begin
            fail_budget = fail_budget - 1;
            $display("[FAIL] %0s", label);
            if (fail_budget == 0)
                $display("[INFO] Failure print budget exhausted; further failures counted silently.");
        end
    end
endtask

// Counts a failure and prints it only while budget remains. Used inside the
// randomised sweeps, which would otherwise flood a cloud log viewer.
task note_fail(input [8*96-1:0] label);
    begin
        fail = fail + 1;
        if (fail_budget > 0) begin
            fail_budget = fail_budget - 1;
            $display("[FAIL] %0s", label);
        end
    end
endtask

// ===========================================================================
//  REFERENCE MODELS
//  Independent re-implementations of the specification, deliberately not
//  copied from the blocks they check. These replace the Python-generated
//  vector files the file-driven suite read from disk.
// ===========================================================================

// CRC-16/CCITT-FALSE: poly 0x1021, MSB-first, no reflection, no final XOR.
// Operand roles match the block: seed is rs1[15:0], data is rs2.
function [15:0] ref_crc;
    input [2:0]  f3;
    input [15:0] seed;
    input [31:0] data;
    reg   [15:0] c;
    reg          fb;
    integer      nbits, bi;
    begin
        c = seed;
        case (f3[1:0])
            2'b00:   nbits = 8;
            2'b01:   nbits = 16;
            2'b10:   nbits = 32;
            default: nbits = 0;   // unused encoding: seed passes through
        endcase
        for (bi = nbits - 1; bi >= 0; bi = bi - 1) begin
            fb = c[15] ^ data[bi];
            c  = {c[14:0], 1'b0} ^ (fb ? 16'h1021 : 16'h0000);
        end
        ref_crc = c;
    end
endfunction

function [31:0] ref_imm;
    input [31:0] ins;
    begin
        case (ins[6:0])
            OP_LOAD, OP_ALU_IMM, OP_JALR:
                ref_imm = {{20{ins[31]}}, ins[31:20]};
            OP_STORE:
                ref_imm = {{20{ins[31]}}, ins[31:25], ins[11:7]};
            OP_BRANCH:
                ref_imm = {{19{ins[31]}}, ins[31], ins[7], ins[30:25], ins[11:8], 1'b0};
            OP_LUI, OP_AUIPC:
                ref_imm = {ins[31:12], 12'b0};
            OP_JAL:
                ref_imm = {{11{ins[31]}}, ins[31], ins[19:12], ins[20], ins[30:21], 1'b0};
            default:
                ref_imm = 32'b0;
        endcase
    end
endfunction

function ref_branch;
    input [2:0]  f3;
    input [31:0] a, b;
    begin
        case (f3)
            3'b000:  ref_branch = (a == b);
            3'b001:  ref_branch = (a != b);
            3'b100:  ref_branch = ($signed(a) <  $signed(b));
            3'b101:  ref_branch = ($signed(a) >= $signed(b));
            3'b110:  ref_branch = (a <  b);
            3'b111:  ref_branch = (a >= b);
            default: ref_branch = 1'b0;   // 010/011 are not branch encodings
        endcase
    end
endfunction

// Load extraction and extension. op_size is funct3: [1:0]=width, [2]=unsigned.
// Misaligned half/word accesses return a deterministic 0, never x.
function [31:0] ref_load;
    input [2:0]  f3;
    input [1:0]  off;
    input [31:0] word;
    reg   [7:0]  bb;
    reg   [15:0] hh;
    begin
        case (off)
            2'b00:   bb = word[7:0];
            2'b01:   bb = word[15:8];
            2'b10:   bb = word[23:16];
            default: bb = word[31:24];
        endcase
        case (off)
            2'b00:   hh = word[15:0];
            2'b10:   hh = word[31:16];
            default: hh = 16'b0;
        endcase
        case (f3[1:0])
            2'b00:   ref_load = f3[2] ? {24'b0, bb} : {{24{bb[7]}},  bb};
            2'b01:   ref_load = (off == 2'b00 || off == 2'b10)
                                ? (f3[2] ? {16'b0, hh} : {{16{hh[15]}}, hh})
                                : 32'b0;
            2'b10:   ref_load = (off == 2'b00) ? word : 32'b0;
            default: ref_load = 32'b0;
        endcase
    end
endfunction

function [3:0] ref_strobe;
    input [2:0] f3;
    input [1:0] off;
    input       valid_store;
    begin
        if (!valid_store) ref_strobe = 4'b0000;
        else case (f3[1:0])
            2'b00:   ref_strobe = 4'b0001 << off;
            2'b01:   ref_strobe = (off == 2'b00) ? 4'b0011 :
                                  (off == 2'b10) ? 4'b1100 : 4'b0000;
            2'b10:   ref_strobe = (off == 2'b00) ? 4'b1111 : 4'b0000;
            default: ref_strobe = 4'b0000;
        endcase
    end
endfunction

function [31:0] ref_store_data;
    input [2:0]  f3;
    input [1:0]  off;
    input [31:0] rs2;
    input        valid_store;
    begin
        if (!valid_store) ref_store_data = 32'b0;
        else case (f3[1:0])
            2'b00:   ref_store_data = {24'b0, rs2[7:0]} << (8*off);
            2'b01:   ref_store_data = (off == 2'b00) ? {16'b0, rs2[15:0]} :
                                      (off == 2'b10) ? {rs2[15:0], 16'b0} : 32'b0;
            2'b10:   ref_store_data = (off == 2'b00) ? rs2 : 32'b0;
            default: ref_store_data = 32'b0;
        endcase
    end
endfunction

// ===========================================================================
//  SUITE 0 - UNIT DUTs
//  Instantiated directly by module name. The generated project file defines
//  every block alongside `top`, so this is legal there exactly as it is here.
// ===========================================================================
reg  [31:0] u_a, u_b;
reg  [3:0]  u_aluop;
reg  [2:0]  u_f3;
wire [31:0] u_aluq;
alu U_ALU (.a(u_a), .b(u_b), .alu_op(u_aluop), .result(u_aluq));

wire u_taken;
branch_comparator U_BC (
    .rs1_data(u_a), .rs2_data(u_b), .funct3(u_f3), .branch_taken(u_taken));

reg  [31:0] u_ins;
wire [31:0] u_immq;
immediate_generator U_IMM (.ir(u_ins), .imm(u_immq));

wire [31:0] u_mulq;
multiplier U_MUL (
    .rs1_data(u_a), .rs2_data(u_b), .funct3(u_f3), .result(u_mulq));

wire [31:0] u_crcq;
crc_unit U_CRC (
    .rs1_data(u_a), .rs2_data(u_b), .funct3(u_f3), .result(u_crcq));

reg  [31:0] l_addr, l_rs2, l_memrd;
reg         l_store;
wire [31:0] l_load, l_sdata;
wire [3:0]  l_bw;
lsu U_LSU (
    .alu_result(l_addr), .rs2_data(l_rs2), .op_size(u_f3), .is_valid_store(l_store),
    .mem_data_o(l_memrd), .core_data_i(l_load),
    .byte_write_o(l_bw), .store_data_o(l_sdata));

reg  [31:0] d_addr, d_imemrd, d_dmemrd;
reg         d_we, d_oe;
reg  [3:0]  d_bw;
wire        d_ioe, d_dwe, d_doe;
wire [3:0]  d_dbw;
wire [31:0] d_data;
address_decoder U_DEC (
    .address_i(d_addr), .we_i(d_we), .oe_i(d_oe), .bw_i(d_bw),
    .imem_rdata(d_imemrd), .dmem_rdata(d_dmemrd),
    .imem_oe_o(d_ioe), .dmem_we_o(d_dwe), .dmem_oe_o(d_doe),
    .dmem_bw_o(d_dbw), .data_o(d_data));

reg         r_rst, r_we;
reg  [4:0]  r_a1, r_a2, r_ad;
reg  [31:0] r_wd;
wire [31:0] r_d1, r_d2;
register_file U_RF (
    .clk_i(clk), .rst_i(r_rst),
    .rs1_addr(r_a1), .rs2_addr(r_a2), .rd_addr(r_ad),
    .rd_data(r_wd), .reg_write(r_we), .rs1_data(r_d1), .rs2_data(r_d2));

reg  [31:0] p_addr;
reg         p_oe;
wire [31:0] p_data;
imem U_IMEM (.address_i(p_addr), .oe_i(p_oe), .data_o(p_data));

// A small standalone DMEM, so the "inside the 8kB window but past the
// instantiated array" checks have a reachable out-of-range address.
localparam MWORDS = 32;
reg  [31:0] m_addr, m_wd;
reg         m_we, m_oe;
reg  [3:0]  m_bw;
wire [31:0] m_rd;
dmem #(.DMEM_WORDS(MWORDS)) U_DMEM (
    .clk_i(clk), .rst_i(1'b0), .address_i(m_addr), .we_i(m_we), .oe_i(m_oe),
    .bw_i(m_bw), .data_i(m_wd), .data_o(m_rd));

reg         g_s;
wire [31:0] g_muxz;
mux2_32 U_MUX2 (.a(u_a), .b(u_b), .s(g_s), .z(g_muxz));

reg  [31:0] g_alu, g_mul, g_crc, g_load, g_pc4;
reg  [2:0]  g_wbsel;
wire [31:0] g_wbz;
wb_mux_32 U_WBMUX (
    .alu_result(g_alu), .mult_result(g_mul), .crc_result(g_crc),
    .lsu_load_data(g_load), .pc_plus_4(g_pc4),
    .wb_src_sel(g_wbsel), .wb_data(g_wbz));

wire [4:0] g_rs1, g_rs2, g_rd;
ir_fields U_IRF (.ir(u_ins), .rs1_addr(g_rs1), .rs2_addr(g_rs2), .rd_addr(g_rd));

// ===========================================================================
//  SUITE 1 - standalone control unit
// ===========================================================================
reg         c_rst, c_bt;
reg  [31:0] c_ir;
wire [2:0]  c_state, c_wbsel, c_opsize;
wire [3:0]  c_aluop;
wire        c_asel, c_bsel, c_addrsel, c_pcsel;
wire        c_pcwrite, c_regwrite, c_we, c_oe, c_irwrite, c_sysevent, c_store;
control_unit U_CTRL (
    .clk_i(clk), .rst_i(c_rst), .ir(c_ir), .branch_taken(c_bt),
    .state_o(c_state),
    .alu_src_a_sel(c_asel), .alu_src_b_sel(c_bsel), .alu_op(c_aluop),
    .addr_src_sel(c_addrsel), .wb_src_sel(c_wbsel), .pc_src_sel(c_pcsel),
    .pc_write(c_pcwrite), .reg_write(c_regwrite), .we_o(c_we), .oe_o(c_oe),
    .ir_write(c_irwrite), .sys_event_o(c_sysevent),
    .is_valid_store(c_store), .op_size(c_opsize));

// ===========================================================================
//  SUITE 0.1 - ALU
// ===========================================================================
task check_alu(input [31:0] exp, input [8*64-1:0] name);
    begin
        if (u_aluq === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        a=%h b=%h op=%h -> got=%h exp=%h", u_a, u_b, u_aluop, u_aluq, exp);
        end
    end
endtask

task suite_alu;
    begin
        u_a=32'h1111_1111; u_b=32'h789A_BCDE; u_aluop=4'h0; #1; check_alu(u_b, "ALU PASS_B");

        u_a=32'd10; u_b=32'd20; u_aluop=4'h1; #1; check_alu(32'd30, "ALU ADD basic");
        u_a=32'hFFFF_FFFF; u_b=32'd1; u_aluop=4'h1; #1; check_alu(32'd0, "ALU ADD overflow wrap");

        u_a=32'd5; u_b=32'd8; u_aluop=4'h2; #1; check_alu(-32'd3, "ALU SUB negative result");
        u_a=32'h8000_0000; u_b=32'h1; u_aluop=4'h2; #1; check_alu(32'h7FFF_FFFF, "ALU SUB INT_MIN-1 wrap");

        u_a=32'hFF00_FF00; u_b=32'h0FF0_0FF0; u_aluop=4'h3; #1; check_alu(32'h0F00_0F00, "ALU AND");
        u_a=32'hFF00_FF00; u_b=32'h00FF_00FF; u_aluop=4'h4; #1; check_alu(32'hFFFF_FFFF, "ALU OR");
        u_a=32'hAAAA_AAAA; u_b=32'hFFFF_FFFF; u_aluop=4'h5; #1; check_alu(32'h5555_5555, "ALU XOR");

        u_a=32'h0000_0001; u_b=32'd31; u_aluop=4'h6; #1; check_alu(32'h8000_0000, "ALU SLL by 31");
        u_a=32'h0000_0001; u_b=32'd32; u_aluop=4'h6; #1; check_alu(32'h0000_0001, "ALU SLL masked shamt 32->0");
        u_a=32'h8000_0000; u_b=32'd4;  u_aluop=4'h7; #1; check_alu(32'h0800_0000, "ALU SRL logical MSB=1");
        u_a=32'h8000_0000; u_b=32'd4;  u_aluop=4'h8; #1; check_alu(32'hF800_0000, "ALU SRA sign-extends");
        u_a=32'h7FFF_FFFF; u_b=32'd31; u_aluop=4'h8; #1; check_alu(32'h0000_0000, "ALU SRA positive to 0");
        u_a=32'hFFFF_FFFF; u_b=32'd31; u_aluop=4'h8; #1; check_alu(32'hFFFF_FFFF, "ALU SRA -1 stays -1");

        u_a=32'h8000_0000; u_b=32'h7FFF_FFFF; u_aluop=4'h9; #1; check_alu(32'd1, "ALU SLT INT_MIN<INT_MAX");
        u_a=32'h8000_0000; u_b=32'h7FFF_FFFF; u_aluop=4'hA; #1; check_alu(32'd0, "ALU SLTU big unsigned not less");
        u_a=32'd0; u_b=32'd0; u_aluop=4'h9; #1; check_alu(32'd0, "ALU SLT equal -> 0");
        u_a=32'hFFFF_FFFF; u_b=32'd0; u_aluop=4'h9; #1; check_alu(32'd1, "ALU SLT -1 < 0 signed");
        u_a=32'hFFFF_FFFF; u_b=32'd0; u_aluop=4'hA; #1; check_alu(32'd0, "ALU SLTU 0xFFFFFFFF not < 0");

        u_a=32'hDEAD_BEEF; u_b=32'hCAFE_BABE; u_aluop=4'hF; #1; check_alu(32'd0, "ALU reserved opcode -> defined 0");

        u_a=32'd0; u_b=32'd0; u_aluop=4'h1; #1; check_alu(32'd0, "ALU ADD 0+0");
        u_a=32'hFFFF_FFFF; u_b=32'hFFFF_FFFF; u_aluop=4'h1; #1; check_alu(32'hFFFF_FFFE, "ALU ADD -1 + -1 wraps");
        u_a=32'd5; u_b=32'd5; u_aluop=4'h2; #1; check_alu(32'd0, "ALU SUB equal -> 0");
        u_a=32'd1; u_b=32'd0; u_aluop=4'h6; #1; check_alu(32'd1, "ALU SLL by 0 unchanged");
        u_a=32'h8000_0000; u_b=32'd0; u_aluop=4'h7; #1; check_alu(32'h8000_0000, "ALU SRL by 0 unchanged");
        u_a=32'h8000_0000; u_b=32'd0; u_aluop=4'h8; #1; check_alu(32'h8000_0000, "ALU SRA by 0 unchanged");
        u_a=32'd5; u_b=32'd5; u_aluop=4'h9; #1; check_alu(32'd0, "ALU SLT equal -> 0 (repeat)");
        u_a=32'd5; u_b=32'd5; u_aluop=4'hA; #1; check_alu(32'd0, "ALU SLTU equal -> 0");

        // Randomised sweep across all 11 defined operations.
        for (n = 0; n < 100; n = n + 1) begin
            u_a = $random; u_b = $random;
            u_aluop=4'h0; #1; check_alu(u_b, "ALU PASS_B random");
            u_aluop=4'h1; #1; check_alu(u_a + u_b, "ALU ADD random");
            u_aluop=4'h2; #1; check_alu(u_a - u_b, "ALU SUB random");
            u_aluop=4'h3; #1; check_alu(u_a & u_b, "ALU AND random");
            u_aluop=4'h4; #1; check_alu(u_a | u_b, "ALU OR random");
            u_aluop=4'h5; #1; check_alu(u_a ^ u_b, "ALU XOR random");
            u_aluop=4'h6; #1; check_alu(u_a << u_b[4:0], "ALU SLL random");
            u_aluop=4'h7; #1; check_alu(u_a >> u_b[4:0], "ALU SRL random");
            u_aluop=4'h8; #1; check_alu($signed(u_a) >>> u_b[4:0], "ALU SRA random");
            u_aluop=4'h9; #1; check_alu(($signed(u_a) < $signed(u_b)) ? 32'd1 : 32'd0, "ALU SLT random");
            u_aluop=4'hA; #1; check_alu((u_a < u_b) ? 32'd1 : 32'd0, "ALU SLTU random");
        end
        $display("  [S0.1] ALU: 11 ops, mux-free corners, 1100 randomised");
    end
endtask

// ===========================================================================
//  SUITE 0.2 - branch comparator
// ===========================================================================
task check_bc(input exp, input [8*64-1:0] name);
    begin
        if (u_taken === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        rs1=%h rs2=%h f3=%b -> got=%b exp=%b", u_a, u_b, u_f3, u_taken, exp);
        end
    end
endtask

task suite_bc;
    begin
        u_a=32'd5; u_b=32'd5; u_f3=3'b000; #1; check_bc(1'b1, "BEQ equal");
        u_a=32'd5; u_b=32'd6; u_f3=3'b000; #1; check_bc(1'b0, "BEQ not-equal");
        u_a=32'd5; u_b=32'd6; u_f3=3'b001; #1; check_bc(1'b1, "BNE differ");
        u_a=32'd5; u_b=32'd5; u_f3=3'b001; #1; check_bc(1'b0, "BNE equal -> not taken");

        u_a=32'h8000_0000; u_b=32'h7FFF_FFFF; u_f3=3'b100; #1; check_bc(1'b1, "BLT signed MIN<MAX");
        u_a=32'h7FFF_FFFF; u_b=32'h8000_0000; u_f3=3'b100; #1; check_bc(1'b0, "BLT signed MAX<MIN false");
        u_a=32'h8000_0000; u_b=32'h7FFF_FFFF; u_f3=3'b101; #1; check_bc(1'b0, "BGE signed MIN>=MAX false");
        u_a=32'h7FFF_FFFF; u_b=32'h8000_0000; u_f3=3'b101; #1; check_bc(1'b1, "BGE signed MAX>=MIN true");

        u_a=32'h8000_0000; u_b=32'h7FFF_FFFF; u_f3=3'b110; #1; check_bc(1'b0, "BLTU big unsigned not less");
        u_a=32'h7FFF_FFFF; u_b=32'h8000_0000; u_f3=3'b110; #1; check_bc(1'b1, "BLTU small < big unsigned");
        u_a=32'h8000_0000; u_b=32'h7FFF_FFFF; u_f3=3'b111; #1; check_bc(1'b1, "BGEU big>=small true");
        u_a=32'h7FFF_FFFF; u_b=32'h8000_0000; u_f3=3'b111; #1; check_bc(1'b0, "BGEU small>=big false");

        u_a=32'hFFFF_FFFF; u_b=32'h0000_0000; u_f3=3'b010; #1; check_bc(1'b0, "reserved funct3 010 -> not taken");
        u_a=32'hFFFF_FFFF; u_b=32'h0000_0000; u_f3=3'b011; #1; check_bc(1'b0, "reserved funct3 011 -> not taken");

        u_a=32'd7; u_b=32'd7; u_f3=3'b100; #1; check_bc(1'b0, "BLT equal -> not taken (strict)");
        u_a=32'd7; u_b=32'd7; u_f3=3'b101; #1; check_bc(1'b1, "BGE equal -> taken");
        u_a=32'd7; u_b=32'd7; u_f3=3'b110; #1; check_bc(1'b0, "BLTU equal -> not taken");
        u_a=32'd7; u_b=32'd7; u_f3=3'b111; #1; check_bc(1'b1, "BGEU equal -> taken");
        u_a=32'd0; u_b=32'd0; u_f3=3'b000; #1; check_bc(1'b1, "BEQ 0==0");
        u_a=32'd0; u_b=32'd0; u_f3=3'b001; #1; check_bc(1'b0, "BNE 0==0 -> not taken");
        u_a=32'd0; u_b=32'd0; u_f3=3'b100; #1; check_bc(1'b0, "BLT 0<0 -> not taken");
        u_a=32'd0; u_b=32'd0; u_f3=3'b101; #1; check_bc(1'b1, "BGE 0>=0");
        u_a=32'd0; u_b=32'd0; u_f3=3'b110; #1; check_bc(1'b0, "BLTU 0<0u -> not taken");
        u_a=32'd0; u_b=32'd0; u_f3=3'b111; #1; check_bc(1'b1, "BGEU 0>=0u");

        // Randomised across all 8 funct3 values, including the two reserved.
        for (n = 0; n < 1500; n = n + 1) begin
            u_a = $random; u_b = $random; u_f3 = n % 8;
            // Bias a third of the cases to equal operands, which is where the
            // strict/non-strict boundary lives.
            if (n % 3 == 0) u_b = u_a;
            #1; check_bc(ref_branch(u_f3, u_a, u_b), "BC randomised");
        end
        $display("  [S0.2] Branch comparator: 6 conditions, reserved funct3, 1500 randomised");
    end
endtask

// ===========================================================================
//  SUITE 0.3 - immediate generator (replaces the golden vector file)
// ===========================================================================
task suite_imm;
    begin
        f0 = 0;

        // Directed: sign-extension boundaries in every format.
        u_ins = {12'h800, 5'd0, 3'b000, 5'd0, OP_ALU_IMM}; #1;   // I-type, most negative
        if (u_immq !== 32'hFFFF_F800) begin f0=f0+1; note_fail("IMM I-type most negative"); end
        u_ins = {12'h7FF, 5'd0, 3'b000, 5'd0, OP_ALU_IMM}; #1;   // I-type, most positive
        if (u_immq !== 32'h0000_07FF) begin f0=f0+1; note_fail("IMM I-type most positive"); end
        u_ins = {20'hFFFFF, 5'd0, OP_LUI}; #1;
        if (u_immq !== 32'hFFFF_F000) begin f0=f0+1; note_fail("IMM U-type all ones"); end
        u_ins = {20'h00000, 5'd0, OP_AUIPC}; #1;
        if (u_immq !== 32'h0000_0000) begin f0=f0+1; note_fail("IMM U-type zero"); end

        // R-type / SYSTEM / FENCE are don't-care but must be defined, not x.
        u_ins = 32'h0000_0033; #1;
        if (u_immq !== 32'b0) begin f0=f0+1; note_fail("IMM R-type must be defined 0"); end
        u_ins = 32'h0000_0073; #1;
        if (u_immq !== 32'b0) begin f0=f0+1; note_fail("IMM SYSTEM must be defined 0"); end
        u_ins = 32'h0FF0_000F; #1;
        if (u_immq !== 32'b0) begin f0=f0+1; note_fail("IMM FENCE must be defined 0"); end

        // Randomised across every format. The bit-scrambling in the B and J
        // encodings is exactly the kind of thing a hand-written vector set
        // under-samples, so this sweeps far wider than the 33 golden vectors
        // the file-driven suite used.
        for (n = 0; n < 2000; n = n + 1) begin
            u_ins = $random;
            case (n % 8)
                0: u_ins[6:0] = OP_LUI;
                1: u_ins[6:0] = OP_AUIPC;
                2: u_ins[6:0] = OP_JAL;
                3: u_ins[6:0] = OP_BRANCH;
                4: u_ins[6:0] = OP_STORE;
                5: u_ins[6:0] = OP_ALU_IMM;
                6: u_ins[6:0] = OP_LOAD;
                7: u_ins[6:0] = OP_JALR;
            endcase
            #1;
            if (u_immq === ref_imm(u_ins)) pass = pass + 1;
            else begin
                f0 = f0 + 1;
                note_fail("IMM randomised");
                if (fail_budget >= 0)
                    $display("        ir=%h -> got=%h exp=%h", u_ins, u_immq, ref_imm(u_ins));
            end
        end

        if (f0 == 0) pass_msg("S0.3 Immediate generator: I/S/B/U/J formats, 2000 randomised");
        $display("  [S0.3] Immediate generator: directed boundaries + 2000 randomised");
    end
endtask

// ===========================================================================
//  SUITE 0.4 - multiplier
//  The expected value comes from a 64-bit software model, deliberately not
//  from the block's own a_signed/b_signed/sel_upper expressions.
// ===========================================================================
reg signed [63:0] mm_as, mm_bs;
reg        [63:0] mm_au, mm_bu, mm_ss, mm_uu, mm_su;
reg        [31:0] mm_exp;

task mult_expected(input [31:0] r1, input [31:0] r2, input [2:0] fn3);
    begin
        mm_as = $signed(r1); mm_bs = $signed(r2);
        mm_au = {32'b0, r1}; mm_bu = {32'b0, r2};
        mm_ss = mm_as * mm_bs;
        mm_uu = mm_au * mm_bu;
        mm_su = mm_as * mm_bu;
        case (fn3)
            3'b000:  mm_exp = mm_ss[31:0];
            3'b001:  mm_exp = mm_ss[63:32];
            3'b010:  mm_exp = mm_su[63:32];
            3'b011:  mm_exp = mm_uu[63:32];
            default: mm_exp = 32'b0;
        endcase
    end
endtask

task check_mult(input [8*64-1:0] name);
    begin
        mult_expected(u_a, u_b, u_f3);
        #1;
        if (u_mulq === mm_exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        rs1=%h rs2=%h f3=%b -> got=%h exp=%h", u_a, u_b, u_f3, u_mulq, mm_exp);
        end
    end
endtask

reg [31:0] corner [0:6];
integer c1, c2;

task suite_mult;
    reg [2:0] fn3;
    reg exp_as, exp_bs, exp_up, got_as, got_bs, got_up;
    begin
        corner[0] = 32'h0000_0000;
        corner[1] = 32'h0000_0001;
        corner[2] = 32'hFFFF_FFFF; // -1
        corner[3] = 32'h8000_0000; // INT_MIN
        corner[4] = 32'h7FFF_FFFF; // INT_MAX
        corner[5] = 32'h0000_0002;
        corner[6] = 32'hFFFF_FFFE; // -2

        for (c1 = 0; c1 < 7; c1 = c1 + 1) begin
            for (c2 = 0; c2 < 7; c2 = c2 + 1) begin
                u_a = corner[c1]; u_b = corner[c2];
                u_f3 = 3'b000; check_mult("MUL corner");
                u_f3 = 3'b001; check_mult("MULH corner");
                u_f3 = 3'b010; check_mult("MULHSU corner");
                u_f3 = 3'b011; check_mult("MULHU corner");
            end
        end

        // INT_MIN * -1: must wrap, not trap.
        u_a = 32'h8000_0000; u_b = 32'hFFFF_FFFF;
        u_f3 = 3'b000; check_mult("MUL INT_MIN*-1 wraps");
        u_f3 = 3'b001; check_mult("MULH INT_MIN*-1");

        for (n = 0; n < 500; n = n + 1) begin
            u_a = $random; u_b = $random;
            u_f3 = 3'b000; check_mult("MUL randomised");
            u_f3 = 3'b001; check_mult("MULH randomised");
            u_f3 = 3'b010; check_mult("MULHSU randomised");
            u_f3 = 3'b011; check_mult("MULHU randomised");
        end

        // Brute-force check of the operand-signedness formulas themselves
        // against the Table 10 truth table. funct3[0] alone would be wrong for
        // MULHSU, which is exactly why the design uses funct3[1]|funct3[0].
        for (fn3 = 0; fn3 < 4; fn3 = fn3 + 1) begin
            case (fn3)
                3'b000: begin exp_as=1; exp_bs=1; exp_up=0; end // MUL
                3'b001: begin exp_as=1; exp_bs=1; exp_up=1; end // MULH
                3'b010: begin exp_as=1; exp_bs=0; exp_up=1; end // MULHSU
                default:begin exp_as=0; exp_bs=0; exp_up=1; end // MULHU
            endcase
            got_as = ~(fn3[1] & fn3[0]);
            got_bs = ~fn3[1];
            got_up = fn3[1] | fn3[0];
            if (got_as===exp_as && got_bs===exp_bs && got_up===exp_up) pass = pass + 1;
            else begin
                note_fail("MULT truth table");
                $display("        funct3=%b a_signed=%b(exp %b) b_signed=%b(exp %b) sel_upper=%b(exp %b)",
                         fn3, got_as, exp_as, got_bs, exp_bs, got_up, exp_up);
            end
        end
        $display("  [S0.4] Multiplier: 4 ops, 49 corner pairs, 2000 randomised, truth table");
    end
endtask

// ===========================================================================
//  SUITE 0.5 - LSU
// ===========================================================================
task check_load(input [31:0] exp, input [8*64-1:0] name);
    begin
        if (l_load === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0) $display("        got=%h exp=%h", l_load, exp);
        end
    end
endtask

task check_store(input [3:0] exp_bw, input [31:0] exp_data, input [8*64-1:0] name);
    begin
        if (l_bw === exp_bw && l_sdata === exp_data) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        got bw=%b data=%h  exp bw=%b data=%h", l_bw, l_sdata, exp_bw, exp_data);
        end
    end
endtask

task suite_lsu;
    begin
        l_store = 0;
        // Block Guide 3.3.1 worked example: DMEM word 0xF4F3F2F1.
        l_memrd = 32'hF4F3_F2F1;
        l_addr=32'h1001_0000; u_f3=3'b100; #1; check_load(32'h0000_00F1, "LBU @0");
        l_addr=32'h1001_0000; u_f3=3'b000; #1; check_load(32'hFFFF_FFF1, "LB  @0");
        l_addr=32'h1001_0000; u_f3=3'b101; #1; check_load(32'h0000_F2F1, "LHU @0");
        l_addr=32'h1001_0000; u_f3=3'b001; #1; check_load(32'hFFFF_F2F1, "LH  @0");
        l_addr=32'h1001_0000; u_f3=3'b010; #1; check_load(32'hF4F3_F2F1, "LW  @0");
        l_addr=32'h1001_0002; u_f3=3'b100; #1; check_load(32'h0000_00F3, "LBU @2");
        l_addr=32'h1001_0002; u_f3=3'b000; #1; check_load(32'hFFFF_FFF3, "LB  @2");
        l_addr=32'h1001_0001; u_f3=3'b100; #1; check_load(32'h0000_00F2, "LBU @1");
        l_addr=32'h1001_0003; u_f3=3'b100; #1; check_load(32'h0000_00F4, "LBU @3");
        l_addr=32'h1001_0003; u_f3=3'b000; #1; check_load(32'hFFFF_FFF4, "LB  @3 sign=1");
        l_addr=32'h1001_0002; u_f3=3'b101; #1; check_load(32'h0000_F4F3, "LHU @2");
        l_addr=32'h1001_0002; u_f3=3'b001; #1; check_load(32'hFFFF_F4F3, "LH  @2 sign=1");

        // Misaligned half/word: deterministic 0, never x or partial garbage.
        l_addr=32'h1001_0001; u_f3=3'b001; #1; check_load(32'b0, "LH misaligned off1 -> 0");
        l_addr=32'h1001_0003; u_f3=3'b001; #1; check_load(32'b0, "LH misaligned off3 -> 0");
        l_addr=32'h1001_0001; u_f3=3'b010; #1; check_load(32'b0, "LW misaligned off1 -> 0");
        l_addr=32'h1001_0002; u_f3=3'b010; #1; check_load(32'b0, "LW misaligned off2 -> 0");

        // Block Guide 3.3.2 worked example: store 0x12 to ...0002.
        l_store = 1;
        l_addr=32'h1001_0002; u_f3=3'b000; l_rs2=32'h0000_0012;
        #1; check_store(4'b0100, 32'h0012_0000, "SB @2 (Block Guide example)");

        l_rs2 = 32'h0000_00AB;
        l_addr=32'h1001_0000; u_f3=3'b000; #1; check_store(4'b0001, 32'h0000_00AB, "SB @0");
        l_addr=32'h1001_0001; u_f3=3'b000; #1; check_store(4'b0010, 32'h0000_AB00, "SB @1");
        l_addr=32'h1001_0003; u_f3=3'b000; #1; check_store(4'b1000, 32'hAB00_0000, "SB @3");

        l_rs2 = 32'h0000_ABCD;
        l_addr=32'h1001_0000; u_f3=3'b001; #1; check_store(4'b0011, 32'h0000_ABCD, "SH @0");
        l_addr=32'h1001_0002; u_f3=3'b001; #1; check_store(4'b1100, 32'hABCD_0000, "SH @2");
        l_addr=32'h1001_0001; u_f3=3'b001; #1; check_store(4'b0000, 32'b0, "SH misaligned -> no write");

        l_rs2 = 32'hCAFE_BABE;
        l_addr=32'h1001_0000; u_f3=3'b010; #1; check_store(4'b1111, 32'hCAFE_BABE, "SW @0");
        l_addr=32'h1001_0001; u_f3=3'b010; #1; check_store(4'b0000, 32'b0, "SW misaligned -> no write");

        // is_valid_store gating: a perfectly aligned access must still produce
        // bw=0000 when the current instruction is not a store.
        l_store = 0;
        l_addr=32'h1001_0000; u_f3=3'b000; l_rs2=32'hFF; #1;
        check_store(4'b0000, 32'b0, "is_valid_store=0 forces bw=0000");

        // Randomised across every funct3 and byte offset, both paths.
        for (n = 0; n < 1500; n = n + 1) begin
            l_addr  = $random;
            l_rs2   = $random;
            l_memrd = $random;
            u_f3    = n % 8;
            l_store = n[3];
            #1;
            if (l_load === ref_load(u_f3, l_addr[1:0], l_memrd)) pass = pass + 1;
            else begin
                note_fail("LSU load randomised");
                if (fail_budget >= 0)
                    $display("        f3=%b off=%b got=%h exp=%h",
                             u_f3, l_addr[1:0], l_load, ref_load(u_f3, l_addr[1:0], l_memrd));
            end
            if (l_bw === ref_strobe(u_f3, l_addr[1:0], l_store) &&
                l_sdata === ref_store_data(u_f3, l_addr[1:0], l_rs2, l_store)) pass = pass + 1;
            else begin
                note_fail("LSU store randomised");
                if (fail_budget >= 0)
                    $display("        f3=%b off=%b store=%b got bw=%b data=%h exp bw=%b data=%h",
                             u_f3, l_addr[1:0], l_store, l_bw, l_sdata,
                             ref_strobe(u_f3, l_addr[1:0], l_store),
                             ref_store_data(u_f3, l_addr[1:0], l_rs2, l_store));
            end
        end
        $display("  [S0.5] LSU: 8 funct3 x 4 offsets, both paths, 3000 randomised checks");
    end
endtask

// ===========================================================================
//  SUITE 0.6 - address decoder
// ===========================================================================
task check_dec(input exp_ioe, input exp_dwe, input exp_doe, input [3:0] exp_bw,
               input [31:0] exp_data, input [8*72-1:0] name);
    begin
        if (d_ioe===exp_ioe && d_dwe===exp_dwe && d_doe===exp_doe &&
            d_dbw===exp_bw && d_data===exp_data) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        imem_oe=%b(%b) dmem_we=%b(%b) dmem_oe=%b(%b) bw=%b(%b) data=%h(%h)",
                    d_ioe, exp_ioe, d_dwe, exp_dwe, d_doe, exp_doe, d_dbw, exp_bw, d_data, exp_data);
        end
    end
endtask

task suite_dec;
    begin
        d_imemrd = 32'hAAAA_AAAA; d_dmemrd = 32'hBBBB_BBBB;

        d_we=0; d_oe=1; d_bw=4'b0000;
        d_addr = IMEM_BASE;     #1; check_dec(1,0,0,4'b0000, 32'hAAAA_AAAA, "IMEM base");
        d_addr = IMEM_LAST;     #1; check_dec(1,0,0,4'b0000, 32'hAAAA_AAAA, "IMEM last byte");
        d_addr = IMEM_BASE - 1; #1; check_dec(0,0,0,4'b0000, 32'b0, "just below IMEM base -> unmapped");
        d_addr = IMEM_LAST + 1; #1; check_dec(0,0,0,4'b0000, 32'b0, "just above IMEM last -> unmapped");

        d_addr = DMEM_BASE;     #1; check_dec(0,0,1,4'b0000, 32'hBBBB_BBBB, "DMEM base");
        d_addr = DMEM_LAST;     #1; check_dec(0,0,1,4'b0000, 32'hBBBB_BBBB, "DMEM last byte");
        d_addr = DMEM_BASE - 1; #1; check_dec(0,0,0,4'b0000, 32'b0, "just below DMEM base -> unmapped");
        d_addr = DMEM_LAST + 1; #1; check_dec(0,0,0,4'b0000, 32'b0, "just above DMEM last -> unmapped");

        d_we=1; d_oe=0; d_bw=4'b1111;
        d_addr = 32'h1001_0010; #1; check_dec(0,1,0,4'b1111, 32'hBBBB_BBBB, "DMEM write in range");

        // An out-of-range store must assert exactly zero write strobes. A
        // decoder missing the explicit dmem_sel qualifier would still raise
        // dmem_we here and silently corrupt whatever word its own low-bit
        // decode landed on.
        d_addr = 32'hDEAD_0000; #1;
        check_dec(0,0,0,4'b0000, 32'b0, "out-of-range store asserts no dmem_we/bw");
        d_addr = 32'h0000_0000; #1;
        check_dec(0,0,0,4'b0000, 32'b0, "store at address 0 asserts no dmem_we/bw");

        d_we=0; d_oe=1; d_bw=4'b0000;
        d_addr = 32'hFFFF_FFFF; #1;
        check_dec(0,0,0,4'b0000, 32'b0, "out-of-range read -> 0, no oe asserted");
        $display("  [S0.6] Address decoder: window boundaries, WE gating, aliasing prevention");
    end
endtask

// ===========================================================================
//  SUITE 0.7 - register file
// ===========================================================================
task check_rf(input [31:0] got, input [31:0] exp, input [8*64-1:0] name);
    begin
        if (got === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0) $display("        got=%h exp=%h", got, exp);
        end
    end
endtask

task suite_rf;
    begin
        r_rst = 1; r_we = 0; r_ad = 0; r_wd = 0; r_a1 = 0; r_a2 = 0;
        @(posedge clk); @(posedge clk); #1;
        r_rst = 0;

        // x0 must read 0 even after a write to it is attempted.
        r_ad = 5'd0; r_wd = 32'hDEAD_BEEF; r_we = 1;
        @(posedge clk); #1;
        r_a1 = 5'd0; #1; check_rf(r_d1, 32'b0, "x0 write-guard still reads 0");
        r_we = 0;

        r_ad = 5'd5; r_wd = 32'h1234_5678; r_we = 1;
        @(posedge clk); #1;
        r_we = 0;
        r_a1 = 5'd5; r_a2 = 5'd5; #1;
        check_rf(r_d1, 32'h1234_5678, "x5 round-trip rs1 port");
        check_rf(r_d2, 32'h1234_5678, "x5 round-trip rs2 port");

        for (i = 1; i < 32; i = i + 1) begin
            r_ad = i[4:0]; r_wd = {i[4:0], i[4:0], i[4:0], i[4:0], i[4:0], i[4:0], 2'b00};
            r_we = 1;
            @(posedge clk); #1;
            r_we = 0;
        end
        for (i = 1; i < 32; i = i + 1) begin
            r_a1 = i[4:0]; #1;
            check_rf(r_d1, {i[4:0], i[4:0], i[4:0], i[4:0], i[4:0], i[4:0], 2'b00},
                     "all-register sweep round-trip");
        end

        r_rst = 1; @(posedge clk); #1; r_rst = 0;
        r_a1 = 5'd5; #1; check_rf(r_d1, 32'b0, "reset clears x5");

        r_ad = 5'd7; r_wd = 32'hFFFF_FFFF; r_we = 0;
        @(posedge clk); #1;
        r_a1 = 5'd7; #1; check_rf(r_d1, 32'b0, "reg_write=0 performs no write");
        $display("  [S0.7] Register file: x0 guard, all 31 registers, reset, write-enable");
    end
endtask

// ===========================================================================
//  SUITE 0.8 - CRC (replaces the golden vector file)
//
//  OPERAND ROLES: rs1 (u_a) carries the data, rs2 (u_b) carries the running
//  CRC. That is the order the official validation firmware uses -
//  "crcb s0, s1, s0" folds s1 into the accumulator held in s0 - and getting it
//  backwards is the one thing about this unit that a correct algorithm and a
//  correct check value will not catch, because CRCB(seed=X, data=Y) and
//  CRCB(seed=Y, data=X) are both perfectly valid CRC-16 computations. The
//  firmware anchor at the end of this task is what pins the order down.
// ===========================================================================
task suite_crc;
    reg [15:0] seed;
    reg [7:0]  msg [0:8];
    reg [7:0]  fw_b [0:7];
    reg [15:0] fw_h [0:3];
    reg [31:0] fw_w [0:1];
    begin
        f0 = 0;

        // The standard CRC-16/CCITT-FALSE check value: chaining CRCB over the
        // ASCII string "123456789" from seed 0xFFFF must give 0x29B1. This is
        // the hard gate on the algorithm being the right one.
        msg[0]=8'h31; msg[1]=8'h32; msg[2]=8'h33; msg[3]=8'h34; msg[4]=8'h35;
        msg[5]=8'h36; msg[6]=8'h37; msg[7]=8'h38; msg[8]=8'h39;
        seed = 16'hFFFF;
        u_f3 = 3'b000;
        for (k = 0; k < 9; k = k + 1) begin
            u_a = {24'b0, msg[k]};    // rs1 = data
            u_b = {16'b0, seed};      // rs2 = running CRC
            #1;
            seed = u_crcq[15:0];
        end
        if (seed === 16'h29B1) begin
            pass = pass + 1;
            $display("  CHECK-VALUE GATE: chained CRCB(\"123456789\") = 0x%h (expected 0x29B1) PASS", seed);
        end else begin
            f0 = f0 + 1;
            fail_msg("CRC check-value gate");
            $display("        got 0x%h, expected 0x29B1", seed);
        end

        // ---- Competition anchor: the three chains _rvbl2_crc_test runs -----
        // The official firmware compares each of these against 0x1E82 and
        // branches to _error otherwise. Replaying them here means a regression
        // in the operand order is caught by this unit test rather than showing
        // up as an opaque x4 = FFFFFFFF two suites later.
        fw_b[0]=8'h12; fw_b[1]=8'h34; fw_b[2]=8'h56; fw_b[3]=8'h78;
        fw_b[4]=8'h90; fw_b[5]=8'hAB; fw_b[6]=8'hCD; fw_b[7]=8'hEF;
        fw_h[0]=16'h1234; fw_h[1]=16'h5678; fw_h[2]=16'h90AB; fw_h[3]=16'hCDEF;
        fw_w[0]=32'h12345678; fw_w[1]=32'h90ABCDEF;

        seed = 16'hFFFF; u_f3 = 3'b000;
        for (k = 0; k < 8; k = k + 1) begin
            u_a = {24'b0, fw_b[k]}; u_b = {16'b0, seed}; #1; seed = u_crcq[15:0];
        end
        if (seed === 16'h1E82) pass = pass + 1;
        else begin
            f0 = f0 + 1; fail_msg("firmware anchor: 8x CRCB");
            $display("        got 0x%h, the validation firmware expects 0x1E82", seed);
        end

        seed = 16'hFFFF; u_f3 = 3'b001;
        for (k = 0; k < 4; k = k + 1) begin
            u_a = {16'b0, fw_h[k]}; u_b = {16'b0, seed}; #1; seed = u_crcq[15:0];
        end
        if (seed === 16'h1E82) pass = pass + 1;
        else begin
            f0 = f0 + 1; fail_msg("firmware anchor: 4x CRCH");
            $display("        got 0x%h, the validation firmware expects 0x1E82", seed);
        end

        seed = 16'hFFFF; u_f3 = 3'b010;
        for (k = 0; k < 2; k = k + 1) begin
            u_a = fw_w[k]; u_b = {16'b0, seed}; #1; seed = u_crcq[15:0];
        end
        if (seed === 16'h1E82) pass = pass + 1;
        else begin
            f0 = f0 + 1; fail_msg("firmware anchor: 2x CRCW");
            $display("        got 0x%h, the validation firmware expects 0x1E82", seed);
        end

        // Directed corners across all three widths. (u_a = data, u_b = seed.)
        for (k = 0; k < 3; k = k + 1) begin
            u_f3 = k[2:0];
            u_a = 32'h0000_0000; u_b = 32'h0000_0000; #1;
            if (u_crcq !== {16'b0, ref_crc(u_f3, 16'h0000, 32'h0)}) begin f0=f0+1; note_fail("CRC zero seed, zero data"); end
            u_a = 32'hFFFF_FFFF; u_b = 32'h0000_FFFF; #1;
            if (u_crcq !== {16'b0, ref_crc(u_f3, 16'hFFFF, 32'hFFFFFFFF)}) begin f0=f0+1; note_fail("CRC all-ones"); end
            u_a = 32'h0000_0000; u_b = 32'h0000_FFFF; #1;
            if (u_crcq !== {16'b0, ref_crc(u_f3, 16'hFFFF, 32'h0)}) begin f0=f0+1; note_fail("CRC ones seed, zero data"); end
        end

        // Only rs2[15:0] is the seed: the upper half must be ignored entirely.
        u_f3 = 3'b000; u_a = 32'h0000_005A;
        u_b = 32'h0000_1234; #1; k = u_crcq;
        u_b = 32'hFFFF_1234; #1;
        if (u_crcq === k) pass = pass + 1;
        else begin f0=f0+1; note_fail("CRC must ignore rs2[31:16]"); end

        // The data operand is the one that must be read at full width: a CRCW
        // has to see rs1[31:16], where a CRCB must not. This is the mirror of
        // the check above and fails if the two operands are ever swapped back.
        u_f3 = 3'b010; u_b = 32'h0000_FFFF;
        u_a = 32'h0000_1234; #1; k = u_crcq;
        u_a = 32'hABCD_1234; #1;
        if (u_crcq !== k) pass = pass + 1;
        else begin f0=f0+1; note_fail("CRCW must fold all 32 bits of rs1"); end

        // funct3=11 is not a CRC encoding; the seed passes through.
        u_f3 = 3'b011; u_b = 32'h0000_ABCD; u_a = 32'hFFFF_FFFF; #1;
        if (u_crcq === 32'h0000_ABCD) pass = pass + 1;
        else begin f0=f0+1; note_fail("CRC unused encoding must pass the seed through"); end

        // Randomised across all three widths against the reference model.
        for (n = 0; n < 600; n = n + 1) begin
            u_a  = $random;   // data
            u_b  = $random;   // seed
            u_f3 = n % 3;
            #1;
            if (u_crcq === {16'b0, ref_crc(u_f3, u_b[15:0], u_a)}) pass = pass + 1;
            else begin
                f0 = f0 + 1;
                note_fail("CRC randomised");
                if (fail_budget >= 0)
                    $display("        f3=%b seed=%h data=%h got=%h exp=%h",
                             u_f3, u_b[15:0], u_a, u_crcq, ref_crc(u_f3, u_b[15:0], u_a));
            end
        end

        if (f0 == 0) pass_msg("S0.8 CRC: check value, firmware anchor, three widths, 600 randomised");
        $display("  [S0.8] CRC-16/CCITT-FALSE: KAT gate, firmware 0x1E82 anchor, corners, 600 randomised");
    end
endtask

// ===========================================================================
//  SUITE 0.9 - IMEM (generated case-ROM)
// ===========================================================================
task check_imem(input [31:0] exp, input [8*72-1:0] name);
    begin
        if (p_data === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0) $display("        addr=%h got=%h exp=%h", p_addr, p_data, exp);
        end
    end
endtask

task suite_imem;
    begin
        // The ROM holds two images:
        //   word   0..258  official validation firmware   (0x00400000)
        //   word 259..511  gap, reads back 0
        //   word 512..994  supplementary coverage program (0x00400800)
        // scripts/gen_ci_imem.py --check guards every word; these are the
        // landmarks that would catch a placement mistake - a misplaced image
        // would still be a self-consistent ROM and pass that check.
        p_oe = 1;

        // ---- official firmware, first three words --------------------------
        p_addr = IMEM_BASE + 0;  #1; check_imem(32'h123452b7, "official word 0 (lui t0,0x12345)");
        p_addr = IMEM_BASE + 4;  #1; check_imem(32'h12345337, "official word 1 (lui t1,0x12345)");
        p_addr = IMEM_BASE + 8;  #1; check_imem(32'h3e629463, "official word 2 (bne t0,t1,_error)");

        // ---- the two exit loops, which SUITE 2A synchronises on ------------
        p_addr = FW_PASS_LOOP - 4; #1; check_imem(32'h00000213, "all_good: addi x4, x0, 0");
        p_addr = FW_PASS_LOOP;     #1; check_imem(32'h0000006f, "all_good: j . (pass self-loop)");
        p_addr = FW_ERROR_PC;      #1; check_imem(32'hfff00213, "_error:   addi x4, x0, -1");
        p_addr = FW_FAIL_LOOP;     #1; check_imem(32'h0000006f, "_error:   j . (fail self-loop)");

        // ---- .rodata the firmware LOADS OUT OF IMEM ------------------------
        // These are constants, not instructions. Reaching them is the
        // ARCH_SPEC 7.4 case: IMEM is combinational with no output register,
        // so a load only resolves here because oe_o and the address mux stay
        // asserted through WRITEBACK.
        p_addr = 32'h004003F8; #1; check_imem(32'h12345678, "crc_data[0] in IMEM");
        p_addr = 32'h004003FC; #1; check_imem(32'h90abcdef, "crc_data[1] in IMEM");
        p_addr = 32'h00400400; #1; check_imem(32'h11111111, "source_data[0] in IMEM");
        p_addr = 32'h00400408; #1; check_imem(32'h33333333, "source_data[2] in IMEM");

        // ---- the gap between the two images --------------------------------
        p_addr = IMEM_BASE + 259*4; #1; check_imem(32'b0, "first word past the official image -> 0");
        p_addr = IMEM_BASE + 400*4; #1; check_imem(32'b0, "mid-gap -> 0, no aliasing");

        // ---- supplementary program at SUPP_BASE ----------------------------
        p_addr = SUPP_BASE + 0;  #1; check_imem(32'h10010a37, "supp word 0 (lui x20,0x10010)");
        p_addr = SUPP_BASE + 4;  #1; check_imem(32'h10010fb7, "supp word 1 (lui x31,0x10010)");
        p_addr = SUPP_BASE + 8;  #1; check_imem(32'h100f8f93, "supp word 2 (addi x31,x31,256)");

        // oe_i low must read a defined 0, not x.
        p_oe = 0; p_addr = IMEM_BASE; #1; check_imem(32'b0, "oe=0 reads defined 0");

        // Past the end of both images but still inside the 4MB architectural
        // window: must read 0, never alias back into a real word.
        p_oe = 1;
        p_addr = SUPP_BASE + 483*4;       #1; check_imem(32'b0, "one word past the ROM -> 0, no aliasing");
        p_addr = SUPP_BASE + 483*4 + 128; #1; check_imem(32'b0, "further past the ROM -> 0");
        p_addr = IMEM_BASE + 32'h003F_FFFC;  #1; check_imem(32'b0, "top of 4MB window -> 0");
        p_oe = 0;
        $display("  [S0.9] IMEM: both images placed, gap reads 0, oe gating, out-of-image reads");
    end
endtask

// ===========================================================================
//  SUITE 0.10 - DMEM
//  Signals are only changed a delta after a clock edge, never in the same
//  timestep the memory samples on: doing the latter is a genuine Verilog race
//  and it produced intermittently-skipped writes when this was first written.
// ===========================================================================
task dmem_write(input [31:0] a, input [31:0] d, input [3:0] mask);
    begin
        @(posedge clk); #1;
        m_addr = a; m_wd = d; m_bw = mask; m_we = 1; m_oe = 0;
        @(posedge clk); #1;
        m_we = 0;
    end
endtask

task dmem_read(input [31:0] a);
    begin
        @(posedge clk); #1;
        m_addr = a; m_oe = 1; m_we = 0;
        @(posedge clk);
        // Sample late in the cycle, where the register file actually captures
        // load data, rather than right at the edge.
        #9;
        m_oe = 0;
    end
endtask

task check_dmem(input [31:0] exp, input [8*72-1:0] name);
    begin
        if (m_rd === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0) $display("        got=%h exp=%h", m_rd, exp);
        end
    end
endtask

task suite_dmem;
    begin
        m_we=0; m_oe=0; m_bw=0; m_addr=0; m_wd=0;
        for (i = 0; i < MWORDS; i = i + 1) U_DMEM.mem[i] = 32'b0;
        @(posedge clk); #1;

        dmem_write(32'h1001_0000, 32'hCAFE_BABE, 4'b1111);
        dmem_read(32'h1001_0000);
        check_dmem(32'hCAFE_BABE, "full-word write then registered read-back");

        dmem_write(32'h1001_0000, 32'h00AA_0000, 4'b0100);
        dmem_read(32'h1001_0000);
        check_dmem(32'hCAAA_BABE, "single byte lane preserves the other three");

        dmem_write(32'h1001_0004, 32'h1111_2222, 4'b1111);
        repeat (5) @(posedge clk);
        dmem_read(32'h1001_0004);
        check_dmem(32'h1111_2222, "write survives idle cycles (true storage)");

        dmem_write(32'h1001_0008, 32'hFFFF_FFFF, 4'b1111);
        dmem_write(32'h1001_0008, 32'h0000_00AA, 4'b0001);
        dmem_read(32'h1001_0008); check_dmem(32'hFFFF_FFAA, "lane 0 only");
        dmem_write(32'h1001_0008, 32'h0000_BB00, 4'b0010);
        dmem_read(32'h1001_0008); check_dmem(32'hFFFF_BBAA, "lane 1 only");
        dmem_write(32'h1001_0008, 32'h00CC_0000, 4'b0100);
        dmem_read(32'h1001_0008); check_dmem(32'hFFCC_BBAA, "lane 2 only");
        dmem_write(32'h1001_0008, 32'hDD00_0000, 4'b1000);
        dmem_read(32'h1001_0008); check_dmem(32'hDDCC_BBAA, "lane 3 only");

        // Simultaneous we/oe cannot occur given the FSM's scoping, but if it
        // ever did the behaviour must be deterministic write-wins.
        @(posedge clk); #1;
        m_addr = 32'h1001_000C; m_wd = 32'h5555_5555; m_bw = 4'b1111; m_we = 1; m_oe = 1;
        @(posedge clk); #1; m_we = 0; m_oe = 0;
        dmem_read(32'h1001_000C);
        check_dmem(32'h5555_5555, "simultaneous we and oe -> write wins");

        dmem_write(32'h1001_0010, 32'hAAAA_BBBB, 4'b1111);
        dmem_write(32'h1001_0014, 32'hCCCC_DDDD, 4'b1111);
        dmem_read(32'h1001_0010); check_dmem(32'hAAAA_BBBB, "non-adjacent word A independent");
        dmem_read(32'h1001_0014); check_dmem(32'hCCCC_DDDD, "non-adjacent word B independent");

        dmem_read(32'h1001_0020);
        check_dmem(32'h0000_0000, "never-written word reads 0");

        dmem_write(32'h1001_0018, 32'hFFFF_FFFF, 4'b1111);
        dmem_write(32'h1001_0018, 32'h0000_5678, 4'b0011);
        dmem_read(32'h1001_0018); check_dmem(32'hFFFF_5678, "half-word write lanes 0+1");

        dmem_write(32'h1001_001C, 32'h0000_0000, 4'b1111);
        dmem_write(32'h1001_001C, 32'h9ABC_0000, 4'b1100);
        dmem_read(32'h1001_001C); check_dmem(32'h9ABC_0000, "half-word write lanes 2+3");

        dmem_write(32'h1001_0000 + (MWORDS-1)*4, 32'hDEAD_BEEF, 4'b1111);
        dmem_read(32'h1001_0000 + (MWORDS-1)*4);
        check_dmem(32'hDEAD_BEEF, "last implemented word");

        // Inside the architectural 8kB window but past the instantiated array:
        // must read 0 and write nothing, never alias into a real word. This is
        // the guard that makes DMEM_WORDS a safe resize knob.
        dmem_write(32'h1001_0000, 32'hA5A5_A5A5, 4'b1111);
        dmem_write(32'h1001_0080, 32'hDEAD_BEEF, 4'b1111);
        dmem_read(32'h1001_0000);
        check_dmem(32'hA5A5_A5A5, "out-of-range write must not alias into word 0");
        dmem_read(32'h1001_0080);
        check_dmem(32'h0000_0000, "out-of-range read returns 0, not an aliased word");
        dmem_read(32'h1001_1FFC);
        check_dmem(32'h0000_0000, "read at top of window, past array -> 0");
        $display("  [S0.10] DMEM: byte lanes, storage, aliasing prevention");
    end
endtask

// ===========================================================================
//  SUITE 0.11 - glue blocks
//  These carry logic that used to live inline in riscv_core, so they are the
//  parts of the design with no prior test history at all.
// ===========================================================================
task suite_glue;
    begin
        f0 = 0;

        // mux2_32: s selects b, not a.
        u_a = 32'hAAAA_AAAA; u_b = 32'h5555_5555;
        g_s = 1'b0; #1; if (g_muxz !== 32'hAAAA_AAAA) begin f0=f0+1; note_fail("mux2_32 s=0 must select a"); end
        g_s = 1'b1; #1; if (g_muxz !== 32'h5555_5555) begin f0=f0+1; note_fail("mux2_32 s=1 must select b"); end
        for (n = 0; n < 200; n = n + 1) begin
            u_a = $random; u_b = $random; g_s = n[0]; #1;
            if (g_muxz === (g_s ? u_b : u_a)) pass = pass + 1;
            else begin f0=f0+1; note_fail("mux2_32 randomised"); end
        end

        // wb_mux_32: every defined select, plus the undefined ones falling
        // through to the ALU result exactly as the original case default did.
        g_alu=32'h1111_1111; g_mul=32'h2222_2222; g_crc=32'h3333_3333;
        g_load=32'h4444_4444; g_pc4=32'h5555_5555;
        g_wbsel=3'b000; #1; if (g_wbz!==g_alu)  begin f0=f0+1; note_fail("wb_mux 000 -> alu_result"); end else pass=pass+1;
        g_wbsel=3'b001; #1; if (g_wbz!==g_mul)  begin f0=f0+1; note_fail("wb_mux 001 -> mult_result"); end else pass=pass+1;
        g_wbsel=3'b010; #1; if (g_wbz!==g_crc)  begin f0=f0+1; note_fail("wb_mux 010 -> crc_result"); end else pass=pass+1;
        g_wbsel=3'b011; #1; if (g_wbz!==g_load) begin f0=f0+1; note_fail("wb_mux 011 -> lsu_load_data"); end else pass=pass+1;
        g_wbsel=3'b100; #1; if (g_wbz!==g_pc4)  begin f0=f0+1; note_fail("wb_mux 100 -> pc_plus_4"); end else pass=pass+1;
        g_wbsel=3'b101; #1; if (g_wbz!==g_alu)  begin f0=f0+1; note_fail("wb_mux 101 -> alu_result (default)"); end else pass=pass+1;
        g_wbsel=3'b110; #1; if (g_wbz!==g_alu)  begin f0=f0+1; note_fail("wb_mux 110 -> alu_result (default)"); end else pass=pass+1;
        g_wbsel=3'b111; #1; if (g_wbz!==g_alu)  begin f0=f0+1; note_fail("wb_mux 111 -> alu_result (default)"); end else pass=pass+1;

        // ir_fields: the extraction the canvas cannot do with a wire.
        u_ins = 32'hFFFF_FFFF; #1;
        if (g_rs1===5'h1F && g_rs2===5'h1F && g_rd===5'h1F) pass=pass+1;
        else begin f0=f0+1; note_fail("ir_fields all-ones"); end
        u_ins = 32'h0000_0000; #1;
        if (g_rs1===5'h00 && g_rs2===5'h00 && g_rd===5'h00) pass=pass+1;
        else begin f0=f0+1; note_fail("ir_fields all-zeros"); end
        for (n = 0; n < 300; n = n + 1) begin
            u_ins = $random; #1;
            if (g_rs1 === u_ins[19:15] && g_rs2 === u_ins[24:20] && g_rd === u_ins[11:7]) pass = pass + 1;
            else begin
                f0 = f0 + 1;
                note_fail("ir_fields randomised");
                if (fail_budget >= 0)
                    $display("        ir=%h rs1=%h(%h) rs2=%h(%h) rd=%h(%h)", u_ins,
                             g_rs1, u_ins[19:15], g_rs2, u_ins[24:20], g_rd, u_ins[11:7]);
            end
        end

        if (f0 == 0) pass_msg("S0.11 Glue blocks: mux2_32, wb_mux_32, ir_fields");
        $display("  [S0.11] Glue blocks: mux2_32, wb_mux_32, ir_fields");
    end
endtask

// ===========================================================================
//  SUITE 1 - control unit
// ===========================================================================
localparam [2:0] C_ILLEGAL = 3'd0,  // incl. FENCE / ECALL / EBREAK: no rd write
                 C_WRITES  = 3'd1,
                 C_LOAD    = 3'd2,
                 C_STORE   = 3'd3,
                 C_BRANCH  = 3'd4;

// An independent classifier derived from the ISA tables, deliberately not
// copied from control_unit's own decode expressions.
function [2:0] ref_class;
    input [31:0] instr;
    reg [6:0] opcode, funct7;
    reg [2:0] funct3;
    reg       shift_ok;
    begin
        opcode = instr[6:0];
        funct3 = instr[14:12];
        funct7 = instr[31:25];
        case (opcode)
            OP_ALU_REG:
                ref_class = ((funct7==7'b0000000) ||
                             ((funct7==7'b0100000) && (funct3==3'b000 || funct3==3'b101)) ||
                             ((funct7==7'b0000001) && (funct3[2]==1'b0)) ||
                             ((funct7==7'b1000000) && (funct3==3'b000||funct3==3'b001||funct3==3'b010)))
                            ? C_WRITES : C_ILLEGAL;
            OP_ALU_IMM: begin
                shift_ok = (funct3==3'b001) ? (funct7==7'b0000000)
                                            : ((funct7==7'b0000000)||(funct7==7'b0100000));
                ref_class = ((funct3!=3'b001 && funct3!=3'b101) || shift_ok) ? C_WRITES : C_ILLEGAL;
            end
            OP_LOAD:   ref_class = (funct3==3'b000||funct3==3'b001||funct3==3'b010||
                                    funct3==3'b100||funct3==3'b101) ? C_LOAD : C_ILLEGAL;
            OP_STORE:  ref_class = (funct3==3'b000||funct3==3'b001||funct3==3'b010)
                                   ? C_STORE : C_ILLEGAL;
            OP_BRANCH: ref_class = (funct3==3'b000||funct3==3'b001||funct3==3'b100||
                                    funct3==3'b101||funct3==3'b110||funct3==3'b111)
                                   ? C_BRANCH : C_ILLEGAL;
            OP_JAL:    ref_class = C_WRITES;
            OP_JALR:   ref_class = (funct3==3'b000) ? C_WRITES : C_ILLEGAL;
            OP_LUI:    ref_class = C_WRITES;
            OP_AUIPC:  ref_class = C_WRITES;
            OP_SYSTEM: ref_class = C_ILLEGAL;   // ECALL/EBREAK take the no-result path too
            OP_FENCE:  ref_class = C_ILLEGAL;
            default:   ref_class = C_ILLEGAL;
        endcase
    end
endfunction

task ctrl_hard_reset;
    begin
        c_rst = 1; @(posedge clk); #1;
        c_rst = 0; @(posedge clk); #1;
        if (c_state !== S_FETCH) fail_msg("ctrl_hard_reset did not land in FETCH");
    end
endtask

task ctrl_wait_state(input [2:0] target, input integer max_cycles, output integer taken);
    integer c;
    begin
        c = 0;
        while ((c_state !== target) && (c < max_cycles)) begin
            @(posedge clk); #1;
            c = c + 1;
        end
        taken = c;
    end
endtask

// Drives one encoding to its terminal state, checking both where EXECUTE
// hands off to and whether rd is written there.
task check_encoding(input [31:0] instr);
    reg [2:0] cls, exp_state, got_state;
    reg       exp_regwrite;
    integer   c;
    begin
        cls = ref_class(instr);
        case (cls)
            C_LOAD:   begin exp_state = S_MEMORY;    exp_regwrite = 1'b1; end
            C_STORE:  begin exp_state = S_MEMORY;    exp_regwrite = 1'b0; end
            C_BRANCH: begin exp_state = S_FETCH;     exp_regwrite = 1'b0; end
            C_WRITES: begin exp_state = S_WRITEBACK; exp_regwrite = 1'b1; end
            default:  begin exp_state = S_WRITEBACK; exp_regwrite = 1'b0; end
        endcase

        ctrl_hard_reset;
        c_ir = instr;
        c_bt = 1'b0;

        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c != 2) begin
            note_fail("control timing FETCH->EXECUTE");
            if (fail_budget >= 0)
                $display("        took %0d cycles (expected 2) for ir=%h", c, instr);
        end

        @(posedge clk); #1;
        got_state = c_state;
        if (got_state === exp_state) pass = pass + 1;
        else begin
            note_fail("control class -> terminal state");
            if (fail_budget >= 0)
                $display("        ir=%h cls=%0d expected state %0d after EXECUTE, got %0d",
                         instr, cls, exp_state, got_state);
        end

        if (cls == C_LOAD) begin
            @(posedge clk); #1;
            if (c_state !== S_WRITEBACK) begin
                note_fail("load must reach WRITEBACK");
                if (fail_budget >= 0) $display("        ir=%h got state %0d", instr, c_state);
            end
        end

        if (cls == C_STORE || cls == C_BRANCH) begin
            // Neither class has a WRITEBACK state at all.
            if (c_regwrite === 1'b0) pass = pass + 1;
            else begin
                note_fail("store/branch must never assert reg_write");
                if (fail_budget >= 0) $display("        ir=%h", instr);
            end
        end else begin
            if (c_regwrite === exp_regwrite) pass = pass + 1;
            else begin
                note_fail("reg_write in WRITEBACK");
                if (fail_budget >= 0)
                    $display("        ir=%h cls=%0d got=%b expected=%b", instr, cls, c_regwrite, exp_regwrite);
            end
        end
    end
endtask

task check_exec_signals(
    input [31:0]   encoding,
    input          bt,
    input          exp_a_sel,
    input          exp_b_sel,
    input [3:0]    exp_alu_op,
    input [2:0]    exp_wb_src,
    input          exp_pc_src,
    input          exp_store,
    input [8*40-1:0] name
);
    integer c;
    begin
        ctrl_hard_reset;
        c_ir = encoding;
        c_bt = bt;
        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c_asel !== exp_a_sel || c_bsel !== exp_b_sel || c_aluop !== exp_alu_op ||
            c_wbsel !== exp_wb_src || c_pcsel !== exp_pc_src || c_store !== exp_store) begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        a=%b(%b) b=%b(%b) op=%h(%h) wb=%b(%b) pc=%b(%b) store=%b(%b)",
                    c_asel, exp_a_sel, c_bsel, exp_b_sel, c_aluop, exp_alu_op,
                    c_wbsel, exp_wb_src, c_pcsel, exp_pc_src, c_store, exp_store);
        end else pass = pass + 1;
    end
endtask

task suite_ctrl_sweep;
    reg [6:0] opcodes [0:10];
    reg [6:0] watch_f7 [0:7];
    integer oi, wi, f3i, f7i;
    begin
        opcodes[0]=OP_ALU_REG; opcodes[1]=OP_ALU_IMM; opcodes[2]=OP_LOAD;
        opcodes[3]=OP_STORE;   opcodes[4]=OP_BRANCH;  opcodes[5]=OP_JAL;
        opcodes[6]=OP_JALR;    opcodes[7]=OP_LUI;     opcodes[8]=OP_AUIPC;
        opcodes[9]=OP_SYSTEM;  opcodes[10]=OP_FENCE;
        // Valid boundaries plus clearly-invalid funct7 values.
        watch_f7[0]=7'b0000000; watch_f7[1]=7'b0100000; watch_f7[2]=7'b0000001;
        watch_f7[3]=7'b1000000; watch_f7[4]=7'b0010101; watch_f7[5]=7'b1111111;
        watch_f7[6]=7'b0000011; watch_f7[7]=7'b1010101;

        for (oi = 0; oi < 11; oi = oi + 1)
            for (f3i = 0; f3i < 8; f3i = f3i + 1)
                for (wi = 0; wi < 8; wi = wi + 1) begin
                    f7i = watch_f7[wi];
                    // rd=1 so a spurious reg_write is observable rather than
                    // masked by the x0 write-guard.
                    check_encoding({f7i[6:0], 5'd0, 5'd0, f3i[2:0], 5'd1, opcodes[oi]});
                end
        $display("  [S1.1] Control decode sweep: %0d encodings through the real FSM", 11*8*8);
    end
endtask

task suite_ctrl_fsm;
    integer c;
    begin
        c_rst = 1; c_ir = 32'h0000_0013; @(posedge clk); #1;
        if (c_state === S_RESET) pass=pass+1; else fail_msg("not in RESET while rst=1");

        c_rst = 0; @(posedge clk); #1;
        if (c_state === S_FETCH) pass=pass+1; else fail_msg("RESET->FETCH on rst deassert");

        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c == 2) pass=pass+1; else fail_msg("FETCH->EXECUTE must take exactly 2 cycles");

        // Branch, taken: 3-cycle instruction, EXECUTE returns straight to FETCH.
        ctrl_hard_reset;
        c_ir = {7'b0, 5'd2, 5'd1, 3'b000, 5'b0, OP_BRANCH};
        c_bt = 1;
        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c == 2) pass=pass+1; else fail_msg("branch FETCH->EXECUTE cycles");
        @(posedge clk); #1;
        if (c_state === S_FETCH) pass=pass+1; else fail_msg("EXECUTE(branch taken)->FETCH");

        // Store: 4-cycle, EXECUTE->MEMORY->FETCH, we_o only in MEMORY.
        ctrl_hard_reset;
        c_ir = {7'b0, 5'd2, 5'd1, 3'b010, 5'd0, OP_STORE};
        c_bt = 0;
        ctrl_wait_state(S_EXECUTE, 5, c);
        @(posedge clk); #1;
        if (c_state === S_MEMORY) pass=pass+1; else fail_msg("EXECUTE(store)->MEMORY");
        if (c_we === 1'b1) pass=pass+1; else fail_msg("we_o not asserted in MEMORY for store");
        @(posedge clk); #1;
        if (c_state === S_FETCH) pass=pass+1; else fail_msg("MEMORY(store)->FETCH");

        // Load: 5-cycle, EXECUTE->MEMORY->WRITEBACK->FETCH. oe_o must still be
        // asserted in WRITEBACK - that is what makes a load from the
        // combinational IMEM work at all.
        ctrl_hard_reset;
        c_ir = {12'd0, 5'd2, 3'b010, 5'd1, OP_LOAD};
        ctrl_wait_state(S_EXECUTE, 5, c);
        @(posedge clk); #1;
        if (c_state === S_MEMORY) pass=pass+1; else fail_msg("EXECUTE(load)->MEMORY");
        @(posedge clk); #1;
        if (c_state === S_WRITEBACK) pass=pass+1; else fail_msg("MEMORY(load)->WRITEBACK");
        if (c_oe === 1'b1) pass=pass+1;
        else fail_msg("oe_o must stay asserted in WRITEBACK for a load");
        @(posedge clk); #1;
        if (c_state === S_FETCH) pass=pass+1; else fail_msg("WRITEBACK(load)->FETCH");

        // sys_event_o: a one-cycle pulse in EXECUTE, for ECALL and EBREAK only.
        ctrl_hard_reset;
        c_ir = 32'h0000_0073; // ECALL
        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c_sysevent === 1'b1) pass=pass+1; else fail_msg("sys_event_o not pulsed for ECALL");
        @(posedge clk); #1;
        if (c_state === S_WRITEBACK) pass=pass+1; else fail_msg("EXECUTE(ecall)->WRITEBACK");
        if (c_sysevent === 1'b0) pass=pass+1; else fail_msg("sys_event_o must not persist into WRITEBACK");
        if (c_regwrite === 1'b0) pass=pass+1; else fail_msg("ECALL must not assert reg_write");

        ctrl_hard_reset;
        c_ir = 32'h0010_0073; // EBREAK
        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c_sysevent === 1'b1) pass=pass+1; else fail_msg("sys_event_o not pulsed for EBREAK");

        // A SYSTEM word that is not exactly ECALL or EBREAK must not pulse the
        // event, so stray ROM padding cannot forge a firmware-completion marker.
        ctrl_hard_reset;
        c_ir = 32'h0000_00F3; // SYSTEM, funct3=000, imm=0, but rd=1
        ctrl_wait_state(S_EXECUTE, 5, c);
        if (c_sysevent === 1'b0) pass=pass+1; else fail_msg("non-canonical SYSTEM word pulsed sys_event_o");
        @(posedge clk); #1;
        if (c_regwrite === 1'b0) pass=pass+1; else fail_msg("non-canonical SYSTEM word asserted reg_write");

        // Reset mid-instruction must abort we_o in the SAME cycle, not the next.
        ctrl_hard_reset;
        c_ir = {7'b0, 5'd2, 5'd1, 3'b010, 5'd0, OP_STORE};
        ctrl_wait_state(S_EXECUTE, 5, c);
        @(posedge clk); #1;
        if (c_we === 1'b1) pass=pass+1; else fail_msg("we_o should be asserted in MEMORY (pre-check)");
        c_rst = 1; #1;   // assert reset with no further clock edge
        if (c_we === 1'b0) pass=pass+1;
        else fail_msg("we_o must drop the same cycle rst_i asserts, mid-instruction");
        c_rst = 0;

        // Illegal instruction: reaches WRITEBACK, never MEMORY, writes nothing.
        ctrl_hard_reset;
        c_ir = 32'hFFFF_FFFF;
        ctrl_wait_state(S_EXECUTE, 5, c);
        @(posedge clk); #1;
        if (c_state === S_WRITEBACK) pass=pass+1; else fail_msg("illegal instruction must reach WRITEBACK");
        if (c_regwrite === 1'b0) pass=pass+1; else fail_msg("illegal instruction must not assert reg_write");
        if (c_we === 1'b0 && c_oe === 1'b0) pass=pass+1;
        else fail_msg("illegal instruction must not assert we_o/oe_o in WRITEBACK");
        $display("  [S1.2] Control FSM: transitions, cycle counts, sys_event, reset abort");
    end
endtask

task suite_ctrl_signals;
    begin
        // R-type: a=rs1(0), b=rs2(0), wb=ALU(000), pc=+4(0)
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b000, 5'd0, OP_ALU_REG}, 0, 0,0,4'h1,3'b000,0,0, "ADD selects");
        check_exec_signals({7'b0100000, 5'd0, 5'd0, 3'b000, 5'd0, OP_ALU_REG}, 0, 0,0,4'h2,3'b000,0,0, "SUB selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b001, 5'd0, OP_ALU_REG}, 0, 0,0,4'h6,3'b000,0,0, "SLL selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b010, 5'd0, OP_ALU_REG}, 0, 0,0,4'h9,3'b000,0,0, "SLT selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b011, 5'd0, OP_ALU_REG}, 0, 0,0,4'hA,3'b000,0,0, "SLTU selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b100, 5'd0, OP_ALU_REG}, 0, 0,0,4'h5,3'b000,0,0, "XOR selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b101, 5'd0, OP_ALU_REG}, 0, 0,0,4'h7,3'b000,0,0, "SRL selects");
        check_exec_signals({7'b0100000, 5'd0, 5'd0, 3'b101, 5'd0, OP_ALU_REG}, 0, 0,0,4'h8,3'b000,0,0, "SRA selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b110, 5'd0, OP_ALU_REG}, 0, 0,0,4'h4,3'b000,0,0, "OR selects");
        check_exec_signals({7'b0000000, 5'd0, 5'd0, 3'b111, 5'd0, OP_ALU_REG}, 0, 0,0,4'h3,3'b000,0,0, "AND selects");

        // I-type: a=rs1(0), b=imm(1)
        check_exec_signals({12'd0, 5'd0, 3'b000, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h1,3'b000,0,0, "ADDI selects");
        check_exec_signals({12'd0, 5'd0, 3'b010, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h9,3'b000,0,0, "SLTI selects");
        check_exec_signals({12'd0, 5'd0, 3'b011, 5'd0, OP_ALU_IMM}, 0, 0,1,4'hA,3'b000,0,0, "SLTIU selects");
        check_exec_signals({12'd0, 5'd0, 3'b100, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h5,3'b000,0,0, "XORI selects");
        check_exec_signals({12'd0, 5'd0, 3'b110, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h4,3'b000,0,0, "ORI selects");
        check_exec_signals({12'd0, 5'd0, 3'b111, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h3,3'b000,0,0, "ANDI selects");
        check_exec_signals({7'b0000000, 5'd5, 5'd0, 3'b001, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h6,3'b000,0,0, "SLLI selects");
        check_exec_signals({7'b0000000, 5'd5, 5'd0, 3'b101, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h7,3'b000,0,0, "SRLI selects");
        check_exec_signals({7'b0100000, 5'd5, 5'd0, 3'b101, 5'd0, OP_ALU_IMM}, 0, 0,1,4'h8,3'b000,0,0, "SRAI selects");

        check_exec_signals({20'h12345, 5'd0, OP_LUI},                        0, 0,1,4'h0,3'b000,0,0, "LUI selects");
        check_exec_signals({20'h12345, 5'd0, OP_AUIPC},                      0, 1,1,4'h1,3'b000,0,0, "AUIPC selects");
        check_exec_signals({12'd0, 5'd0, 3'b010, 5'd0, OP_LOAD},             0, 0,1,4'h1,3'b011,0,0, "LW selects");
        check_exec_signals({7'b0, 5'd0, 5'd0, 3'b010, 5'd0, OP_STORE},       0, 0,1,4'h1,3'b000,0,1, "SW selects");
        check_exec_signals({7'b0000001, 5'd0, 5'd0, 3'b000, 5'd0, OP_ALU_REG},0, 0,0,4'h1,3'b001,0,0, "MUL selects");
        check_exec_signals({7'b1000000, 5'd0, 5'd0, 3'b000, 5'd0, OP_ALU_REG},0, 0,0,4'h1,3'b010,0,0, "CRCB selects");
        check_exec_signals({1'b0, 10'b0000000100, 1'b0, 8'b0, 5'd1, OP_JAL}, 0, 1,1,4'h1,3'b100,1,0, "JAL selects");
        check_exec_signals({12'd0, 5'd0, 3'b000, 5'd1, OP_JALR},             0, 0,1,4'h1,3'b100,1,0, "JALR selects");
        check_exec_signals({1'b0,6'b0,5'd0,5'd0,3'b000,4'b0010,1'b0,OP_BRANCH},1, 1,1,4'h1,3'b000,1,0, "BEQ taken selects");
        check_exec_signals({1'b0,6'b0,5'd0,5'd0,3'b000,4'b0010,1'b0,OP_BRANCH},0, 1,1,4'h1,3'b000,0,0, "BEQ untaken selects");
        $display("  [S1.3] Control outputs: alu_op and every mux select at EXECUTE");
    end
endtask

// ===========================================================================
//  SUITE 2 - integration
//
//   2A  the official validation firmware, from reset, verdict in x4
//   2B  this project's supplementary program, entered at SUPP_BASE
// ===========================================================================
integer cyc, event_count;

// ---------------------------------------------------------------------------
// SUITE 2A support
// ---------------------------------------------------------------------------
// Every failing subtest in the official firmware branches to the same _error
// label, so "x4 = FFFFFFFF" on its own says nothing about which one failed.
// This records the PC the jump into _error came from, which identifies the
// failing subtest exactly.
reg [31:0] fw_prev_pc, fw_err_from;
reg        fw_err_seen;

always @(posedge clk) begin
    if (rst === 1'b1) begin
        fw_prev_pc  <= 32'hFFFF_FFFF;
        fw_err_from <= 32'h0;
        fw_err_seen <= 1'b0;
    end else begin
        if (`PC.pc === FW_ERROR_PC && fw_prev_pc !== FW_ERROR_PC && !fw_err_seen) begin
            fw_err_from <= fw_prev_pc;
            fw_err_seen <= 1'b1;
        end
        fw_prev_pc <= `PC.pc;
    end
end

// Shared state checks, used by both 2A and 2B.
task check_reg(input [4:0] idx, input [31:0] exp, input [8*96-1:0] name);
    reg [31:0] got;
    begin
        got = `RF.regs[idx];
        if (got === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0) $display("        x%0d got=%h exp=%h", idx, got, exp);
        end
    end
endtask

task check_dmem_word(input integer idx, input [31:0] exp, input [8*96-1:0] name);
    reg [31:0] got;
    begin
        got = `DMEM_WORD(idx);
        if (got === exp) pass = pass + 1;
        else begin
            note_fail(name);
            if (fail_budget >= 0)
                $display("        DMEM[%0d] (0x%08h) got=%h exp=%h",
                         idx, DMEM_BASE + 4*idx, got, exp);
        end
    end
endtask

// Subtest boundaries, read off the firmware's own source. Reported rather than
// asserted on - this is a diagnostic, not a pass criterion.
task fw_report_subtest(input [31:0] pc);
    begin
        $write("        the branch into _error was at pc=%08h, in ", pc);
        if      (pc <= 32'h00400118) $display("_rv32i_alu_test");
        else if (pc <= 32'h00400180) $display("_rv32i_lsu_test");
        else if (pc <= 32'h0040020C) $display("_rv32i_ctrl_test");
        else if (pc <= 32'h00400234) $display("_rv32i_reg_test");
        else if (pc <= 32'h00400294) $display("_rvbl2_mult_test");
        else if (pc <= 32'h00400348) $display("_rvbl2_crc_test");
        else if (pc <= 32'h00400374) $display("_rvbl2_crc_mem_test");
        else if (pc <= 32'h00400390) $display("_rvbl2_arith_integ_test");
        else if (pc <= 32'h004003E4) $display("_rvbl2_mem_transfer_test");
        else                          $display("the epilogue");
    end
endtask

// Run the official firmware from reset until it settles into one of its two
// self-loops. `settled` reports whether it got there at all, so a hang is
// distinguishable from a genuine FAIL verdict.
task fw_run(output integer ran, output reg settled);
    integer hold;
    begin
        for (i = 0; i < 2048; i = i + 1) `DMEM_WORD(i) = 32'b0;
        rst = 1;
        repeat (3) @(posedge clk); #1;
        rst = 0;

        ran = 0; hold = 0; settled = 1'b0;
        while (ran < FW_CYCLE_CAP && !settled) begin
            @(posedge clk); #1;
            ran = ran + 1;
            if (`PC.pc === FW_PASS_LOOP || `PC.pc === FW_FAIL_LOOP) begin
                hold = hold + 1;
                if (hold >= FW_SETTLE) settled = 1'b1;
            end else begin
                hold = 0;
            end
        end
    end
endtask

task suite_official;
    integer ran;
    reg     settled;
    reg [31:0] verdict;
    begin
        fw_run(ran, settled);
        verdict = `RF.regs[FW_VERDICT_REG];

        // ---- did it finish at all? -----------------------------------------
        if (settled) begin
            pass = pass + 1;
            $display("  Firmware settled after %0d cycles at pc=%08h (%0s)",
                     ran, `PC.pc,
                     (`PC.pc === FW_PASS_LOOP) ? "all_good" : "_error");
        end else begin
            note_fail("official firmware never reached a completion loop");
            $display("        ran the full %0d-cycle budget, pc=%08h state=%0d",
                     ran, `PC.pc, `CTRL.state);
        end

        // ---- THE COMPETITION CRITERION -------------------------------------
        // "x4 = 0x00000000 -> PASS, x4 = 0xFFFFFFFF -> FAIL"
        if (verdict === FW_PASS) begin
            pass = pass + 1;
            $display("  ******************************************************");
            $display("  *  OFFICIAL VALIDATION FIRMWARE: x4 = %08h  PASS  *", verdict);
            $display("  ******************************************************");
        end else begin
            note_fail("OFFICIAL VALIDATION FIRMWARE FAILED");
            $display("        x4 = %08h (expected %08h)", verdict, FW_PASS);
            if (fw_err_seen) fw_report_subtest(fw_err_from);
            else $display("        _error was never entered - the run did not complete");
        end

        // Reaching the pass loop and leaving x4 clear must agree with each
        // other; if they ever disagree the run is not what it appears to be.
        if (settled && `PC.pc === FW_PASS_LOOP) begin
            if (verdict === FW_PASS) pass = pass + 1;
            else note_fail("reached all_good but x4 is not 0");
        end
        if (settled && `PC.pc === FW_FAIL_LOOP) begin
            if (verdict === FW_FAIL) pass = pass + 1;
            else note_fail("reached _error but x4 is not -1");
        end

        // ---- memory state, not just the verdict register -------------------
        // The firmware's own stores, checked independently of the branches it
        // used to check them. A core that computed the right comparisons but
        // wrote to the wrong place would still show x4 = 0.
        check_dmem_word(0, FW_DM0, "official: sw 0x12345678 to test_ram+0");
        check_dmem_word(1, FW_DM1, "official: sh 0xAABB to test_ram+4");
        check_dmem_word(2, FW_DM2, "official: sb 0xCC to test_ram+8");
        check_dmem_word(4, FW_DM4, "official: copy loop word 0 (IMEM -> DMEM)");
        check_dmem_word(5, FW_DM5, "official: copy loop word 1");
        check_dmem_word(6, FW_DM6, "official: copy loop word 2");

        // The copy loop read its source out of IMEM at 0x00400400 and the CRC
        // subtest read 0x004003F8, so a correct DMEM image here is also
        // positive evidence that loads resolving into IMEM work end to end.

        // x0 survived a whole validation run, including the firmware's own
        // "addi zero, zero, 1" probe.
        check_reg(0, 32'h0000_0000, "official: x0 still zero after the full run");

        $display("  [S2A] Official validation firmware: %0d cycles, verdict x4=%08h",
                 ran, verdict);
    end
endtask

// Log every firmware-completion pulse with its cycle and PC, which is the
// evidence the Submission Guide's firmware demo asks for.
always @(posedge clk) begin
    if (rst === 1'b0 && `CTRL.sys_event_o === 1'b1) begin
        event_count = event_count + 1;
        $display("  [sys_event_o pulse #%0d] cycle=%0d pc=%h", event_count, cyc, `PC.pc);
    end
end

// ---------------------------------------------------------------------------
// SUITE 2B support: entering the supplementary program.
//
// The ROM's reset vector belongs to the official firmware, so this program is
// entered by pointing the PC at it while the core is still in reset. That is
// safe because pc_write is only asserted in EXECUTE(branch), MEMORY(store) and
// WRITEBACK - the PC holds through RESET, FETCH and DECODE, so the value
// written here is the one the first fetch uses.
//
// This is the one place the suite depends on a hierarchical procedural write
// to a register inside the design (DMEM zeroing aside). If a simulator ever
// refuses it, the fallback is to run this program as a separate project with
// the ROM's two segments swapped.
// ---------------------------------------------------------------------------
task enter_supplementary;
    begin
        for (i = 0; i < 2048; i = i + 1) `DMEM_WORD(i) = 32'b0;
        rst = 1;
        repeat (3) @(posedge clk); #1;
        `PC.pc = SUPP_BASE;   // still in reset; the next edge holds it
        rst = 0;
    end
endtask

task suite_integration;
    integer sig_fail;
    reg [31:0] sig_word;
    begin
        cyc = 0; event_count = 0;
        enter_supplementary;

        // The entry point has to actually stick, or every check below would be
        // testing the official firmware's leftovers instead.
        if (`PC.pc === SUPP_BASE) pass = pass + 1;
        else begin
            note_fail("supplementary program entry point did not take");
            $display("        pc=%08h, expected %08h", `PC.pc, SUPP_BASE);
        end

        // A fixed budget is safer than synchronising on "the" completion pulse,
        // since the program legitimately produces two (EBREAK, then ECALL).
        repeat (6000) begin
            @(posedge clk); #1;
            cyc = cyc + 1;
        end

        $display("  Ran %0d cycles, observed %0d sys_event_o pulses (expect 2: EBREAK then ECALL)",
                 cyc, event_count);
        if (event_count == 2) pass = pass + 1;
        else begin
            note_fail("expected exactly 2 sys_event_o pulses");
            $display("        got %0d", event_count);
        end

        // Every instruction test stores (actual XOR expected) into its own
        // signature slot, so a zero word means that instruction passed.
        sig_fail = 0;
        for (i = 0; i < NUM_SIG_TESTS; i = i + 1) begin
            sig_word = `DMEM_WORD(SIG_BASE_WORDS + i);
            if (sig_word === 32'b0) pass = pass + 1;
            else begin
                sig_fail = sig_fail + 1;
                note_fail("instruction signature non-zero");
                if (fail_budget >= 0)
                    $display("        signature[%0d] diff=%h", i, sig_word);
            end
        end
        $display("  Signature-based instruction tests: %0d/%0d passed",
                 NUM_SIG_TESTS - sig_fail, NUM_SIG_TESTS);

        // Structural checks for the instructions a signature slot cannot cover.
        check_reg(7,  32'h0000_0000, "x7 skipped by JAL");
        check_reg(8,  32'h0000_0001, "x8 proves JAL landed");
        check_reg(9,  EXP_JALR_LINK, "x9 JALR link address");
        check_reg(11, 32'h0000_0001, "x11 reached once via the JALR return path");
        check_reg(12, 32'h0000_0001, "x12 proves JALR landed");
        check_reg(13, 32'h0000_0001, "x13 control flow rejoined after JALR");
        check_reg(14, EXP_AUIPC,     "x14 AUIPC = pc + (5<<12)");
        check_reg(15, 32'h0000_0077, "x15 sentinel before FENCE");
        check_reg(16, 32'h0000_0077, "x16 FENCE was a pure no-op");
        check_reg(17, 32'h0000_0088, "x17 sentinel before EBREAK");
        check_reg(18, 32'h0000_0088, "x18 EBREAK was a pure no-op");

        // The load-from-IMEM timing case. IMEM is combinational with no output
        // register, so this only reads back the real constant because oe_o and
        // the address mux stay asserted through WRITEBACK.
        check_reg(22, EXP_IMEM_LOAD, "x22 load resolved into IMEM, not DMEM");
        check_reg(23, 32'h0000_0001, "x23 control flow survived the IMEM load");

        // Dependent-register loop: hazard-free by construction.
        check_reg(24, EXP_DEP_SUM,   "x24 dependent-loop sum 1..5");
        check_reg(25, EXP_DEP_CTR,   "x25 dependent-loop counter on exit");
        check_reg(27, 32'h0000_0001, "x27 dependent loop exited normally");

        // x0 must still be zero after a whole program's worth of writes.
        check_reg(0, 32'h0000_0000, "x0 hardwired zero after full program");
        $display("  [S2B] Integration: supplementary program at %08h, %0d instruction signatures, structural checks",
                 SUPP_BASE, NUM_SIG_TESTS);
    end
endtask

// ===========================================================================
//  SUITE 3 - reset stress
//  The unit-level check confirms the combinational enables drop the same cycle
//  reset asserts. What that cannot see is whether an in-flight DMEM write is
//  genuinely aborted before it commits, which is what this injects for.
//
//  3.1 injects reset at forty points in the OFFICIAL firmware, since that is
//      what runs from the reset vector.
//  3.2 then requires the official firmware to still reach x4 = 0 afterwards -
//      recovering to the competition's own verdict is a stronger claim than
//      recovering to signatures we chose ourselves.
//  3.3 does the same for the supplementary program and its 58 signatures.
// ===========================================================================
localparam INJECT_POINTS = 40;
localparam WATCH_LOW     = 16;   // words the early program writes
localparam WATCH_SIG     = 16;   // first signature slots

reg [31:0] snap_low [0:WATCH_LOW-1];
reg [31:0] snap_sig [0:WATCH_SIG-1];

task suite_reset;
    integer inj;
    begin
        for (inj = 1; inj <= INJECT_POINTS; inj = inj + 1) begin
            rst = 1; repeat (3) @(posedge clk); #1;
            rst = 0;
            repeat (inj) @(posedge clk);
            #1;

            for (i = 0; i < WATCH_LOW; i = i + 1) snap_low[i] = `DMEM_WORD(i);
            for (i = 0; i < WATCH_SIG; i = i + 1) snap_sig[i] = `DMEM_WORD(SIG_BASE_WORDS + i);

            rst = 1;            // assert mid-instruction
            @(posedge clk); #1; // the edge reset must abort

            for (i = 0; i < WATCH_LOW; i = i + 1) begin
                if (`DMEM_WORD(i) === snap_low[i]) pass = pass + 1;
                else begin
                    note_fail("DMEM word changed across the reset edge");
                    if (fail_budget >= 0)
                        $display("        inj=%0d word %0d: %h -> %h",
                                 inj, i, snap_low[i], `DMEM_WORD(i));
                end
            end
            for (i = 0; i < WATCH_SIG; i = i + 1) begin
                if (`DMEM_WORD(SIG_BASE_WORDS + i) === snap_sig[i]) pass = pass + 1;
                else begin
                    note_fail("signature word changed across the reset edge");
                    if (fail_budget >= 0)
                        $display("        inj=%0d signature %0d: %h -> %h",
                                 inj, i, snap_sig[i], `DMEM_WORD(SIG_BASE_WORDS + i));
                end
            end

            if (`PC.pc === 32'h0040_0000) pass = pass + 1;
            else begin
                note_fail("PC not at the reset vector after reset");
                if (fail_budget >= 0) $display("        inj=%0d pc=%h", inj, `PC.pc);
            end

            if (`CTRL.state === S_RESET) pass = pass + 1;
            else begin
                note_fail("FSM not in RESET after reset");
                if (fail_budget >= 0) $display("        inj=%0d state=%0d", inj, `CTRL.state);
            end

            for (i = 0; i < 32; i = i + 1) begin
                if (`RF.regs[i] === 32'd0) pass = pass + 1;
                else begin
                    note_fail("GPR not cleared by reset");
                    if (fail_budget >= 0)
                        $display("        inj=%0d x%0d=%h", inj, i, `RF.regs[i]);
                end
            end
        end
        $display("  [S3.1] Reset injected at %0d points of the official firmware: writes aborted, PC/FSM/GPRs cleared",
                 INJECT_POINTS);
    end
endtask

task suite_reset_official;
    integer ran;
    reg     settled;
    reg [31:0] verdict;
    begin
        // Reset must leave the core genuinely usable, not merely quiet. The
        // strongest available statement of that is that the competition's own
        // firmware still passes after the core has been reset mid-instruction
        // forty times.
        fw_run(ran, settled);
        verdict = `RF.regs[FW_VERDICT_REG];

        if (settled) pass = pass + 1;
        else begin
            note_fail("post-reset re-run: official firmware did not complete");
            $display("        pc=%08h after %0d cycles", `PC.pc, ran);
        end

        if (verdict === FW_PASS) pass = pass + 1;
        else begin
            note_fail("post-reset re-run: official firmware verdict is not PASS");
            $display("        x4 = %08h", verdict);
            if (fw_err_seen) fw_report_subtest(fw_err_from);
        end

        check_dmem_word(0, FW_DM0, "post-reset re-run: official DMEM word 0");
        check_dmem_word(6, FW_DM6, "post-reset re-run: official copy loop word 2");

        $display("  [S3.2] Reset recovery: the official firmware still returns x4=%08h after %0d cycles",
                 verdict, ran);
    end
endtask

task suite_reset_recovery;
    begin
        // The same claim for the supplementary program, which is what covers
        // FENCE, ECALL, EBREAK and the 58 instruction signatures.
        cyc = 0;
        enter_supplementary;
        repeat (6000) begin
            @(posedge clk); #1;
            cyc = cyc + 1;
        end

        check_reg(22, EXP_IMEM_LOAD, "post-reset re-run: IMEM load still correct");
        check_reg(24, EXP_DEP_SUM,   "post-reset re-run: dependent loop still correct");
        check_reg(18, 32'h0000_0088, "post-reset re-run: EBREAK still a no-op");

        f0 = 0;
        for (i = 0; i < NUM_SIG_TESTS; i = i + 1)
            if (`DMEM_WORD(SIG_BASE_WORDS + i) !== 32'b0) f0 = f0 + 1;
        if (f0 == 0) pass = pass + 1;
        else begin
            note_fail("post-reset re-run: instruction signatures not all zero");
            $display("        %0d of %0d slots non-zero", f0, NUM_SIG_TESTS);
        end
        $display("  [S3.3] Reset recovery: supplementary program re-runs to an identical result");
    end
endtask

// ===========================================================================
//  WAVEFORM DUMP
// ---------------------------------------------------------------------------
//  $dumpvars records only from the moment it executes, so it has to run at
//  time 0 in its own initial block. Placed at the end of MAIN, just before
//  $finish, it emits a header naming every signal and not one transition:
//  the viewer then shows a full signal list with completely empty traces.
//
//  Dumping the whole run is possible but unwieldy. It spans 197 us and
//  writes a 15.2 MB VCD with 65,152 time steps, which is more than a
//  browser-side viewer wants to open. So the dump is armed here and
//  switched straight off; MAIN opens it around SUITE 2A only. That window
//  is the official validation firmware reaching all_good: 47.9 us to
//  57.9 us, 781 kB, 2,981 time steps.
//
//  SCOPE: $dumpvars(2, dut) records the 20 canvas instances and their
//  internals, and nothing else. Dumping all of testbench instead would add
//  the reference-model functions and the SUITE 0 unit DUTs, which is 723
//  signals rather than 248 and makes the platform signal picker unusable.
//  dut.clk_i and dut.rst_i stand in for the testbench clock and reset.
//
//  TO CAPTURE THE ENTIRE RUN: delete the $dumpoff below, and the
//  $dumpon / $dumpoff pair around suite_official in MAIN.
//  TO SEE THE TESTBENCH ITSELF TOO: use $dumpvars(0, testbench).
//
//  $dumpvars walks the hierarchy structurally, so the platform renaming
//  instances to blk3658_25 and the like does not affect it. Only the
//  INSTANCE ALIASES block at the top of this file cares about those names.
// ===========================================================================
initial begin
    $dumpfile("testbench.vcd");
    $dumpvars(2, dut);
    $dumpoff;                // waveform window is opened by MAIN, below
end

// ===========================================================================
//  MAIN
// ===========================================================================
initial begin
    pass = 0; fail = 0;
    fail_budget = 200;
    rst = 1;
    c_rst = 1; c_ir = 32'h0000_0013; c_bt = 0;
    r_rst = 1; r_we = 0;
    m_we = 0; m_oe = 0;
    l_store = 0; d_we = 0; d_oe = 0;
    p_oe = 0;

    $display("============================================================");
    $display(" RVBL-2 combined verification suite");
    $display(" RV32I + Zmmul + Xicrc, 47 instructions");
    $display("============================================================");

    $display("");
    $display("-- SUITE 0: unit tests (core held in reset) -----------------");
    suite_alu;
    suite_bc;
    suite_imm;
    suite_mult;
    suite_lsu;
    suite_dec;
    suite_crc;
    suite_imem;
    suite_glue;
    suite_rf;
    suite_dmem;

    $display("");
    $display("-- SUITE 1: control unit ------------------------------------");
    suite_ctrl_sweep;
    suite_ctrl_fsm;
    suite_ctrl_signals;
    c_rst = 1;   // park the standalone control unit for the rest of the run

    $display("");
    $display("-- SUITE 2A: OFFICIAL VALIDATION FIRMWARE --------------------");
    $dumpon;                 // ---- waveform window opens
    suite_official;
    $dumpoff;                // ---- waveform window closes

    $display("");
    $display("-- SUITE 2B: integration, supplementary coverage program -----");
    suite_integration;

    $display("");
    $display("-- SUITE 3: reset stress ------------------------------------");
    suite_reset;
    suite_reset_official;
    suite_reset_recovery;

    $display("");
    $display("============================================================");
    $display("==== testbench: %0d passed, %0d failed ====", pass, fail);
    if (fail == 0) $display("ALL TESTS PASSED");
    else           $display("FAILURES PRESENT");
    $display("============================================================");
    $finish;
end

endmodule
