`timescale 1ns/1ps
// ============================================================================
// tb_app_ci_fast.v - GENERATED by application/testbench/gen_platform_tb.py; do not edit.
//
// The Stage 3 application (the free-flow toll lane controller) on the canvas
// chip `top`, checked against the golden model (application/testbench/lane_model.py).
// Use it with the APPLICATION ROM: paste chipinventor/app/imem_app.v into the
// imem block's Code field (the validation ROM stays in chipinventor/blocks/).
//
// Plays a scenario - frames into rx_i, vehicle presence / class / lane-closed
// on pins 3:0 - and prints every 8-byte record the chip sends on tx_o, as it
// arrives, with the model's verdict:
//     REC <n> @<cycle> <record, 16 hex digits> ok|MISMATCH
//     PINS <vehicle> @<cycle> <p7 p6 p5 p4> ok|MISMATCH
// Paste the log into the replay page to watch the chip's decisions; the page
// decodes those bytes and checks every CRC and Chaskey-12 tag itself.
//
// Set SCEN (below) to choose the run:
//   0  lane-a    key; a charged car, a class mismatch and the adjacent lane's
//                weak read, authenticated; a corrupted frame and its 'E'; stats
//   1  lane-b    key, gantry 2, a stolen tag and a clone sighting; the stolen
//                car and the clone, authenticated
//   2  identity  the chip measures its own ROM ('I'); key; a taxi, authenticated
// Pass: "TB_APP_CI: ALL TESTS PASSED".
//
// FAST: the UART's BAUD_RATE is overridden to 921,600 bps (33 clocks per bit
// instead of 263) and the 'P' frame sets an 8-iteration exit hold-off, so each
// run fits the platform's simulation window. Same chip, same firmware;
// chipinventor/scripts/run_ci.sh runs all three on the mirror and the export
// before you paste, and tb_app.v runs the showcase at both rates. The override
// names the UART instance: paste build/tb_app_platform.v, which run_ci.sh
// writes from this file with your export's instance names.
// ============================================================================
module testbench;   // the platform runs the module named testbench
    parameter SCEN = 0;
    localparam integer NB = 33;              // clocks per bit: 30.303 MHz / 921600
    localparam integer GAP = 30 * NB;        // idle after each frame
    localparam integer SETTLE_RISE = 1000;   // after a car arrives
    localparam integer SETTLE_FALL = 9000;  // after it leaves (> the whole decision)

    reg clk = 0, rst = 1;
    always #16.5 clk = ~clk;
    integer cycles = 0;
    always @(posedge clk) cycles = cycles + 1;

    reg  [3:0] pin_in = 4'h0;
    reg        rx = 1'b1;
    wire       tx;
    wire p0, p1, p2, p3, p4, p5, p6, p7;
    assign p0 = pin_in[0];
    assign p1 = pin_in[1];
    assign p2 = pin_in[2];
    assign p3 = pin_in[3];
    assign (weak0, weak1) p4 = 1'b0;
    assign (weak0, weak1) p5 = 1'b0;
    assign (weak0, weak1) p6 = 1'b0;
    assign (weak0, weak1) p7 = 1'b0;

    top dut (
        .clk_i(clk), .rst_i(rst),
        .pins_io_0(p0), .pins_io_1(p1), .pins_io_2(p2), .pins_io_3(p3),
        .pins_io_4(p4), .pins_io_5(p5), .pins_io_6(p6), .pins_io_7(p7),
        .tx_o(tx), .rx_i(rx));

// Instance names from the export; run_ci.sh regenerates this block.
// >>> BEGIN GENERATED ALIASES
// <<< END GENERATED ALIASES
    defparam `UART.BAUD_RATE = 921600;

    // ---- scenario lane-a: 188 event bytes, 8 records ----
    reg [7:0]  lane_a_ev  [0:187];
    reg [63:0] lane_a_rec [0:7];
    reg [7:0]  lane_a_pin [0:7];

    // ---- scenario lane-b: 162 event bytes, 4 records ----
    reg [7:0]  lane_b_ev  [0:161];
    reg [63:0] lane_b_rec [0:3];
    reg [7:0]  lane_b_pin [0:3];

    // ---- scenario identity: 87 event bytes, 3 records ----
    reg [7:0]  identity_ev  [0:86];
    reg [63:0] identity_rec [0:2];
    reg [7:0]  identity_pin [0:2];

    initial begin
        lane_a_ev[0]=8'h42; lane_a_ev[1]=8'h15; lane_a_ev[2]=8'ha5; lane_a_ev[3]=8'h4b; lane_a_ev[4]=8'h10; lane_a_ev[5]=8'h52; lane_a_ev[6]=8'h56; lane_a_ev[7]=8'h42;
        lane_a_ev[8]=8'h4c; lane_a_ev[9]=8'h2d; lane_a_ev[10]=8'h32; lane_a_ev[11]=8'h20; lane_a_ev[12]=8'h6c; lane_a_ev[13]=8'h61; lane_a_ev[14]=8'h6e; lane_a_ev[15]=8'h65;
        lane_a_ev[16]=8'h20; lane_a_ev[17]=8'h6b; lane_a_ev[18]=8'h65; lane_a_ev[19]=8'h79; lane_a_ev[20]=8'h21; lane_a_ev[21]=8'h34; lane_a_ev[22]=8'h3b; lane_a_ev[23]=8'h42;
        lane_a_ev[24]=8'h0f; lane_a_ev[25]=8'ha5; lane_a_ev[26]=8'h50; lane_a_ev[27]=8'h0a; lane_a_ev[28]=8'h1e; lane_a_ev[29]=8'hf4; lane_a_ev[30]=8'h01; lane_a_ev[31]=8'hb8;
        lane_a_ev[32]=8'h0b; lane_a_ev[33]=8'hfa; lane_a_ev[34]=8'h00; lane_a_ev[35]=8'h08; lane_a_ev[36]=8'h30; lane_a_ev[37]=8'h00; lane_a_ev[38]=8'h54; lane_a_ev[39]=8'h79;
        lane_a_ev[40]=8'h47; lane_a_ev[41]=8'h01; lane_a_ev[42]=8'h01; lane_a_ev[43]=8'h42; lane_a_ev[44]=8'h1a; lane_a_ev[45]=8'ha5; lane_a_ev[46]=8'h52; lane_a_ev[47]=8'h15;
        lane_a_ev[48]=8'hd1; lane_a_ev[49]=8'hfb; lane_a_ev[50]=8'h01; lane_a_ev[51]=8'h00; lane_a_ev[52]=8'h00; lane_a_ev[53]=8'h30; lane_a_ev[54]=8'h39; lane_a_ev[55]=8'h97;
        lane_a_ev[56]=8'h8b; lane_a_ev[57]=8'h21; lane_a_ev[58]=8'h5e; lane_a_ev[59]=8'hea; lane_a_ev[60]=8'h9a; lane_a_ev[61]=8'h79; lane_a_ev[62]=8'ha0; lane_a_ev[63]=8'h94;
        lane_a_ev[64]=8'h10; lane_a_ev[65]=8'h9b; lane_a_ev[66]=8'h6f; lane_a_ev[67]=8'hd6; lane_a_ev[68]=8'h5a; lane_a_ev[69]=8'ha9; lane_a_ev[70]=8'hd8; lane_a_ev[71]=8'h42;
        lane_a_ev[72]=8'h1a; lane_a_ev[73]=8'ha5; lane_a_ev[74]=8'h52; lane_a_ev[75]=8'h15; lane_a_ev[76]=8'hd2; lane_a_ev[77]=8'hfb; lane_a_ev[78]=8'h01; lane_a_ev[79]=8'h00;
        lane_a_ev[80]=8'h00; lane_a_ev[81]=8'h30; lane_a_ev[82]=8'h39; lane_a_ev[83]=8'h97; lane_a_ev[84]=8'h8b; lane_a_ev[85]=8'h21; lane_a_ev[86]=8'h5e; lane_a_ev[87]=8'hea;
        lane_a_ev[88]=8'h9a; lane_a_ev[89]=8'h79; lane_a_ev[90]=8'ha0; lane_a_ev[91]=8'h94; lane_a_ev[92]=8'h10; lane_a_ev[93]=8'h9b; lane_a_ev[94]=8'h6f; lane_a_ev[95]=8'hd6;
        lane_a_ev[96]=8'h5f; lane_a_ev[97]=8'h37; lane_a_ev[98]=8'he6; lane_a_ev[99]=8'h47; lane_a_ev[100]=8'h01; lane_a_ev[101]=8'h00; lane_a_ev[102]=8'h47; lane_a_ev[103]=8'h01;
        lane_a_ev[104]=8'h05; lane_a_ev[105]=8'h42; lane_a_ev[106]=8'h1a; lane_a_ev[107]=8'ha5; lane_a_ev[108]=8'h52; lane_a_ev[109]=8'h15; lane_a_ev[110]=8'hb8; lane_a_ev[111]=8'hff;
        lane_a_ev[112]=8'h01; lane_a_ev[113]=8'h00; lane_a_ev[114]=8'h00; lane_a_ev[115]=8'h30; lane_a_ev[116]=8'h01; lane_a_ev[117]=8'he8; lane_a_ev[118]=8'hd6; lane_a_ev[119]=8'h78;
        lane_a_ev[120]=8'h42; lane_a_ev[121]=8'h8d; lane_a_ev[122]=8'h3b; lane_a_ev[123]=8'h31; lane_a_ev[124]=8'hfe; lane_a_ev[125]=8'hb7; lane_a_ev[126]=8'h78; lane_a_ev[127]=8'h8a;
        lane_a_ev[128]=8'h2e; lane_a_ev[129]=8'hbd; lane_a_ev[130]=8'h46; lane_a_ev[131]=8'hbf; lane_a_ev[132]=8'h79; lane_a_ev[133]=8'h47; lane_a_ev[134]=8'h01; lane_a_ev[135]=8'h00;
        lane_a_ev[136]=8'h47; lane_a_ev[137]=8'h01; lane_a_ev[138]=8'h01; lane_a_ev[139]=8'h42; lane_a_ev[140]=8'h1a; lane_a_ev[141]=8'ha5; lane_a_ev[142]=8'h52; lane_a_ev[143]=8'h15;
        lane_a_ev[144]=8'h58; lane_a_ev[145]=8'h0f; lane_a_ev[146]=8'h02; lane_a_ev[147]=8'h00; lane_a_ev[148]=8'h00; lane_a_ev[149]=8'h30; lane_a_ev[150]=8'hb1; lane_a_ev[151]=8'hc9;
        lane_a_ev[152]=8'heb; lane_a_ev[153]=8'h6d; lane_a_ev[154]=8'h65; lane_a_ev[155]=8'hba; lane_a_ev[156]=8'hcd; lane_a_ev[157]=8'h93; lane_a_ev[158]=8'h71; lane_a_ev[159]=8'hf6;
        lane_a_ev[160]=8'hef; lane_a_ev[161]=8'h22; lane_a_ev[162]=8'h08; lane_a_ev[163]=8'h25; lane_a_ev[164]=8'h14; lane_a_ev[165]=8'hb6; lane_a_ev[166]=8'he3; lane_a_ev[167]=8'h47;
        lane_a_ev[168]=8'h01; lane_a_ev[169]=8'h00; lane_a_ev[170]=8'h42; lane_a_ev[171]=8'h09; lane_a_ev[172]=8'ha5; lane_a_ev[173]=8'h54; lane_a_ev[174]=8'h04; lane_a_ev[175]=8'h40;
        lane_a_ev[176]=8'h13; lane_a_ev[177]=8'h06; lane_a_ev[178]=8'h00; lane_a_ev[179]=8'hee; lane_a_ev[180]=8'he3; lane_a_ev[181]=8'h42; lane_a_ev[182]=8'h05; lane_a_ev[183]=8'ha5;
        lane_a_ev[184]=8'h51; lane_a_ev[185]=8'h00; lane_a_ev[186]=8'h81; lane_a_ev[187]=8'h20;
        lane_a_rec[0]=64'h56000011fa003c7b; lane_a_pin[0]=8'h10;
        lane_a_rec[1]=64'h4100db5f9a6a8fdf; lane_a_pin[1]=8'hff;
        lane_a_rec[2]=64'h56010231ee023655; lane_a_pin[2]=8'h30;
        lane_a_rec[3]=64'h4101dcf299bcd625; lane_a_pin[3]=8'hff;
        lane_a_rec[4]=64'h560201170000a107; lane_a_pin[4]=8'h20;
        lane_a_rec[5]=64'h41022063a5704a0c; lane_a_pin[5]=8'hff;
        lane_a_rec[6]=64'h450154010000aa05; lane_a_pin[6]=8'hff;
        lane_a_rec[7]=64'h510300000100c7e6; lane_a_pin[7]=8'hff;
        lane_b_ev[0]=8'h42; lane_b_ev[1]=8'h15; lane_b_ev[2]=8'ha5; lane_b_ev[3]=8'h4b; lane_b_ev[4]=8'h10; lane_b_ev[5]=8'h52; lane_b_ev[6]=8'h56; lane_b_ev[7]=8'h42;
        lane_b_ev[8]=8'h4c; lane_b_ev[9]=8'h2d; lane_b_ev[10]=8'h32; lane_b_ev[11]=8'h20; lane_b_ev[12]=8'h6c; lane_b_ev[13]=8'h61; lane_b_ev[14]=8'h6e; lane_b_ev[15]=8'h65;
        lane_b_ev[16]=8'h20; lane_b_ev[17]=8'h6b; lane_b_ev[18]=8'h65; lane_b_ev[19]=8'h79; lane_b_ev[20]=8'h21; lane_b_ev[21]=8'h34; lane_b_ev[22]=8'h3b; lane_b_ev[23]=8'h42;
        lane_b_ev[24]=8'h0f; lane_b_ev[25]=8'ha5; lane_b_ev[26]=8'h50; lane_b_ev[27]=8'h0a; lane_b_ev[28]=8'h1e; lane_b_ev[29]=8'hf4; lane_b_ev[30]=8'h01; lane_b_ev[31]=8'hb8;
        lane_b_ev[32]=8'h0b; lane_b_ev[33]=8'hfa; lane_b_ev[34]=8'h00; lane_b_ev[35]=8'h08; lane_b_ev[36]=8'h30; lane_b_ev[37]=8'h00; lane_b_ev[38]=8'h54; lane_b_ev[39]=8'h79;
        lane_b_ev[40]=8'h42; lane_b_ev[41]=8'h08; lane_b_ev[42]=8'ha5; lane_b_ev[43]=8'h47; lane_b_ev[44]=8'h03; lane_b_ev[45]=8'h02; lane_b_ev[46]=8'h90; lane_b_ev[47]=8'h01;
        lane_b_ev[48]=8'hc6; lane_b_ev[49]=8'h9a; lane_b_ev[50]=8'h42; lane_b_ev[51]=8'h12; lane_b_ev[52]=8'ha5; lane_b_ev[53]=8'h48; lane_b_ev[54]=8'h0d; lane_b_ev[55]=8'hd1;
        lane_b_ev[56]=8'h8c; lane_b_ev[57]=8'h79; lane_b_ev[58]=8'h65; lane_b_ev[59]=8'ha3; lane_b_ev[60]=8'hdc; lane_b_ev[61]=8'h26; lane_b_ev[62]=8'h3b; lane_b_ev[63]=8'ha2;
        lane_b_ev[64]=8'h26; lane_b_ev[65]=8'hde; lane_b_ev[66]=8'hed; lane_b_ev[67]=8'h01; lane_b_ev[68]=8'ha7; lane_b_ev[69]=8'h21; lane_b_ev[70]=8'h42; lane_b_ev[71]=8'h16;
        lane_b_ev[72]=8'ha5; lane_b_ev[73]=8'h53; lane_b_ev[74]=8'h11; lane_b_ev[75]=8'h82; lane_b_ev[76]=8'h63; lane_b_ev[77]=8'hbd; lane_b_ev[78]=8'h03; lane_b_ev[79]=8'hab;
        lane_b_ev[80]=8'hc6; lane_b_ev[81]=8'h10; lane_b_ev[82]=8'h28; lane_b_ev[83]=8'hc2; lane_b_ev[84]=8'hf5; lane_b_ev[85]=8'h97; lane_b_ev[86]=8'h0a; lane_b_ev[87]=8'h02;
        lane_b_ev[88]=8'ha0; lane_b_ev[89]=8'h86; lane_b_ev[90]=8'h01; lane_b_ev[91]=8'h00; lane_b_ev[92]=8'h49; lane_b_ev[93]=8'heb; lane_b_ev[94]=8'h47; lane_b_ev[95]=8'h01;
        lane_b_ev[96]=8'h01; lane_b_ev[97]=8'h42; lane_b_ev[98]=8'h1a; lane_b_ev[99]=8'ha5; lane_b_ev[100]=8'h52; lane_b_ev[101]=8'h15; lane_b_ev[102]=8'ha0; lane_b_ev[103]=8'h03;
        lane_b_ev[104]=8'h02; lane_b_ev[105]=8'h00; lane_b_ev[106]=8'h00; lane_b_ev[107]=8'h30; lane_b_ev[108]=8'hd1; lane_b_ev[109]=8'h8c; lane_b_ev[110]=8'h79; lane_b_ev[111]=8'h65;
        lane_b_ev[112]=8'ha3; lane_b_ev[113]=8'hdc; lane_b_ev[114]=8'h26; lane_b_ev[115]=8'h3b; lane_b_ev[116]=8'ha2; lane_b_ev[117]=8'h26; lane_b_ev[118]=8'hde; lane_b_ev[119]=8'hed;
        lane_b_ev[120]=8'hde; lane_b_ev[121]=8'h6d; lane_b_ev[122]=8'h50; lane_b_ev[123]=8'hc5; lane_b_ev[124]=8'hb9; lane_b_ev[125]=8'h47; lane_b_ev[126]=8'h01; lane_b_ev[127]=8'h00;
        lane_b_ev[128]=8'h47; lane_b_ev[129]=8'h01; lane_b_ev[130]=8'h03; lane_b_ev[131]=8'h42; lane_b_ev[132]=8'h1a; lane_b_ev[133]=8'ha5; lane_b_ev[134]=8'h52; lane_b_ev[135]=8'h15;
        lane_b_ev[136]=8'h88; lane_b_ev[137]=8'h07; lane_b_ev[138]=8'h02; lane_b_ev[139]=8'h00; lane_b_ev[140]=8'h00; lane_b_ev[141]=8'h30; lane_b_ev[142]=8'h82; lane_b_ev[143]=8'h63;
        lane_b_ev[144]=8'hbd; lane_b_ev[145]=8'h03; lane_b_ev[146]=8'hab; lane_b_ev[147]=8'hc6; lane_b_ev[148]=8'h10; lane_b_ev[149]=8'h28; lane_b_ev[150]=8'hc2; lane_b_ev[151]=8'hf5;
        lane_b_ev[152]=8'h97; lane_b_ev[153]=8'h0a; lane_b_ev[154]=8'h50; lane_b_ev[155]=8'h3a; lane_b_ev[156]=8'h50; lane_b_ev[157]=8'h7e; lane_b_ev[158]=8'hf9; lane_b_ev[159]=8'h47;
        lane_b_ev[160]=8'h01; lane_b_ev[161]=8'h00;
        lane_b_rec[0]=64'h560003110000ea1c; lane_b_pin[0]=8'h60;
        lane_b_rec[1]=64'h41009a976af1e269; lane_b_pin[1]=8'hff;
        lane_b_rec[2]=64'h560104220000637b; lane_b_pin[2]=8'h60;
        lane_b_rec[3]=64'h41013449e126f289; lane_b_pin[3]=8'hff;
        identity_ev[0]=8'h42; identity_ev[1]=8'h05; identity_ev[2]=8'ha5; identity_ev[3]=8'h49; identity_ev[4]=8'h00; identity_ev[5]=8'h5b; identity_ev[6]=8'haa; identity_ev[7]=8'h57;
        identity_ev[8]=8'h04; identity_ev[9]=8'h50; identity_ev[10]=8'hc3; identity_ev[11]=8'h00; identity_ev[12]=8'h00; identity_ev[13]=8'h42; identity_ev[14]=8'h15; identity_ev[15]=8'ha5;
        identity_ev[16]=8'h4b; identity_ev[17]=8'h10; identity_ev[18]=8'h52; identity_ev[19]=8'h56; identity_ev[20]=8'h42; identity_ev[21]=8'h4c; identity_ev[22]=8'h2d; identity_ev[23]=8'h32;
        identity_ev[24]=8'h20; identity_ev[25]=8'h6c; identity_ev[26]=8'h61; identity_ev[27]=8'h6e; identity_ev[28]=8'h65; identity_ev[29]=8'h20; identity_ev[30]=8'h6b; identity_ev[31]=8'h65;
        identity_ev[32]=8'h79; identity_ev[33]=8'h21; identity_ev[34]=8'h34; identity_ev[35]=8'h3b; identity_ev[36]=8'h42; identity_ev[37]=8'h0f; identity_ev[38]=8'ha5; identity_ev[39]=8'h50;
        identity_ev[40]=8'h0a; identity_ev[41]=8'h1e; identity_ev[42]=8'hf4; identity_ev[43]=8'h01; identity_ev[44]=8'hb8; identity_ev[45]=8'h0b; identity_ev[46]=8'hfa; identity_ev[47]=8'h00;
        identity_ev[48]=8'h08; identity_ev[49]=8'h30; identity_ev[50]=8'h00; identity_ev[51]=8'h54; identity_ev[52]=8'h79; identity_ev[53]=8'h47; identity_ev[54]=8'h01; identity_ev[55]=8'h01;
        identity_ev[56]=8'h42; identity_ev[57]=8'h1a; identity_ev[58]=8'ha5; identity_ev[59]=8'h52; identity_ev[60]=8'h15; identity_ev[61]=8'h70; identity_ev[62]=8'h0b; identity_ev[63]=8'h02;
        identity_ev[64]=8'h00; identity_ev[65]=8'h00; identity_ev[66]=8'h30; identity_ev[67]=8'h4c; identity_ev[68]=8'hc7; identity_ev[69]=8'h07; identity_ev[70]=8'hd2; identity_ev[71]=8'hdd;
        identity_ev[72]=8'h44; identity_ev[73]=8'h79; identity_ev[74]=8'h98; identity_ev[75]=8'hb8; identity_ev[76]=8'heb; identity_ev[77]=8'he0; identity_ev[78]=8'h63; identity_ev[79]=8'h8c;
        identity_ev[80]=8'h76; identity_ev[81]=8'h55; identity_ev[82]=8'he6; identity_ev[83]=8'hc3; identity_ev[84]=8'h47; identity_ev[85]=8'h01; identity_ev[86]=8'h00;
        identity_rec[0]=64'h4903d60a3ded21d5; identity_pin[0]=8'hff;
        identity_rec[1]=64'h5600001482003c11; identity_pin[1]=8'h10;
        identity_rec[2]=64'h41003d0c7fed4a75; identity_pin[2]=8'hff;
    end

    localparam integer N_EV  = (SCEN == 0) ? 188 : (SCEN == 1) ? 162 : 87;
    localparam integer N_REC = (SCEN == 0) ? 8 : (SCEN == 1) ? 4 : 3;
    function [7:0] ev_at(input integer i);
        case (SCEN)
            0: ev_at = lane_a_ev[i];
            1: ev_at = lane_b_ev[i];
            2: ev_at = identity_ev[i];
            default: ev_at = 8'h00;
        endcase
    endfunction
    function [63:0] rec_at(input integer i);
        case (SCEN)
            0: rec_at = lane_a_rec[i];
            1: rec_at = lane_b_rec[i];
            2: rec_at = identity_rec[i];
            default: rec_at = 64'h0;
        endcase
    endfunction
    function [7:0] pin_at(input integer i);
        case (SCEN)
            0: pin_at = lane_a_pin[i];
            1: pin_at = lane_b_pin[i];
            2: pin_at = identity_pin[i];
            default: pin_at = 8'hFF;
        endcase
    endfunction

    integer pass = 0, fail = 0;
    task chk(input ok, input [8*48-1:0] what);
        begin
            if (ok) pass = pass + 1;
            else begin fail = fail + 1; $display("FAIL %0s", what); end
        end
    endtask

    // receiver on tx_o: every 8 bytes is one record
    reg [63:0] got = 0;
    integer nb = 0, n_got = 0, ferr = 0, k;
    reg [7:0] b;
    always begin
        @(negedge tx);
        repeat (NB / 2) @(posedge clk);
        if (tx !== 1'b0) ferr = ferr + 1;
        for (k = 0; k < 8; k = k + 1) begin repeat (NB) @(posedge clk); b[k] = tx; end
        repeat (NB) @(posedge clk);
        if (tx !== 1'b1) ferr = ferr + 1;
        got = {got[55:0], b};
        nb = nb + 1;
        if (nb == 8) begin
            nb = 0;
            if (n_got >= N_REC) begin
                chk(0, "more records than the model");
                $display("REC %0d @%0d %h MISMATCH", n_got, cycles, got);
            end else begin
                chk(got === rec_at(n_got), "record equals the model's");
                $display("REC %0d @%0d %h %0s", n_got, cycles, got,
                         got === rec_at(n_got) ? "ok" : "MISMATCH");
            end
            n_got = n_got + 1;
        end
    end

    task send_byte(input [7:0] d);
        integer j;
        begin
            rx = 1'b0; repeat (NB) @(posedge clk);
            for (j = 0; j < 8; j = j + 1) begin rx = d[j]; repeat (NB) @(posedge clk); end
            rx = 1'b1; repeat (NB) @(posedge clk);
        end
    endtask

    integer i, j, len, vi = 0, vn = 0;
    reg [3:0] prev_in;
    reg [7:0] want;
    initial begin
        case (SCEN)
            0: $display("LANE LaneX toll lane controller on RVBL-2 SCEN=0 lane-a UART %0d clocks/bit", NB);
            1: $display("LANE LaneX toll lane controller on RVBL-2 SCEN=1 lane-b UART %0d clocks/bit", NB);
            2: $display("LANE LaneX toll lane controller on RVBL-2 SCEN=2 identity UART %0d clocks/bit", NB);
        endcase
        repeat (5) @(posedge clk);
        rst = 1'b0;
        repeat (2000) @(posedge clk);
        i = 0;
        while (i < N_EV) begin
            len = ev_at(i + 1);
            if (ev_at(i) == "W") begin
                repeat ({ev_at(i + 5), ev_at(i + 4), ev_at(i + 3), ev_at(i + 2)}) @(posedge clk);
            end else if (ev_at(i) == "G") begin
                prev_in = pin_in;
                pin_in = ev_at(i + 2);
                if (prev_in[0] && !pin_in[0]) repeat (SETTLE_FALL) @(posedge clk);
                else                          repeat (SETTLE_RISE) @(posedge clk);
                if (prev_in[0] && !pin_in[0]) begin    // a car has just left
                    while (vi < N_REC && pin_at(vi) == 8'hFF) vi = vi + 1;   // skip non-vehicle records
                    want = pin_at(vi) >> 4;
                    chk({4'b0000, p7, p6, p5, p4} === want, "pins 7:4 after a vehicle leaves");
                    $display("PINS %0d @%0d %b %0s", vn, cycles, {p7, p6, p5, p4},
                             {4'b0000, p7, p6, p5, p4} === want ? "ok" : "MISMATCH");
                    vi = vi + 1;
                    vn = vn + 1;
                end
            end else begin
                for (j = 0; j < len; j = j + 1) send_byte(ev_at(i + 2 + j));
                if (ev_at(i) == "B") repeat (GAP) @(posedge clk);
            end
            i = i + 2 + len;
        end
        repeat (40 * 10 * NB) @(posedge clk);
        chk(n_got == N_REC, "record count equals the model's");
        chk(ferr == 0, "no framing errors on tx_o");
        $display("==== tb_app_ci (scenario %0d): %0d passed, %0d failed, %0d cycles ====",
                 SCEN, pass, fail, cycles);
        if (fail == 0) $display("TB_APP_CI: ALL TESTS PASSED");
        else           $display("TB_APP_CI: FAILURES PRESENT");
        $finish;
    end
endmodule
