`timescale 1ns/1ps
// ============================================================================
// tb_app_ci.v - GENERATED by application/testbench/gen_platform_tb.py; do not edit.
//
// The Stage 3 application (the free-flow toll lane controller) on the canvas
// chip `top`, checked against the golden model (application/testbench/lane_model.py).
// Use it with the APPLICATION ROM: paste chipinventor/app/imem_app.v into the
// imem block's Code field (the validation ROM stays in chipinventor/blocks/).
//
// Plays a scenario - frames into rx_i, vehicle presence / class / lane-closed
// on pins 3:0 - and prints every 8-byte record the chip sends on tx_o, as it
// arrives, with the model's verdict:
//     REC <n> @<cycle> <record, 16 hex digits> ok|MISMATCH
//     PINS <vehicle> @<cycle> <p7 p6 p5 p4> ok|MISMATCH
// Paste the log into the replay page to watch the chip's decisions; the page
// decodes those bytes and checks every CRC and Chaskey-12 tag itself.
//
// Set SCEN (below) to choose the run:
//   0  showcase  the demo: 'I', key, seven vehicles, one of each outcome, each
//                authenticated; an 'E'; stats
//   1  smoke     six vehicles, one of each main outcome, no key
// Pass: "TB_APP_CI: ALL TESTS PASSED".
// ============================================================================
module testbench;   // the platform runs the module named testbench
    parameter SCEN = 0;
    localparam integer NB = 263;              // clocks per bit: 30.303 MHz / 115200
    localparam integer GAP = 20 * NB;        // idle after each frame
    localparam integer SETTLE_RISE = 2000;   // after a car arrives
    localparam integer SETTLE_FALL = 16000;  // after it leaves (> the whole decision)

    reg clk = 0, rst = 1;
    always #16.5 clk = ~clk;
    integer cycles = 0;
    always @(posedge clk) cycles = cycles + 1;

    reg  [3:0] pin_in = 4'h0;
    reg        rx = 1'b1;
    wire       tx;
    wire p0, p1, p2, p3, p4, p5, p6, p7;
    assign p0 = pin_in[0];
    assign p1 = pin_in[1];
    assign p2 = pin_in[2];
    assign p3 = pin_in[3];
    assign (weak0, weak1) p4 = 1'b0;
    assign (weak0, weak1) p5 = 1'b0;
    assign (weak0, weak1) p6 = 1'b0;
    assign (weak0, weak1) p7 = 1'b0;

    top dut (
        .clk_i(clk), .rst_i(rst),
        .pins_io_0(p0), .pins_io_1(p1), .pins_io_2(p2), .pins_io_3(p3),
        .pins_io_4(p4), .pins_io_5(p5), .pins_io_6(p6), .pins_io_7(p7),
        .tx_o(tx), .rx_i(rx));

    // ---- scenario showcase: 395 event bytes, 17 records ----
    reg [7:0]  showcase_ev  [0:394];
    reg [63:0] showcase_rec [0:16];
    reg [7:0]  showcase_pin [0:16];

    // ---- scenario smoke: 241 event bytes, 6 records ----
    reg [7:0]  smoke_ev  [0:240];
    reg [63:0] smoke_rec [0:5];
    reg [7:0]  smoke_pin [0:5];

    initial begin
        showcase_ev[0]=8'h42; showcase_ev[1]=8'h05; showcase_ev[2]=8'ha5; showcase_ev[3]=8'h49; showcase_ev[4]=8'h00; showcase_ev[5]=8'h5b; showcase_ev[6]=8'haa; showcase_ev[7]=8'h57;
        showcase_ev[8]=8'h04; showcase_ev[9]=8'h70; showcase_ev[10]=8'h11; showcase_ev[11]=8'h01; showcase_ev[12]=8'h00; showcase_ev[13]=8'h42; showcase_ev[14]=8'h15; showcase_ev[15]=8'ha5;
        showcase_ev[16]=8'h4b; showcase_ev[17]=8'h10; showcase_ev[18]=8'h52; showcase_ev[19]=8'h56; showcase_ev[20]=8'h42; showcase_ev[21]=8'h4c; showcase_ev[22]=8'h2d; showcase_ev[23]=8'h32;
        showcase_ev[24]=8'h20; showcase_ev[25]=8'h6c; showcase_ev[26]=8'h61; showcase_ev[27]=8'h6e; showcase_ev[28]=8'h65; showcase_ev[29]=8'h20; showcase_ev[30]=8'h6b; showcase_ev[31]=8'h65;
        showcase_ev[32]=8'h79; showcase_ev[33]=8'h21; showcase_ev[34]=8'h34; showcase_ev[35]=8'h3b; showcase_ev[36]=8'h42; showcase_ev[37]=8'h0f; showcase_ev[38]=8'ha5; showcase_ev[39]=8'h50;
        showcase_ev[40]=8'h0a; showcase_ev[41]=8'h1e; showcase_ev[42]=8'hf4; showcase_ev[43]=8'h01; showcase_ev[44]=8'hb8; showcase_ev[45]=8'h0b; showcase_ev[46]=8'hfa; showcase_ev[47]=8'h00;
        showcase_ev[48]=8'h40; showcase_ev[49]=8'h30; showcase_ev[50]=8'h00; showcase_ev[51]=8'h58; showcase_ev[52]=8'hcd; showcase_ev[53]=8'h42; showcase_ev[54]=8'h13; showcase_ev[55]=8'ha5;
        showcase_ev[56]=8'h43; showcase_ev[57]=8'h0e; showcase_ev[58]=8'h01; showcase_ev[59]=8'h00; showcase_ev[60]=8'h00; showcase_ev[61]=8'h00; showcase_ev[62]=8'hfa; showcase_ev[63]=8'h00;
        showcase_ev[64]=8'hf4; showcase_ev[65]=8'h01; showcase_ev[66]=8'hee; showcase_ev[67]=8'h02; showcase_ev[68]=8'h82; showcase_ev[69]=8'h00; showcase_ev[70]=8'h7c; showcase_ev[71]=8'h01;
        showcase_ev[72]=8'h88; showcase_ev[73]=8'hf3; showcase_ev[74]=8'h42; showcase_ev[75]=8'h08; showcase_ev[76]=8'ha5; showcase_ev[77]=8'h47; showcase_ev[78]=8'h03; showcase_ev[79]=8'h02;
        showcase_ev[80]=8'h90; showcase_ev[81]=8'h01; showcase_ev[82]=8'hc6; showcase_ev[83]=8'h9a; showcase_ev[84]=8'h42; showcase_ev[85]=8'h12; showcase_ev[86]=8'ha5; showcase_ev[87]=8'h48;
        showcase_ev[88]=8'h0d; showcase_ev[89]=8'hd1; showcase_ev[90]=8'h8c; showcase_ev[91]=8'h79; showcase_ev[92]=8'h65; showcase_ev[93]=8'ha3; showcase_ev[94]=8'hdc; showcase_ev[95]=8'h26;
        showcase_ev[96]=8'h3b; showcase_ev[97]=8'ha2; showcase_ev[98]=8'h26; showcase_ev[99]=8'hde; showcase_ev[100]=8'hed; showcase_ev[101]=8'h01; showcase_ev[102]=8'ha7; showcase_ev[103]=8'h21;
        showcase_ev[104]=8'h42; showcase_ev[105]=8'h16; showcase_ev[106]=8'ha5; showcase_ev[107]=8'h53; showcase_ev[108]=8'h11; showcase_ev[109]=8'h82; showcase_ev[110]=8'h63; showcase_ev[111]=8'hbd;
        showcase_ev[112]=8'h03; showcase_ev[113]=8'hab; showcase_ev[114]=8'hc6; showcase_ev[115]=8'h10; showcase_ev[116]=8'h28; showcase_ev[117]=8'hc2; showcase_ev[118]=8'hf5; showcase_ev[119]=8'h97;
        showcase_ev[120]=8'h0a; showcase_ev[121]=8'h02; showcase_ev[122]=8'ha0; showcase_ev[123]=8'h86; showcase_ev[124]=8'h01; showcase_ev[125]=8'h00; showcase_ev[126]=8'h49; showcase_ev[127]=8'heb;
        showcase_ev[128]=8'h42; showcase_ev[129]=8'h09; showcase_ev[130]=8'ha5; showcase_ev[131]=8'h54; showcase_ev[132]=8'h04; showcase_ev[133]=8'hd0; showcase_ev[134]=8'hfb; showcase_ev[135]=8'h01;
        showcase_ev[136]=8'h00; showcase_ev[137]=8'hb2; showcase_ev[138]=8'h79; showcase_ev[139]=8'h47; showcase_ev[140]=8'h01; showcase_ev[141]=8'h01; showcase_ev[142]=8'h42; showcase_ev[143]=8'h1a;
        showcase_ev[144]=8'ha5; showcase_ev[145]=8'h52; showcase_ev[146]=8'h15; showcase_ev[147]=8'hd1; showcase_ev[148]=8'hfb; showcase_ev[149]=8'h01; showcase_ev[150]=8'h00; showcase_ev[151]=8'h00;
        showcase_ev[152]=8'h30; showcase_ev[153]=8'h39; showcase_ev[154]=8'h97; showcase_ev[155]=8'h8b; showcase_ev[156]=8'h21; showcase_ev[157]=8'h5e; showcase_ev[158]=8'hea; showcase_ev[159]=8'h9a;
        showcase_ev[160]=8'h79; showcase_ev[161]=8'ha0; showcase_ev[162]=8'h94; showcase_ev[163]=8'h10; showcase_ev[164]=8'h9b; showcase_ev[165]=8'h6f; showcase_ev[166]=8'hd6; showcase_ev[167]=8'h5a;
        showcase_ev[168]=8'ha9; showcase_ev[169]=8'hd8; showcase_ev[170]=8'h42; showcase_ev[171]=8'h1a; showcase_ev[172]=8'ha5; showcase_ev[173]=8'h52; showcase_ev[174]=8'h15; showcase_ev[175]=8'hd2;
        showcase_ev[176]=8'hfb; showcase_ev[177]=8'h01; showcase_ev[178]=8'h00; showcase_ev[179]=8'h00; showcase_ev[180]=8'h30; showcase_ev[181]=8'h39; showcase_ev[182]=8'h97; showcase_ev[183]=8'h8b;
        showcase_ev[184]=8'h21; showcase_ev[185]=8'h5e; showcase_ev[186]=8'hea; showcase_ev[187]=8'h9a; showcase_ev[188]=8'h79; showcase_ev[189]=8'ha0; showcase_ev[190]=8'h94; showcase_ev[191]=8'h10;
        showcase_ev[192]=8'h9b; showcase_ev[193]=8'h6f; showcase_ev[194]=8'hd6; showcase_ev[195]=8'h5f; showcase_ev[196]=8'h37; showcase_ev[197]=8'he6; showcase_ev[198]=8'h47; showcase_ev[199]=8'h01;
        showcase_ev[200]=8'h00; showcase_ev[201]=8'h47; showcase_ev[202]=8'h01; showcase_ev[203]=8'h05; showcase_ev[204]=8'h42; showcase_ev[205]=8'h1a; showcase_ev[206]=8'ha5; showcase_ev[207]=8'h52;
        showcase_ev[208]=8'h15; showcase_ev[209]=8'hb8; showcase_ev[210]=8'hff; showcase_ev[211]=8'h01; showcase_ev[212]=8'h00; showcase_ev[213]=8'h00; showcase_ev[214]=8'h30; showcase_ev[215]=8'h01;
        showcase_ev[216]=8'he8; showcase_ev[217]=8'hd6; showcase_ev[218]=8'h78; showcase_ev[219]=8'h42; showcase_ev[220]=8'h8d; showcase_ev[221]=8'h3b; showcase_ev[222]=8'h31; showcase_ev[223]=8'hfe;
        showcase_ev[224]=8'hb7; showcase_ev[225]=8'h78; showcase_ev[226]=8'h8a; showcase_ev[227]=8'h2e; showcase_ev[228]=8'hbd; showcase_ev[229]=8'h46; showcase_ev[230]=8'hbf; showcase_ev[231]=8'h79;
        showcase_ev[232]=8'h47; showcase_ev[233]=8'h01; showcase_ev[234]=8'h00; showcase_ev[235]=8'h47; showcase_ev[236]=8'h01; showcase_ev[237]=8'h01; showcase_ev[238]=8'h42; showcase_ev[239]=8'h1a;
        showcase_ev[240]=8'ha5; showcase_ev[241]=8'h52; showcase_ev[242]=8'h15; showcase_ev[243]=8'ha0; showcase_ev[244]=8'h03; showcase_ev[245]=8'h02; showcase_ev[246]=8'h00; showcase_ev[247]=8'h00;
        showcase_ev[248]=8'h30; showcase_ev[249]=8'hd1; showcase_ev[250]=8'h8c; showcase_ev[251]=8'h79; showcase_ev[252]=8'h65; showcase_ev[253]=8'ha3; showcase_ev[254]=8'hdc; showcase_ev[255]=8'h26;
        showcase_ev[256]=8'h3b; showcase_ev[257]=8'ha2; showcase_ev[258]=8'h26; showcase_ev[259]=8'hde; showcase_ev[260]=8'hed; showcase_ev[261]=8'hde; showcase_ev[262]=8'h6d; showcase_ev[263]=8'h50;
        showcase_ev[264]=8'hc5; showcase_ev[265]=8'hb9; showcase_ev[266]=8'h47; showcase_ev[267]=8'h01; showcase_ev[268]=8'h00; showcase_ev[269]=8'h47; showcase_ev[270]=8'h01; showcase_ev[271]=8'h03;
        showcase_ev[272]=8'h42; showcase_ev[273]=8'h1a; showcase_ev[274]=8'ha5; showcase_ev[275]=8'h52; showcase_ev[276]=8'h15; showcase_ev[277]=8'h88; showcase_ev[278]=8'h07; showcase_ev[279]=8'h02;
        showcase_ev[280]=8'h00; showcase_ev[281]=8'h00; showcase_ev[282]=8'h30; showcase_ev[283]=8'h82; showcase_ev[284]=8'h63; showcase_ev[285]=8'hbd; showcase_ev[286]=8'h03; showcase_ev[287]=8'hab;
        showcase_ev[288]=8'hc6; showcase_ev[289]=8'h10; showcase_ev[290]=8'h28; showcase_ev[291]=8'hc2; showcase_ev[292]=8'hf5; showcase_ev[293]=8'h97; showcase_ev[294]=8'h0a; showcase_ev[295]=8'h50;
        showcase_ev[296]=8'h3a; showcase_ev[297]=8'h50; showcase_ev[298]=8'h7e; showcase_ev[299]=8'hf9; showcase_ev[300]=8'h47; showcase_ev[301]=8'h01; showcase_ev[302]=8'h00; showcase_ev[303]=8'h47;
        showcase_ev[304]=8'h01; showcase_ev[305]=8'h01; showcase_ev[306]=8'h42; showcase_ev[307]=8'h1a; showcase_ev[308]=8'ha5; showcase_ev[309]=8'h52; showcase_ev[310]=8'h15; showcase_ev[311]=8'h70;
        showcase_ev[312]=8'h0b; showcase_ev[313]=8'h02; showcase_ev[314]=8'h00; showcase_ev[315]=8'h00; showcase_ev[316]=8'h30; showcase_ev[317]=8'h4c; showcase_ev[318]=8'hc7; showcase_ev[319]=8'h07;
        showcase_ev[320]=8'hd2; showcase_ev[321]=8'hdd; showcase_ev[322]=8'h44; showcase_ev[323]=8'h79; showcase_ev[324]=8'h98; showcase_ev[325]=8'hb8; showcase_ev[326]=8'heb; showcase_ev[327]=8'he0;
        showcase_ev[328]=8'h63; showcase_ev[329]=8'h8c; showcase_ev[330]=8'h76; showcase_ev[331]=8'h55; showcase_ev[332]=8'he6; showcase_ev[333]=8'hc3; showcase_ev[334]=8'h47; showcase_ev[335]=8'h01;
        showcase_ev[336]=8'h00; showcase_ev[337]=8'h47; showcase_ev[338]=8'h01; showcase_ev[339]=8'h01; showcase_ev[340]=8'h42; showcase_ev[341]=8'h1a; showcase_ev[342]=8'ha5; showcase_ev[343]=8'h52;
        showcase_ev[344]=8'h15; showcase_ev[345]=8'h58; showcase_ev[346]=8'h0f; showcase_ev[347]=8'h02; showcase_ev[348]=8'h00; showcase_ev[349]=8'h00; showcase_ev[350]=8'h30; showcase_ev[351]=8'hb1;
        showcase_ev[352]=8'hc9; showcase_ev[353]=8'heb; showcase_ev[354]=8'h6d; showcase_ev[355]=8'h65; showcase_ev[356]=8'hba; showcase_ev[357]=8'hcd; showcase_ev[358]=8'h93; showcase_ev[359]=8'h71;
        showcase_ev[360]=8'hf6; showcase_ev[361]=8'hef; showcase_ev[362]=8'h22; showcase_ev[363]=8'h08; showcase_ev[364]=8'h25; showcase_ev[365]=8'h14; showcase_ev[366]=8'hb6; showcase_ev[367]=8'he3;
        showcase_ev[368]=8'h47; showcase_ev[369]=8'h01; showcase_ev[370]=8'h00; showcase_ev[371]=8'h47; showcase_ev[372]=8'h01; showcase_ev[373]=8'h07; showcase_ev[374]=8'h47; showcase_ev[375]=8'h01;
        showcase_ev[376]=8'h00; showcase_ev[377]=8'h42; showcase_ev[378]=8'h09; showcase_ev[379]=8'ha5; showcase_ev[380]=8'h54; showcase_ev[381]=8'h04; showcase_ev[382]=8'h40; showcase_ev[383]=8'h13;
        showcase_ev[384]=8'h06; showcase_ev[385]=8'h00; showcase_ev[386]=8'hee; showcase_ev[387]=8'he3; showcase_ev[388]=8'h42; showcase_ev[389]=8'h05; showcase_ev[390]=8'ha5; showcase_ev[391]=8'h51;
        showcase_ev[392]=8'h00; showcase_ev[393]=8'h81; showcase_ev[394]=8'h20;
        showcase_rec[0]=64'h4903d60a3ded21d5; showcase_pin[0]=8'hff;
        showcase_rec[1]=64'h56000011fa003c7b; showcase_pin[1]=8'h10;
        showcase_rec[2]=64'h4100db5f9a6a8fdf; showcase_pin[2]=8'hff;
        showcase_rec[3]=64'h56010231ee023655; showcase_pin[3]=8'h30;
        showcase_rec[4]=64'h4101dcf299bcd625; showcase_pin[4]=8'hff;
        showcase_rec[5]=64'h5602031100006958; showcase_pin[5]=8'h60;
        showcase_rec[6]=64'h41025d622b4fa2bf; showcase_pin[6]=8'hff;
        showcase_rec[7]=64'h560304220000e03f; showcase_pin[7]=8'h60;
        showcase_rec[8]=64'h4103cf384b642839; showcase_pin[8]=8'hff;
        showcase_rec[9]=64'h5604001482003a98; showcase_pin[9]=8'h10;
        showcase_rec[10]=64'h4104dbd539c3fcc6; showcase_pin[10]=8'hff;
        showcase_rec[11]=64'h5605011700007560; showcase_pin[11]=8'h20;
        showcase_rec[12]=64'h410553d2e3ddd5b8; showcase_pin[12]=8'hff;
        showcase_rec[13]=64'h5606050700003507; showcase_pin[13]=8'h00;
        showcase_rec[14]=64'h410670ce962e47e4; showcase_pin[14]=8'hff;
        showcase_rec[15]=64'h450154010000aa05; showcase_pin[15]=8'hff;
        showcase_rec[16]=64'h510700000101e07f; showcase_pin[16]=8'hff;
        smoke_ev[0]=8'h42; smoke_ev[1]=8'h08; smoke_ev[2]=8'ha5; smoke_ev[3]=8'h47; smoke_ev[4]=8'h03; smoke_ev[5]=8'h02; smoke_ev[6]=8'h90; smoke_ev[7]=8'h01;
        smoke_ev[8]=8'hc6; smoke_ev[9]=8'h9a; smoke_ev[10]=8'h42; smoke_ev[11]=8'h12; smoke_ev[12]=8'ha5; smoke_ev[13]=8'h48; smoke_ev[14]=8'h0d; smoke_ev[15]=8'h11;
        smoke_ev[16]=8'h89; smoke_ev[17]=8'hcf; smoke_ev[18]=8'he3; smoke_ev[19]=8'hb1; smoke_ev[20]=8'ha2; smoke_ev[21]=8'h0a; smoke_ev[22]=8'h98; smoke_ev[23]=8'hfb;
        smoke_ev[24]=8'h65; smoke_ev[25]=8'hf6; smoke_ev[26]=8'h73; smoke_ev[27]=8'h01; smoke_ev[28]=8'hb8; smoke_ev[29]=8'h24; smoke_ev[30]=8'h42; smoke_ev[31]=8'h16;
        smoke_ev[32]=8'ha5; smoke_ev[33]=8'h53; smoke_ev[34]=8'h11; smoke_ev[35]=8'ha2; smoke_ev[36]=8'hbd; smoke_ev[37]=8'h9d; smoke_ev[38]=8'ha6; smoke_ev[39]=8'h28;
        smoke_ev[40]=8'h9f; smoke_ev[41]=8'h03; smoke_ev[42]=8'hd4; smoke_ev[43]=8'h87; smoke_ev[44]=8'h10; smoke_ev[45]=8'h0f; smoke_ev[46]=8'h09; smoke_ev[47]=8'h02;
        smoke_ev[48]=8'ha0; smoke_ev[49]=8'h86; smoke_ev[50]=8'h01; smoke_ev[51]=8'h00; smoke_ev[52]=8'hde; smoke_ev[53]=8'hd8; smoke_ev[54]=8'h42; smoke_ev[55]=8'h09;
        smoke_ev[56]=8'ha5; smoke_ev[57]=8'h54; smoke_ev[58]=8'h04; smoke_ev[59]=8'hd0; smoke_ev[60]=8'hfb; smoke_ev[61]=8'h01; smoke_ev[62]=8'h00; smoke_ev[63]=8'hb2;
        smoke_ev[64]=8'h79; smoke_ev[65]=8'h47; smoke_ev[66]=8'h01; smoke_ev[67]=8'h01; smoke_ev[68]=8'h42; smoke_ev[69]=8'h1a; smoke_ev[70]=8'ha5; smoke_ev[71]=8'h52;
        smoke_ev[72]=8'h15; smoke_ev[73]=8'hd1; smoke_ev[74]=8'hfb; smoke_ev[75]=8'h01; smoke_ev[76]=8'h00; smoke_ev[77]=8'h00; smoke_ev[78]=8'h30; smoke_ev[79]=8'h71;
        smoke_ev[80]=8'hdd; smoke_ev[81]=8'h8f; smoke_ev[82]=8'hdb; smoke_ev[83]=8'hec; smoke_ev[84]=8'hc7; smoke_ev[85]=8'h77; smoke_ev[86]=8'h73; smoke_ev[87]=8'h82;
        smoke_ev[88]=8'hda; smoke_ev[89]=8'h96; smoke_ev[90]=8'h30; smoke_ev[91]=8'h4c; smoke_ev[92]=8'h5a; smoke_ev[93]=8'h5a; smoke_ev[94]=8'h44; smoke_ev[95]=8'h44;
        smoke_ev[96]=8'h42; smoke_ev[97]=8'h1a; smoke_ev[98]=8'ha5; smoke_ev[99]=8'h52; smoke_ev[100]=8'h15; smoke_ev[101]=8'hd2; smoke_ev[102]=8'hfb; smoke_ev[103]=8'h01;
        smoke_ev[104]=8'h00; smoke_ev[105]=8'h00; smoke_ev[106]=8'h30; smoke_ev[107]=8'h71; smoke_ev[108]=8'hdd; smoke_ev[109]=8'h8f; smoke_ev[110]=8'hdb; smoke_ev[111]=8'hec;
        smoke_ev[112]=8'hc7; smoke_ev[113]=8'h77; smoke_ev[114]=8'h73; smoke_ev[115]=8'h82; smoke_ev[116]=8'hda; smoke_ev[117]=8'h96; smoke_ev[118]=8'h30; smoke_ev[119]=8'h4c;
        smoke_ev[120]=8'h5a; smoke_ev[121]=8'h5f; smoke_ev[122]=8'hda; smoke_ev[123]=8'h7a; smoke_ev[124]=8'h47; smoke_ev[125]=8'h01; smoke_ev[126]=8'h00; smoke_ev[127]=8'h47;
        smoke_ev[128]=8'h01; smoke_ev[129]=8'h05; smoke_ev[130]=8'h42; smoke_ev[131]=8'h1a; smoke_ev[132]=8'ha5; smoke_ev[133]=8'h52; smoke_ev[134]=8'h15; smoke_ev[135]=8'hb8;
        smoke_ev[136]=8'hff; smoke_ev[137]=8'h01; smoke_ev[138]=8'h00; smoke_ev[139]=8'h00; smoke_ev[140]=8'h30; smoke_ev[141]=8'h29; smoke_ev[142]=8'hcd; smoke_ev[143]=8'h83;
        smoke_ev[144]=8'h79; smoke_ev[145]=8'ha1; smoke_ev[146]=8'h9d; smoke_ev[147]=8'hcb; smoke_ev[148]=8'h2f; smoke_ev[149]=8'h18; smoke_ev[150]=8'h72; smoke_ev[151]=8'h4d;
        smoke_ev[152]=8'h24; smoke_ev[153]=8'hc4; smoke_ev[154]=8'h31; smoke_ev[155]=8'h46; smoke_ev[156]=8'hf8; smoke_ev[157]=8'hf1; smoke_ev[158]=8'h47; smoke_ev[159]=8'h01;
        smoke_ev[160]=8'h00; smoke_ev[161]=8'h47; smoke_ev[162]=8'h01; smoke_ev[163]=8'h01; smoke_ev[164]=8'h42; smoke_ev[165]=8'h1a; smoke_ev[166]=8'ha5; smoke_ev[167]=8'h52;
        smoke_ev[168]=8'h15; smoke_ev[169]=8'ha0; smoke_ev[170]=8'h03; smoke_ev[171]=8'h02; smoke_ev[172]=8'h00; smoke_ev[173]=8'h00; smoke_ev[174]=8'h30; smoke_ev[175]=8'h11;
        smoke_ev[176]=8'h89; smoke_ev[177]=8'hcf; smoke_ev[178]=8'he3; smoke_ev[179]=8'hb1; smoke_ev[180]=8'ha2; smoke_ev[181]=8'h0a; smoke_ev[182]=8'h98; smoke_ev[183]=8'hfb;
        smoke_ev[184]=8'h65; smoke_ev[185]=8'hf6; smoke_ev[186]=8'h73; smoke_ev[187]=8'h34; smoke_ev[188]=8'h9d; smoke_ev[189]=8'h50; smoke_ev[190]=8'hdf; smoke_ev[191]=8'hd1;
        smoke_ev[192]=8'h47; smoke_ev[193]=8'h01; smoke_ev[194]=8'h00; smoke_ev[195]=8'h47; smoke_ev[196]=8'h01; smoke_ev[197]=8'h03; smoke_ev[198]=8'h42; smoke_ev[199]=8'h1a;
        smoke_ev[200]=8'ha5; smoke_ev[201]=8'h52; smoke_ev[202]=8'h15; smoke_ev[203]=8'h88; smoke_ev[204]=8'h07; smoke_ev[205]=8'h02; smoke_ev[206]=8'h00; smoke_ev[207]=8'h00;
        smoke_ev[208]=8'h30; smoke_ev[209]=8'ha2; smoke_ev[210]=8'hbd; smoke_ev[211]=8'h9d; smoke_ev[212]=8'ha6; smoke_ev[213]=8'h28; smoke_ev[214]=8'h9f; smoke_ev[215]=8'h03;
        smoke_ev[216]=8'hd4; smoke_ev[217]=8'h87; smoke_ev[218]=8'h10; smoke_ev[219]=8'h0f; smoke_ev[220]=8'h09; smoke_ev[221]=8'hc8; smoke_ev[222]=8'h65; smoke_ev[223]=8'h50;
        smoke_ev[224]=8'hda; smoke_ev[225]=8'hd5; smoke_ev[226]=8'h47; smoke_ev[227]=8'h01; smoke_ev[228]=8'h00; smoke_ev[229]=8'h47; smoke_ev[230]=8'h01; smoke_ev[231]=8'h01;
        smoke_ev[232]=8'h47; smoke_ev[233]=8'h01; smoke_ev[234]=8'h00; smoke_ev[235]=8'h47; smoke_ev[236]=8'h01; smoke_ev[237]=8'h07; smoke_ev[238]=8'h47; smoke_ev[239]=8'h01;
        smoke_ev[240]=8'h00;
        smoke_rec[0]=64'h56000011fa003c7b; smoke_pin[0]=8'h10;
        smoke_rec[1]=64'h56010231ee023655; smoke_pin[1]=8'h30;
        smoke_rec[2]=64'h5602031100006958; smoke_pin[2]=8'h60;
        smoke_rec[3]=64'h560304220000e03f; smoke_pin[3]=8'h60;
        smoke_rec[4]=64'h56040117000024ca; smoke_pin[4]=8'h20;
        smoke_rec[5]=64'h560505070000e7e9; smoke_pin[5]=8'h00;
    end

    localparam integer N_EV  = (SCEN == 0) ? 395 : 241;
    localparam integer N_REC = (SCEN == 0) ? 17 : 6;
    function [7:0] ev_at(input integer i);
        case (SCEN)
            0: ev_at = showcase_ev[i];
            1: ev_at = smoke_ev[i];
            default: ev_at = 8'h00;
        endcase
    endfunction
    function [63:0] rec_at(input integer i);
        case (SCEN)
            0: rec_at = showcase_rec[i];
            1: rec_at = smoke_rec[i];
            default: rec_at = 64'h0;
        endcase
    endfunction
    function [7:0] pin_at(input integer i);
        case (SCEN)
            0: pin_at = showcase_pin[i];
            1: pin_at = smoke_pin[i];
            default: pin_at = 8'hFF;
        endcase
    endfunction

    integer pass = 0, fail = 0;
    task chk(input ok, input [8*48-1:0] what);
        begin
            if (ok) pass = pass + 1;
            else begin fail = fail + 1; $display("FAIL %0s", what); end
        end
    endtask

    // receiver on tx_o: every 8 bytes is one record
    reg [63:0] got = 0;
    integer nb = 0, n_got = 0, ferr = 0, k;
    reg [7:0] b;
    always begin
        @(negedge tx);
        repeat (NB / 2) @(posedge clk);
        if (tx !== 1'b0) ferr = ferr + 1;
        for (k = 0; k < 8; k = k + 1) begin repeat (NB) @(posedge clk); b[k] = tx; end
        repeat (NB) @(posedge clk);
        if (tx !== 1'b1) ferr = ferr + 1;
        got = {got[55:0], b};
        nb = nb + 1;
        if (nb == 8) begin
            nb = 0;
            if (n_got >= N_REC) begin
                chk(0, "more records than the model");
                $display("REC %0d @%0d %h MISMATCH", n_got, cycles, got);
            end else begin
                chk(got === rec_at(n_got), "record equals the model's");
                $display("REC %0d @%0d %h %0s", n_got, cycles, got,
                         got === rec_at(n_got) ? "ok" : "MISMATCH");
            end
            n_got = n_got + 1;
        end
    end

    task send_byte(input [7:0] d);
        integer j;
        begin
            rx = 1'b0; repeat (NB) @(posedge clk);
            for (j = 0; j < 8; j = j + 1) begin rx = d[j]; repeat (NB) @(posedge clk); end
            rx = 1'b1; repeat (NB) @(posedge clk);
        end
    endtask

    integer i, j, len, vi = 0, vn = 0;
    reg [3:0] prev_in;
    reg [7:0] want;
    initial begin
        case (SCEN)
            0: $display("LANE LaneX toll lane controller on RVBL-2 SCEN=0 showcase UART %0d clocks/bit", NB);
            1: $display("LANE LaneX toll lane controller on RVBL-2 SCEN=1 smoke UART %0d clocks/bit", NB);
        endcase
        repeat (5) @(posedge clk);
        rst = 1'b0;
        repeat (2000) @(posedge clk);
        i = 0;
        while (i < N_EV) begin
            len = ev_at(i + 1);
            if (ev_at(i) == "W") begin
                repeat ({ev_at(i + 5), ev_at(i + 4), ev_at(i + 3), ev_at(i + 2)}) @(posedge clk);
            end else if (ev_at(i) == "G") begin
                prev_in = pin_in;
                pin_in = ev_at(i + 2);
                if (prev_in[0] && !pin_in[0]) repeat (SETTLE_FALL) @(posedge clk);
                else                          repeat (SETTLE_RISE) @(posedge clk);
                if (prev_in[0] && !pin_in[0]) begin    // a car has just left
                    while (vi < N_REC && pin_at(vi) == 8'hFF) vi = vi + 1;   // skip non-vehicle records
                    want = pin_at(vi) >> 4;
                    chk({4'b0000, p7, p6, p5, p4} === want, "pins 7:4 after a vehicle leaves");
                    $display("PINS %0d @%0d %b %0s", vn, cycles, {p7, p6, p5, p4},
                             {4'b0000, p7, p6, p5, p4} === want ? "ok" : "MISMATCH");
                    vi = vi + 1;
                    vn = vn + 1;
                end
            end else begin
                for (j = 0; j < len; j = j + 1) send_byte(ev_at(i + 2 + j));
                if (ev_at(i) == "B") repeat (GAP) @(posedge clk);
            end
            i = i + 2 + len;
        end
        repeat (40 * 10 * NB) @(posedge clk);
        chk(n_got == N_REC, "record count equals the model's");
        chk(ferr == 0, "no framing errors on tx_o");
        $display("==== tb_app_ci (scenario %0d): %0d passed, %0d failed, %0d cycles ====",
                 SCEN, pass, fail, cycles);
        if (fail == 0) $display("TB_APP_CI: ALL TESTS PASSED");
        else           $display("TB_APP_CI: FAILURES PRESENT");
        $finish;
    end
endmodule
