# Independent (non-RTL-derived) reference bit-slicer for immediate extraction,
# used to cross-check immediate_generator.v per spec recommendation (§9.7).
def sext(val, bits):
    val &= (1 << bits) - 1
    if val & (1 << (bits - 1)):
        val -= (1 << bits)
    return val & 0xFFFFFFFF

def imm_i(ir):
    return sext(ir >> 20, 12)

def imm_s(ir):
    v = ((ir >> 25) & 0x7F) << 5 | ((ir >> 7) & 0x1F)
    return sext(v, 12)

def imm_b(ir):
    v = (((ir >> 31) & 1) << 12) | (((ir >> 7) & 1) << 11) | \
        (((ir >> 25) & 0x3F) << 5) | (((ir >> 8) & 0xF) << 1)
    return sext(v, 13)

def imm_u(ir):
    return ir & 0xFFFFF000

def imm_j(ir):
    v = (((ir >> 31) & 1) << 20) | (((ir >> 12) & 0xFF) << 12) | \
        (((ir >> 20) & 1) << 11) | (((ir >> 21) & 0x3FF) << 1)
    return sext(v, 21)

# generate a directed vector file for the Verilog testbench: ir, opcode-kind, expected imm
import random, os
random.seed(1)
vectors = []

def mkI(rd, rs1, imm12, opcode=0b0010011, funct3=0):
    ir = ((imm12 & 0xFFF) << 20) | (rs1 << 15) | (funct3 << 12) | (rd << 7) | opcode
    return ir

def mkS(rs1, rs2, imm12, opcode=0b0100011, funct3=0):
    imm12 &= 0xFFF
    ir = (((imm12>>5)&0x7F)<<25) | (rs2<<20) | (rs1<<15) | (funct3<<12) | ((imm12&0x1F)<<7) | opcode
    return ir

def mkB(rs1, rs2, imm13, funct3=0, opcode=0b1100011):
    imm13 &= 0x1FFF
    b12 = (imm13>>12)&1; b11=(imm13>>11)&1; b10_5=(imm13>>5)&0x3F; b4_1=(imm13>>1)&0xF
    ir = (b12<<31)|(b10_5<<25)|(rs2<<20)|(rs1<<15)|(funct3<<12)|(b4_1<<8)|(b11<<7)|opcode
    return ir

def mkU(rd, imm20, opcode=0b0110111):
    ir = ((imm20 & 0xFFFFF) << 12) | (rd<<7) | opcode
    return ir

def mkJ(rd, imm21, opcode=0b1101111):
    imm21 &= 0x1FFFFF
    b20=(imm21>>20)&1; b19_12=(imm21>>12)&0xFF; b11=(imm21>>11)&1; b10_1=(imm21>>1)&0x3FF
    ir = (b20<<31)|(b10_1<<21)|(b11<<20)|(b19_12<<12)|(rd<<7)|opcode
    return ir

tests = []
for imm in [0, 1, -1, 2047, -2048, 100, -100]:
    ir = mkI(5, 6, imm)
    tests.append((ir, imm_i(ir)))
for imm in [0, 1, -1, 2047, -2048, 55, -55]:
    ir = mkS(6, 7, imm)
    tests.append((ir, imm_s(ir)))
for imm in [0, 2, -2, 4094, -4096, 100, -100]:
    imm &= ~1
    ir = mkB(6,7, imm)
    tests.append((ir, imm_b(ir)))
for imm20 in [0, 1, 0xFFFFF, 0x12345, 0x80000]:
    ir = mkU(10, imm20)
    tests.append((ir, imm_u(ir)))
for imm in [0, 2, -2, (1<<20)-2, -(1<<20), 4000, -4000]:
    imm &= ~1
    ir = mkJ(10, imm)
    tests.append((ir, imm_j(ir)))

# Emit every artifact the Verilog testbench actually consumes, so re-running
# this model can never leave tb_immediate_generator checking stale vectors:
#   imm_vectors.txt            - human-readable pair-per-line reference
#   imm_vectors_split_ir.hex   - $readmemh input words
#   imm_vectors_split_exp.hex  - $readmemh expected immediates
#   imm_vectors_count.vh       - vector count, `include`d by the testbench
here = os.path.dirname(os.path.abspath(__file__))
NL = chr(10)

with open(os.path.join(here, 'imm_vectors.txt'), 'w') as f:
    for ir, exp in tests:
        f.write(f"{ir & 0xFFFFFFFF:08x} {exp & 0xFFFFFFFF:08x}" + NL)

with open(os.path.join(here, 'imm_vectors_split_ir.hex'), 'w') as f:
    for ir, _ in tests:
        f.write(f"{ir & 0xFFFFFFFF:08x}" + NL)

with open(os.path.join(here, 'imm_vectors_split_exp.hex'), 'w') as f:
    for _, exp in tests:
        f.write(f"{exp & 0xFFFFFFFF:08x}" + NL)

with open(os.path.join(here, 'imm_vectors_count.vh'), 'w') as f:
    f.write("// Generated by tests/golden/imm_golden.py - do not hand-edit." + NL)
    f.write(f"localparam NVEC = {len(tests)};" + NL)

print(f"Wrote {len(tests)} vectors (txt + 2 hex + count header)")
