#!/usr/bin/env python3
"""Turn ./emu command lines into a testbench that plays them on the chip.

The organisers' emulator (./emu, RVBL-Emulator/src/emu.c) runs only on the
AWS F2 in Stage 4. This is its preview: every option of every command line is
performed on the pins of our chip `top`, in order, as emu performs it, and
the same lines emu prints are printed:

    -d DIR    pins whose bit is 0 are driven by the emulator, 1 are observed
    -i DATA   drive DATA on the pins the emulator drives
    -tN DATA  send N bytes into rx_i, least-significant byte first
    -rN DATA  read the next N bytes the chip sent on tx_o (first byte lowest)
              and compare with DATA
    -o DATA   read the pins the emulator observes and compare with DATA

Like emu, each command line is one run: the processor is reset first, and the
run stops at the first comparison that fails. emu sends one byte per AXI
access, about 0.1 s apart; here each byte is followed by GAP clock cycles of
silence (default 20,000: 0.66 ms, longer than any timeout the firmware could
have), and the chip's UART runs at its real 115,200 bps (263 cycles per bit).

A comment "# expect: error at -o" (or -r) just before a line says emu is
expected to stop there with an [error]; the line then passes only if it does.

    python gen_emu_preview.py emu_commands.txt tb_emu_preview.v
"""
import argparse
import os
import re
import sys

OPS = {"d": "D", "i": "I", "o": "O", "t1": "T", "t2": "T", "t4": "T", "r1": "R", "r2": "R", "r4": "R"}


def parse(path):
    """[(title, command text, expect_err_op or '', [(op, nbytes, value)])]"""
    runs, title, expect = [], "", ""
    for raw in open(path, encoding="utf-8").read().splitlines():
        line = raw.strip()
        if not line:
            title = ""                  # a block's title is its first comment line
            continue
        if line.startswith("#"):
            m = re.match(r"#\s*expect:\s*error at -([or])", line)
            if m:
                expect = m.group(1).upper()
            elif not title:
                title = line.lstrip("# ").strip()
            continue
        tok = line.split()
        if tok[0].endswith("emu"):
            tok = tok[1:]
        if len(tok) % 2:
            sys.exit("%s: odd option list: %s" % (path, line))
        ops = []
        for opt, val in zip(tok[0::2], tok[1::2]):
            key = opt.lstrip("-")
            if key not in OPS:
                sys.exit("%s: unknown option %s" % (path, opt))
            n = int(key[1]) if len(key) == 2 else 1
            ops.append((OPS[key], n, int(val, 0)))
        runs.append((title, "./emu " + " ".join(tok), expect, ops))
        title, expect = "", ""
    return runs


def render(runs, src):
    ev = []
    starts = []
    for _title, _cmd, expect, ops in runs:
        starts.append(len(ev))
        ev += [ord("S"), 1, ord(expect) if expect else 0]
        for op, n, v in ops:
            ev += [ord(op), n] + list((v & (2 ** (8 * n) - 1)).to_bytes(n, "little"))
        ev += [ord("E"), 0]
    L = []
    w = L.append
    w("`timescale 1ns/1ps")
    w("// ============================================================================")
    w("// %s - GENERATED by application/emulator-preview/gen_emu_preview.py" % os.path.basename(OUT))
    w("// from %s; do not edit." % src)
    w("//")
    w("// EMULATOR PREVIEW: the ./emu command lines below, played on the chip `top`")
    w("// in simulation exactly as the organisers' emulator performs them, printing")
    w("// the lines emu prints. Each line is one run: reset, then the options in order;")
    w("// the run stops at the first comparison that fails, as emu does.")
    w("//")
    for k, (title, cmd, expect, _ops) in enumerate(runs):
        w("//   %2d  %s%s" % (k + 1, title, "   (emu is expected to stop at -%s)" % expect.lower() if expect else ""))
    w("//")
    w("// LINE = 0 plays every line; LINE = k plays line k only.")
    w("// Pass: \"EMULATOR PREVIEW: ALL TESTS PASSED\".")
    w("// ============================================================================")
    w("module testbench;")
    w("    parameter LINE = 0;")
    w("    localparam integer NB      = 263;      // clock cycles per UART bit: 115200 bps at 30.303 MHz")
    w("    localparam integer GAP     = 20000;    // silence after each emu access (emu: ~0.1 s)")
    w("    localparam integer BOOT    = 3000;     // after reset, before the first access")
    w("    localparam integer TIMEOUT = 400000;   // the longest a -r may wait for its bytes")
    w("    localparam integer N_EV    = %d;" % len(ev))
    w("    localparam integer N_RUNS  = %d;" % len(runs))
    w("")
    w("    reg clk = 1'b0, rst = 1'b1;")
    w("    always #16.5 clk = ~clk;")
    w("    integer cycles = 0;")
    w("    always @(posedge clk) cycles = cycles + 1;")
    w("")
    w("    // the emulator's side of the pins: it drives pin k with emu_in[k] while")
    w("    // emu_dir[k] = 0, and observes it while emu_dir[k] = 1")
    w("    reg  [7:0] emu_dir = 8'h01, emu_in = 8'h00;")
    w("    reg        uart_rx = 1'b1;")
    w("    wire       uart_tx;")
    w("    wire [7:0] pins;")
    w("    genvar g;")
    w("    generate for (g = 0; g < 8; g = g + 1) begin : pin")
    w("        assign pins[g] = emu_dir[g] ? 1'bz : emu_in[g];")
    w("        assign (weak0, weak1) pins[g] = 1'b0;")
    w("    end endgenerate")
    w("    top dut (")
    w("        .clk_i(clk), .rst_i(rst),")
    w("        .pins_io_0(pins[0]), .pins_io_1(pins[1]), .pins_io_2(pins[2]), .pins_io_3(pins[3]),")
    w("        .pins_io_4(pins[4]), .pins_io_5(pins[5]), .pins_io_6(pins[6]), .pins_io_7(pins[7]),")
    w("        .tx_o(uart_tx), .rx_i(uart_rx));")
    w("")
    w("    initial begin")
    w("        $dumpfile(\"testbench.vcd\");")
    w("        $dumpvars(1, testbench);")
    w("    end")
    w("")
    w("    reg [7:0] ev [0:%d];" % (len(ev) - 1))
    w("    initial begin")
    for i in range(0, len(ev), 12):
        w("        " + " ".join("ev[%d]=8'h%02x;" % (i + k, b) for k, b in enumerate(ev[i:i + 12])))
    w("    end")
    w("")
    w("    // the emulator's UART receive buffer: the first 8 bytes the chip sends")
    w("    reg [7:0] rxbuf [0:7];")
    w("    integer   rx_n = 0;")
    w("    reg [7:0] rb;")
    w("    integer   rk;")
    w("    always begin")
    w("        @(negedge uart_tx);")
    w("        if (rst === 1'b0) begin")
    w("            repeat (NB / 2) @(posedge clk);")
    w("            for (rk = 0; rk < 8; rk = rk + 1) begin repeat (NB) @(posedge clk); rb[rk] = uart_tx; end")
    w("            repeat (NB) @(posedge clk);")
    w("            if (rx_n < 8) rxbuf[rx_n] = rb;")
    w("            rx_n = rx_n + 1;")
    w("        end")
    w("    end")
    w("")
    w("    task uart_send(input [7:0] b);")
    w("        integer j;")
    w("        begin")
    w("            uart_rx = 1'b0; repeat (NB) @(posedge clk);")
    w("            for (j = 0; j < 8; j = j + 1) begin uart_rx = b[j]; repeat (NB) @(posedge clk); end")
    w("            uart_rx = 1'b1; repeat (NB) @(posedge clk);")
    w("        end")
    w("    endtask")
    w("")
    w("    // upper-case hex of the low n bytes of v, as emu prints it")
    w("    function [8*8-1:0] hexs(input [31:0] v, input integer n);")
    w("        integer d;")
    w("        reg [3:0] q;")
    w("        begin")
    w("            hexs = 0;")
    w("            for (d = 2 * n - 1; d >= 0; d = d - 1) begin")
    w("                q = v >> (4 * d);")
    w("                hexs = {hexs[8*7-1:0], (q < 10) ? (8'd48 + q) : (8'd55 + q)};")
    w("            end")
    w("        end")
    w("    endfunction")
    w("")
    w("    task show_cmd(input integer k);")
    w("        case (k)")
    for k, (title, cmd, _e, _o) in enumerate(runs):
        w("            %d: begin $display(\"\"); $display(\"-- %d. %s\"); $display(\"$ %s\"); end"
          % (k, k + 1, title.replace('"', "'"), cmd))
    w("        endcase")
    w("    endtask")
    w("")
    w("    integer i, k, n, t, ptr, run = 0, pass = 0, fail = 0;")
    w("    reg [31:0] v, got;")
    w("    reg [8*8-1:0] hs, he;")
    w("    reg [7:0]  op, expect;")
    w("    reg        stopped, started;")
    w("    initial begin")
    w("        $display(\"============================================================\");")
    w("        $display(\" Emulator preview: ./emu command lines played on RVBL-2\");")
    w("        $display(\" UART 115200 bps, %0d cycles of silence after each emu access\", GAP);")
    w("        $display(\"============================================================\");")
    w("        i = 0;")
    w("        while (i < N_EV) begin")
    w("            op = ev[i]; n = ev[i + 1];")
    w("            v = 0;")
    w("            for (k = 0; k < n; k = k + 1) v = v | (ev[i + 2 + k] << (8 * k));")
    w("            if (op == \"S\") begin                     // a new emu run")
    w("                expect = ev[i + 2];")
    w("                stopped = 1'b0; started = 1'b0;")
    w("                if (LINE != 0 && LINE != run + 1) begin    // skip to this run's end")
    w("                    while (ev[i] != \"E\") i = i + 2 + ev[i + 1];")
    w("                    stopped = 1'b1; n = -2;                // so the loop lands on the E")
    w("                end else begin")
    w("                    show_cmd(run);")
    w("                    rst = 1'b1; emu_dir = 8'h01; emu_in = 8'h00; rx_n = 0; ptr = 0;")
    w("                    repeat (20) @(posedge clk);")
    w("                    $display(\"[ok] RISC-V started!\");")
    w("                end")
    w("            end else if (op == \"E\") begin")
    w("                if (!(LINE != 0 && LINE != run + 1)) begin")
    w("                    if (expect != 0 && !stopped) begin")
    w("                        fail = fail + 1;")
    w("                        $display(\"FAIL line %0d: emu was expected to stop at -%s, but every comparison passed\", run + 1, expect == \"O\" ? \"o\" : \"r\");")
    w("                    end else if (expect == 0 && stopped) begin")
    w("                        fail = fail + 1;")
    w("                        $display(\"FAIL line %0d\", run + 1);")
    w("                    end else begin")
    w("                        pass = pass + 1;")
    w("                        if (expect != 0) $display(\"PASS line %0d: emu stops at -%s, as expected\", run + 1, expect == \"O\" ? \"o\" : \"r\");")
    w("                        else             $display(\"PASS line %0d\", run + 1);")
    w("                    end")
    w("                end")
    w("                run = run + 1;")
    w("            end else if (!stopped) begin")
    w("                // emu's first -d comes before the core runs its first instruction here; on")
    w("                // the F2 it follows the reset (the firmware sets its own pin directions)")
    w("                if (!started && op != \"D\") begin")
    w("                    started = 1'b1;")
    w("                    rst = 1'b0; repeat (BOOT) @(posedge clk);")
    w("                end")
    w("                case (op)")
    w("                    \"D\": begin emu_dir = v; $display(\"[ok] Written 0x%s to DIRECTION\", hexs(v, 4)); end")
    w("                    \"I\": begin emu_in = v; $display(\"[ok] Written 0x%s to INPUT PINS\", hexs(v, 4));")
    w("                               repeat (GAP) @(posedge clk); end")
    w("                    \"T\": begin")
    w("                        for (k = 0; k < n; k = k + 1) begin uart_send(ev[i + 2 + k]); repeat (GAP) @(posedge clk); end")
    w("                        hs = hexs(v, n);")
    w("                        case (n) 1: $display(\"[ok] Written 0x%s to UART RX\", hs[15:0]);")
    w("                                 2: $display(\"[ok] Written 0x%s to UART RX\", hs[31:0]);")
    w("                           default: $display(\"[ok] Written 0x%s to UART RX\", hs); endcase")
    w("                    end")
    w("                    \"R\": begin")
    w("                        t = 0;")
    w("                        while (rx_n < ptr + n && t < TIMEOUT) begin @(posedge clk); t = t + 1; end")
    w("                        got = 0;")
    w("                        for (k = 0; k < n; k = k + 1)")
    w("                            if (ptr + k < rx_n && ptr + k < 8) got = got | (rxbuf[ptr + k] << (8 * k));")
    w("                        ptr = ptr + n;")
    w("                        hs = hexs(got, n); he = hexs(v, n);")
    w("                        if (got === v) case (n)")
    w("                            1: $display(\"[ok] Read 0x%s from UART TX\", hs[15:0]);")
    w("                            2: $display(\"[ok] Read 0x%s from UART TX\", hs[31:0]);")
    w("                            default: $display(\"[ok] Read 0x%s from UART TX\", hs);")
    w("                        endcase else begin")
    w("                            case (n)")
    w("                                1: $display(\"[error] UART read error. Expected 0x%s. Got 0x%s\", he[15:0], hs[15:0]);")
    w("                                2: $display(\"[error] UART read error. Expected 0x%s. Got 0x%s\", he[31:0], hs[31:0]);")
    w("                                default: $display(\"[error] UART read error. Expected 0x%s. Got 0x%s\", he, hs);")
    w("                            endcase")
    w("                            stopped = 1'b1;")
    w("                        end")
    w("                    end")
    w("                    \"O\": begin")
    w("                        repeat (GAP) @(posedge clk);")
    w("                        got = {24'd0, pins & emu_dir};")
    w("                        if (got === v) $display(\"[ok] Read 0x%s from OUTPUT PINS\", hexs(got, 4));")
    w("                        else begin")
    w("                            $display(\"[error] OUT read error. Expected 0x%s. Got 0x%s\", hexs(v, 4), hexs(got, 4));")
    w("                            stopped = 1'b1;")
    w("                        end")
    w("                    end")
    w("                endcase")
    w("                if (stopped && expect != 0 && expect != op) begin")
    w("                    $display(\"(stopped at -%s, not at the expected -%s)\", op == \"O\" ? \"o\" : \"r\", expect == \"O\" ? \"o\" : \"r\");")
    w("                    expect = 0;                          // counts as a failure at E")
    w("                end")
    w("            end")
    w("            i = i + 2 + n;")
    w("        end")
    w("        $display(\"\");")
    w("        $display(\"==== tb_emu_preview: %0d passed, %0d failed ====\", pass, fail);")
    w("        if (fail == 0) $display(\"EMULATOR PREVIEW: ALL TESTS PASSED\");")
    w("        else           $display(\"EMULATOR PREVIEW: FAILURES PRESENT\");")
    w("        $finish;")
    w("    end")
    w("endmodule")
    return "\n".join(L) + "\n"


OUT = "tb_emu_preview.v"


def main():
    global OUT
    ap = argparse.ArgumentParser()
    ap.add_argument("commands")
    ap.add_argument("out")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    OUT = a.out
    runs = parse(a.commands)
    text = render(runs, os.path.basename(a.commands))
    if a.check:
        cur = open(a.out, encoding="utf-8").read() if os.path.exists(a.out) else ""
        if cur != text:
            sys.exit("FAIL %s is stale: run gen_emu_preview.py" % a.out)
        print("OK   %s is current (%d command lines)" % (a.out, len(runs)))
        return 0
    with open(a.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote %s (%d command lines)" % (a.out, len(runs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
