`timescale 1ns/1ps
// ============================================================================
// tb_emu_preview.v - GENERATED by application/emulator-preview/gen_emu_preview.py
// from emu_commands.txt; do not edit.
//
// EMULATOR PREVIEW: the ./emu command lines below, played on the chip `top`
// in simulation exactly as the organisers' emulator performs them, printing
// the lines emu prints. Each line is one run: reset, then the options in order;
// the run stops at the first comparison that fails, as emu does.
//
//    1  valid tag, class matches -> CHARGED RM 2.50, P4 on
//    2  car tag on a lorry -> CLASS MISMATCH, charged at the lorry fare, P4+P5
//    3  taxi tag -> CHARGED at the taxi fare RM 1.30
//    4  no tag read -> NO TAG, camera P5
//    5  motorcycle, no tag -> FREE, no lamp
//    6  stolen car on the hotlist -> HOTLIST, camera + alarm P5+P6
//    7  cloned tag: seen 40 km away 30 s ago -> CLONE, camera + alarm
//    8  radio-corrupted tag (bad Gen2 CRC) -> NO TAG, camera
//    9  adjacent lane's weak read below the RSSI floor -> NO TAG
//   10  lane closed (P3) -> LANE CLOSED, P7 stays on while closed
//   11  identify: the chip reads its own ROM and reports its size and CRC
//
// LINE = 0 plays every line; LINE = k plays line k only.
// Pass: "EMULATOR PREVIEW: ALL TESTS PASSED".
// ============================================================================
module testbench;
    parameter LINE = 0;
    localparam integer NB      = 263;      // clock cycles per UART bit: 115200 bps at 30.303 MHz
    localparam integer GAP     = 20000;    // silence after each emu access (emu: ~0.1 s)
    localparam integer BOOT    = 3000;     // after reset, before the first access
    localparam integer TIMEOUT = 400000;   // the longest a -r may wait for its bytes
    localparam integer N_EV    = 738;
    localparam integer N_RUNS  = 11;

    reg clk = 1'b0, rst = 1'b1;
    always #16.5 clk = ~clk;
    integer cycles = 0;
    always @(posedge clk) cycles = cycles + 1;

    // the emulator's side of the pins: it drives pin k with emu_in[k] while
    // emu_dir[k] = 0, and observes it while emu_dir[k] = 1
    reg  [7:0] emu_dir = 8'h01, emu_in = 8'h00;
    reg        uart_rx = 1'b1;
    wire       uart_tx;
    wire [7:0] pins;
    genvar g;
    generate for (g = 0; g < 8; g = g + 1) begin : pin
        assign pins[g] = emu_dir[g] ? 1'bz : emu_in[g];
        assign (weak0, weak1) pins[g] = 1'b0;
    end endgenerate
    top dut (
        .clk_i(clk), .rst_i(rst),
        .pins_io_0(pins[0]), .pins_io_1(pins[1]), .pins_io_2(pins[2]), .pins_io_3(pins[3]),
        .pins_io_4(pins[4]), .pins_io_5(pins[5]), .pins_io_6(pins[6]), .pins_io_7(pins[7]),
        .tx_o(uart_tx), .rx_i(uart_rx));

    initial begin
        $dumpfile("testbench.vcd");
        $dumpvars(1, testbench);
    end

    reg [7:0] ev [0:737];
    initial begin
        ev[0]=8'h53; ev[1]=8'h01; ev[2]=8'h00; ev[3]=8'h44; ev[4]=8'h01; ev[5]=8'hf0; ev[6]=8'h49; ev[7]=8'h01; ev[8]=8'h01; ev[9]=8'h54; ev[10]=8'h04; ev[11]=8'ha5;
        ev[12]=8'h52; ev[13]=8'h15; ev[14]=8'h30; ev[15]=8'h54; ev[16]=8'h04; ev[17]=8'h75; ev[18]=8'h00; ev[19]=8'h00; ev[20]=8'h00; ev[21]=8'h54; ev[22]=8'h04; ev[23]=8'h30;
        ev[24]=8'h19; ev[25]=8'h51; ev[26]=8'h80; ev[27]=8'h54; ev[28]=8'h04; ev[29]=8'hf3; ev[30]=8'h83; ev[31]=8'ha5; ev[32]=8'hdc; ev[33]=8'h54; ev[34]=8'h04; ev[35]=8'hf3;
        ev[36]=8'h1a; ev[37]=8'he2; ev[38]=8'h39; ev[39]=8'h54; ev[40]=8'h04; ev[41]=8'he5; ev[42]=8'hcc; ev[43]=8'h6e; ev[44]=8'h5a; ev[45]=8'h54; ev[46]=8'h02; ev[47]=8'h92;
        ev[48]=8'hf5; ev[49]=8'h49; ev[50]=8'h01; ev[51]=8'h00; ev[52]=8'h52; ev[53]=8'h04; ev[54]=8'h56; ev[55]=8'h00; ev[56]=8'h00; ev[57]=8'h11; ev[58]=8'h52; ev[59]=8'h04;
        ev[60]=8'hfa; ev[61]=8'h00; ev[62]=8'h3c; ev[63]=8'h7b; ev[64]=8'h4f; ev[65]=8'h01; ev[66]=8'h10; ev[67]=8'h45; ev[68]=8'h00; ev[69]=8'h53; ev[70]=8'h01; ev[71]=8'h00;
        ev[72]=8'h44; ev[73]=8'h01; ev[74]=8'hf0; ev[75]=8'h49; ev[76]=8'h01; ev[77]=8'h05; ev[78]=8'h54; ev[79]=8'h04; ev[80]=8'ha5; ev[81]=8'h52; ev[82]=8'h15; ev[83]=8'h30;
        ev[84]=8'h54; ev[85]=8'h04; ev[86]=8'h75; ev[87]=8'h00; ev[88]=8'h00; ev[89]=8'h00; ev[90]=8'h54; ev[91]=8'h04; ev[92]=8'h30; ev[93]=8'h99; ev[94]=8'h9f; ev[95]=8'h8e;
        ev[96]=8'h54; ev[97]=8'h04; ev[98]=8'h6b; ev[99]=8'hc8; ev[100]=8'h92; ev[101]=8'h8c; ev[102]=8'h54; ev[103]=8'h04; ev[104]=8'hd7; ev[105]=8'hbb; ev[106]=8'hc6; ev[107]=8'hc4;
        ev[108]=8'h54; ev[109]=8'h04; ev[110]=8'h7d; ev[111]=8'h57; ev[112]=8'h96; ev[113]=8'h5a; ev[114]=8'h54; ev[115]=8'h02; ev[116]=8'hd0; ev[117]=8'h69; ev[118]=8'h49; ev[119]=8'h01;
        ev[120]=8'h00; ev[121]=8'h52; ev[122]=8'h04; ev[123]=8'h56; ev[124]=8'h00; ev[125]=8'h02; ev[126]=8'h31; ev[127]=8'h52; ev[128]=8'h04; ev[129]=8'hee; ev[130]=8'h02; ev[131]=8'h67;
        ev[132]=8'hff; ev[133]=8'h4f; ev[134]=8'h01; ev[135]=8'h30; ev[136]=8'h45; ev[137]=8'h00; ev[138]=8'h53; ev[139]=8'h01; ev[140]=8'h00; ev[141]=8'h44; ev[142]=8'h01; ev[143]=8'hf0;
        ev[144]=8'h49; ev[145]=8'h01; ev[146]=8'h01; ev[147]=8'h54; ev[148]=8'h04; ev[149]=8'ha5; ev[150]=8'h52; ev[151]=8'h15; ev[152]=8'h30; ev[153]=8'h54; ev[154]=8'h04; ev[155]=8'h75;
        ev[156]=8'h00; ev[157]=8'h00; ev[158]=8'h00; ev[159]=8'h54; ev[160]=8'h04; ev[161]=8'h30; ev[162]=8'hc4; ev[163]=8'hc5; ev[164]=8'h96; ev[165]=8'h54; ev[166]=8'h04; ev[167]=8'h70;
        ev[168]=8'h3d; ev[169]=8'h00; ev[170]=8'h9d; ev[171]=8'h54; ev[172]=8'h04; ev[173]=8'h14; ev[174]=8'h1c; ev[175]=8'h49; ev[176]=8'hd1; ev[177]=8'h54; ev[178]=8'h04; ev[179]=8'h19;
        ev[180]=8'h8b; ev[181]=8'hf4; ev[182]=8'h5a; ev[183]=8'h54; ev[184]=8'h02; ev[185]=8'h2c; ev[186]=8'hb1; ev[187]=8'h49; ev[188]=8'h01; ev[189]=8'h00; ev[190]=8'h52; ev[191]=8'h04;
        ev[192]=8'h56; ev[193]=8'h00; ev[194]=8'h00; ev[195]=8'h14; ev[196]=8'h52; ev[197]=8'h04; ev[198]=8'h82; ev[199]=8'h00; ev[200]=8'h3c; ev[201]=8'h11; ev[202]=8'h4f; ev[203]=8'h01;
        ev[204]=8'h10; ev[205]=8'h45; ev[206]=8'h00; ev[207]=8'h53; ev[208]=8'h01; ev[209]=8'h00; ev[210]=8'h44; ev[211]=8'h01; ev[212]=8'hf0; ev[213]=8'h49; ev[214]=8'h01; ev[215]=8'h01;
        ev[216]=8'h49; ev[217]=8'h01; ev[218]=8'h00; ev[219]=8'h52; ev[220]=8'h04; ev[221]=8'h56; ev[222]=8'h00; ev[223]=8'h01; ev[224]=8'h17; ev[225]=8'h52; ev[226]=8'h04; ev[227]=8'h00;
        ev[228]=8'h00; ev[229]=8'h22; ev[230]=8'h43; ev[231]=8'h4f; ev[232]=8'h01; ev[233]=8'h20; ev[234]=8'h45; ev[235]=8'h00; ev[236]=8'h53; ev[237]=8'h01; ev[238]=8'h00; ev[239]=8'h44;
        ev[240]=8'h01; ev[241]=8'hf0; ev[242]=8'h49; ev[243]=8'h01; ev[244]=8'h07; ev[245]=8'h49; ev[246]=8'h01; ev[247]=8'h00; ev[248]=8'h52; ev[249]=8'h04; ev[250]=8'h56; ev[251]=8'h00;
        ev[252]=8'h05; ev[253]=8'h07; ev[254]=8'h52; ev[255]=8'h04; ev[256]=8'h00; ev[257]=8'h00; ev[258]=8'hb0; ev[259]=8'hca; ev[260]=8'h4f; ev[261]=8'h01; ev[262]=8'h00; ev[263]=8'h45;
        ev[264]=8'h00; ev[265]=8'h53; ev[266]=8'h01; ev[267]=8'h00; ev[268]=8'h44; ev[269]=8'h01; ev[270]=8'hf0; ev[271]=8'h54; ev[272]=8'h04; ev[273]=8'ha5; ev[274]=8'h48; ev[275]=8'h0d;
        ev[276]=8'h71; ev[277]=8'h54; ev[278]=8'h04; ev[279]=8'h02; ev[280]=8'hd0; ev[281]=8'he4; ev[282]=8'haf; ev[283]=8'h54; ev[284]=8'h04; ev[285]=8'h7d; ev[286]=8'had; ev[287]=8'h50;
        ev[288]=8'h35; ev[289]=8'h54; ev[290]=8'h04; ev[291]=8'h65; ev[292]=8'h40; ev[293]=8'h59; ev[294]=8'h01; ev[295]=8'h54; ev[296]=8'h02; ev[297]=8'h97; ev[298]=8'hdc; ev[299]=8'h49;
        ev[300]=8'h01; ev[301]=8'h01; ev[302]=8'h54; ev[303]=8'h04; ev[304]=8'ha5; ev[305]=8'h52; ev[306]=8'h15; ev[307]=8'h30; ev[308]=8'h54; ev[309]=8'h04; ev[310]=8'h75; ev[311]=8'h00;
        ev[312]=8'h00; ev[313]=8'h00; ev[314]=8'h54; ev[315]=8'h04; ev[316]=8'h30; ev[317]=8'h71; ev[318]=8'h02; ev[319]=8'hd0; ev[320]=8'h54; ev[321]=8'h04; ev[322]=8'he4; ev[323]=8'haf;
        ev[324]=8'h7d; ev[325]=8'had; ev[326]=8'h54; ev[327]=8'h04; ev[328]=8'h50; ev[329]=8'h35; ev[330]=8'h65; ev[331]=8'h40; ev[332]=8'h54; ev[333]=8'h04; ev[334]=8'h59; ev[335]=8'h25;
        ev[336]=8'h5e; ev[337]=8'h5a; ev[338]=8'h54; ev[339]=8'h02; ev[340]=8'h28; ev[341]=8'ha1; ev[342]=8'h49; ev[343]=8'h01; ev[344]=8'h00; ev[345]=8'h52; ev[346]=8'h04; ev[347]=8'h56;
        ev[348]=8'h00; ev[349]=8'h03; ev[350]=8'h11; ev[351]=8'h52; ev[352]=8'h04; ev[353]=8'h00; ev[354]=8'h00; ev[355]=8'hea; ev[356]=8'h1c; ev[357]=8'h4f; ev[358]=8'h01; ev[359]=8'h60;
        ev[360]=8'h45; ev[361]=8'h00; ev[362]=8'h53; ev[363]=8'h01; ev[364]=8'h00; ev[365]=8'h44; ev[366]=8'h01; ev[367]=8'hf0; ev[368]=8'h54; ev[369]=8'h04; ev[370]=8'ha5; ev[371]=8'h47;
        ev[372]=8'h03; ev[373]=8'h02; ev[374]=8'h54; ev[375]=8'h04; ev[376]=8'h90; ev[377]=8'h01; ev[378]=8'hc6; ev[379]=8'h9a; ev[380]=8'h54; ev[381]=8'h04; ev[382]=8'ha5; ev[383]=8'h53;
        ev[384]=8'h11; ev[385]=8'hf9; ev[386]=8'h54; ev[387]=8'h04; ev[388]=8'hff; ev[389]=8'hed; ev[390]=8'h5b; ev[391]=8'hce; ev[392]=8'h54; ev[393]=8'h04; ev[394]=8'h60; ev[395]=8'hff;
        ev[396]=8'hbe; ev[397]=8'h83; ev[398]=8'h54; ev[399]=8'h04; ev[400]=8'ha3; ev[401]=8'h13; ev[402]=8'hb9; ev[403]=8'h02; ev[404]=8'h54; ev[405]=8'h04; ev[406]=8'h00; ev[407]=8'h00;
        ev[408]=8'h00; ev[409]=8'h00; ev[410]=8'h54; ev[411]=8'h02; ev[412]=8'h0d; ev[413]=8'h38; ev[414]=8'h49; ev[415]=8'h01; ev[416]=8'h01; ev[417]=8'h54; ev[418]=8'h04; ev[419]=8'ha5;
        ev[420]=8'h52; ev[421]=8'h15; ev[422]=8'h30; ev[423]=8'h54; ev[424]=8'h04; ev[425]=8'h75; ev[426]=8'h00; ev[427]=8'h00; ev[428]=8'h00; ev[429]=8'h54; ev[430]=8'h04; ev[431]=8'h30;
        ev[432]=8'hf9; ev[433]=8'hff; ev[434]=8'hed; ev[435]=8'h54; ev[436]=8'h04; ev[437]=8'h5b; ev[438]=8'hce; ev[439]=8'h60; ev[440]=8'hff; ev[441]=8'h54; ev[442]=8'h04; ev[443]=8'hbe;
        ev[444]=8'h83; ev[445]=8'ha3; ev[446]=8'h13; ev[447]=8'h54; ev[448]=8'h04; ev[449]=8'hb9; ev[450]=8'h67; ev[451]=8'hfc; ev[452]=8'h5a; ev[453]=8'h54; ev[454]=8'h02; ev[455]=8'hab;
        ev[456]=8'h11; ev[457]=8'h49; ev[458]=8'h01; ev[459]=8'h00; ev[460]=8'h52; ev[461]=8'h04; ev[462]=8'h56; ev[463]=8'h00; ev[464]=8'h04; ev[465]=8'h11; ev[466]=8'h52; ev[467]=8'h04;
        ev[468]=8'h00; ev[469]=8'h00; ev[470]=8'hc7; ev[471]=8'h4d; ev[472]=8'h4f; ev[473]=8'h01; ev[474]=8'h60; ev[475]=8'h45; ev[476]=8'h00; ev[477]=8'h53; ev[478]=8'h01; ev[479]=8'h00;
        ev[480]=8'h44; ev[481]=8'h01; ev[482]=8'hf0; ev[483]=8'h49; ev[484]=8'h01; ev[485]=8'h01; ev[486]=8'h54; ev[487]=8'h04; ev[488]=8'ha5; ev[489]=8'h52; ev[490]=8'h15; ev[491]=8'h30;
        ev[492]=8'h54; ev[493]=8'h04; ev[494]=8'h75; ev[495]=8'h00; ev[496]=8'h00; ev[497]=8'h00; ev[498]=8'h54; ev[499]=8'h04; ev[500]=8'h30; ev[501]=8'h51; ev[502]=8'h16; ev[503]=8'h8e;
        ev[504]=8'h54; ev[505]=8'h04; ev[506]=8'h89; ev[507]=8'h4a; ev[508]=8'h49; ev[509]=8'h75; ev[510]=8'h54; ev[511]=8'h04; ev[512]=8'h24; ev[513]=8'he0; ev[514]=8'ha5; ev[515]=8'hb4;
        ev[516]=8'h54; ev[517]=8'h04; ev[518]=8'hb7; ev[519]=8'h7f; ev[520]=8'h20; ev[521]=8'h5a; ev[522]=8'h54; ev[523]=8'h02; ev[524]=8'h3c; ev[525]=8'h06; ev[526]=8'h49; ev[527]=8'h01;
        ev[528]=8'h00; ev[529]=8'h52; ev[530]=8'h04; ev[531]=8'h56; ev[532]=8'h00; ev[533]=8'h01; ev[534]=8'h17; ev[535]=8'h52; ev[536]=8'h04; ev[537]=8'h00; ev[538]=8'h00; ev[539]=8'h22;
        ev[540]=8'h43; ev[541]=8'h4f; ev[542]=8'h01; ev[543]=8'h20; ev[544]=8'h45; ev[545]=8'h00; ev[546]=8'h53; ev[547]=8'h01; ev[548]=8'h00; ev[549]=8'h44; ev[550]=8'h01; ev[551]=8'hf0;
        ev[552]=8'h54; ev[553]=8'h04; ev[554]=8'ha5; ev[555]=8'h50; ev[556]=8'h0a; ev[557]=8'h1e; ev[558]=8'h54; ev[559]=8'h04; ev[560]=8'hf4; ev[561]=8'h01; ev[562]=8'hb8; ev[563]=8'h0b;
        ev[564]=8'h54; ev[565]=8'h04; ev[566]=8'hfa; ev[567]=8'h00; ev[568]=8'h40; ev[569]=8'h00; ev[570]=8'h54; ev[571]=8'h02; ev[572]=8'h00; ev[573]=8'hcd; ev[574]=8'h54; ev[575]=8'h01;
        ev[576]=8'hc8; ev[577]=8'h49; ev[578]=8'h01; ev[579]=8'h01; ev[580]=8'h54; ev[581]=8'h04; ev[582]=8'ha5; ev[583]=8'h52; ev[584]=8'h15; ev[585]=8'h30; ev[586]=8'h54; ev[587]=8'h04;
        ev[588]=8'h75; ev[589]=8'h00; ev[590]=8'h00; ev[591]=8'h00; ev[592]=8'h54; ev[593]=8'h04; ev[594]=8'h30; ev[595]=8'h91; ev[596]=8'h4f; ev[597]=8'h06; ev[598]=8'h54; ev[599]=8'h04;
        ev[600]=8'hd9; ev[601]=8'hb5; ev[602]=8'h5e; ev[603]=8'h5d; ev[604]=8'h54; ev[605]=8'h04; ev[606]=8'h76; ev[607]=8'h6c; ev[608]=8'h17; ev[609]=8'h66; ev[610]=8'h54; ev[611]=8'h04;
        ev[612]=8'he4; ev[613]=8'h24; ev[614]=8'h57; ev[615]=8'h14; ev[616]=8'h54; ev[617]=8'h02; ev[618]=8'h2a; ev[619]=8'h28; ev[620]=8'h49; ev[621]=8'h01; ev[622]=8'h00; ev[623]=8'h52;
        ev[624]=8'h04; ev[625]=8'h56; ev[626]=8'h00; ev[627]=8'h01; ev[628]=8'h17; ev[629]=8'h52; ev[630]=8'h04; ev[631]=8'h00; ev[632]=8'h00; ev[633]=8'h22; ev[634]=8'h43; ev[635]=8'h4f;
        ev[636]=8'h01; ev[637]=8'h20; ev[638]=8'h45; ev[639]=8'h00; ev[640]=8'h53; ev[641]=8'h01; ev[642]=8'h00; ev[643]=8'h44; ev[644]=8'h01; ev[645]=8'hf0; ev[646]=8'h49; ev[647]=8'h01;
        ev[648]=8'h09; ev[649]=8'h54; ev[650]=8'h04; ev[651]=8'ha5; ev[652]=8'h52; ev[653]=8'h15; ev[654]=8'h30; ev[655]=8'h54; ev[656]=8'h04; ev[657]=8'h75; ev[658]=8'h00; ev[659]=8'h00;
        ev[660]=8'h00; ev[661]=8'h54; ev[662]=8'h04; ev[663]=8'h30; ev[664]=8'h19; ev[665]=8'h51; ev[666]=8'h80; ev[667]=8'h54; ev[668]=8'h04; ev[669]=8'hf3; ev[670]=8'h83; ev[671]=8'ha5;
        ev[672]=8'hdc; ev[673]=8'h54; ev[674]=8'h04; ev[675]=8'hf3; ev[676]=8'h1a; ev[677]=8'he2; ev[678]=8'h39; ev[679]=8'h54; ev[680]=8'h04; ev[681]=8'he5; ev[682]=8'hcc; ev[683]=8'h6e;
        ev[684]=8'h5a; ev[685]=8'h54; ev[686]=8'h02; ev[687]=8'h92; ev[688]=8'hf5; ev[689]=8'h49; ev[690]=8'h01; ev[691]=8'h08; ev[692]=8'h52; ev[693]=8'h04; ev[694]=8'h56; ev[695]=8'h00;
        ev[696]=8'h06; ev[697]=8'h17; ev[698]=8'h52; ev[699]=8'h04; ev[700]=8'h00; ev[701]=8'h00; ev[702]=8'h0f; ev[703]=8'h12; ev[704]=8'h4f; ev[705]=8'h01; ev[706]=8'h80; ev[707]=8'h45;
        ev[708]=8'h00; ev[709]=8'h53; ev[710]=8'h01; ev[711]=8'h00; ev[712]=8'h44; ev[713]=8'h01; ev[714]=8'hf0; ev[715]=8'h54; ev[716]=8'h04; ev[717]=8'ha5; ev[718]=8'h49; ev[719]=8'h00;
        ev[720]=8'h5b; ev[721]=8'h54; ev[722]=8'h01; ev[723]=8'haa; ev[724]=8'h52; ev[725]=8'h04; ev[726]=8'h49; ev[727]=8'h03; ev[728]=8'hd6; ev[729]=8'h0a; ev[730]=8'h52; ev[731]=8'h04;
        ev[732]=8'h3d; ev[733]=8'hed; ev[734]=8'h21; ev[735]=8'hd5; ev[736]=8'h45; ev[737]=8'h00;
    end

    // the emulator's UART receive buffer: the first 8 bytes the chip sends
    reg [7:0] rxbuf [0:7];
    integer   rx_n = 0;
    reg [7:0] rb;
    integer   rk;
    always begin
        @(negedge uart_tx);
        if (rst === 1'b0) begin
            repeat (NB / 2) @(posedge clk);
            for (rk = 0; rk < 8; rk = rk + 1) begin repeat (NB) @(posedge clk); rb[rk] = uart_tx; end
            repeat (NB) @(posedge clk);
            if (rx_n < 8) rxbuf[rx_n] = rb;
            rx_n = rx_n + 1;
        end
    end

    task uart_send(input [7:0] b);
        integer j;
        begin
            uart_rx = 1'b0; repeat (NB) @(posedge clk);
            for (j = 0; j < 8; j = j + 1) begin uart_rx = b[j]; repeat (NB) @(posedge clk); end
            uart_rx = 1'b1; repeat (NB) @(posedge clk);
        end
    endtask

    // upper-case hex of the low n bytes of v, as emu prints it
    function [8*8-1:0] hexs(input [31:0] v, input integer n);
        integer d;
        reg [3:0] q;
        begin
            hexs = 0;
            for (d = 2 * n - 1; d >= 0; d = d - 1) begin
                q = v >> (4 * d);
                hexs = {hexs[8*7-1:0], (q < 10) ? (8'd48 + q) : (8'd55 + q)};
            end
        end
    endfunction

    task show_cmd(input integer k);
        case (k)
            0: begin $display(""); $display("-- 1. valid tag, class matches -> CHARGED RM 2.50, P4 on"); $display("$ ./emu -d 0xF0 -i 0x01 -t4 0x301552A5 -t4 0x00000075 -t4 0x80511930 -t4 0xDCA583F3 -t4 0x39E21AF3 -t4 0x5A6ECCE5 -t2 0xF592 -i 0x00 -r4 0x11000056 -r4 0x7B3C00FA -o 0x10"); end
            1: begin $display(""); $display("-- 2. car tag on a lorry -> CLASS MISMATCH, charged at the lorry fare, P4+P5"); $display("$ ./emu -d 0xF0 -i 0x05 -t4 0x301552A5 -t4 0x00000075 -t4 0x8E9F9930 -t4 0x8C92C86B -t4 0xC4C6BBD7 -t4 0x5A96577D -t2 0x69D0 -i 0x00 -r4 0x31020056 -r4 0xFF6702EE -o 0x30"); end
            2: begin $display(""); $display("-- 3. taxi tag -> CHARGED at the taxi fare RM 1.30"); $display("$ ./emu -d 0xF0 -i 0x01 -t4 0x301552A5 -t4 0x00000075 -t4 0x96C5C430 -t4 0x9D003D70 -t4 0xD1491C14 -t4 0x5AF48B19 -t2 0xB12C -i 0x00 -r4 0x14000056 -r4 0x113C0082 -o 0x10"); end
            3: begin $display(""); $display("-- 4. no tag read -> NO TAG, camera P5"); $display("$ ./emu -d 0xF0 -i 0x01 -i 0x00 -r4 0x17010056 -r4 0x43220000 -o 0x20"); end
            4: begin $display(""); $display("-- 5. motorcycle, no tag -> FREE, no lamp"); $display("$ ./emu -d 0xF0 -i 0x07 -i 0x00 -r4 0x07050056 -r4 0xCAB00000 -o 0x00"); end
            5: begin $display(""); $display("-- 6. stolen car on the hotlist -> HOTLIST, camera + alarm P5+P6"); $display("$ ./emu -d 0xF0 -t4 0x710D48A5 -t4 0xAFE4D002 -t4 0x3550AD7D -t4 0x01594065 -t2 0xDC97 -i 0x01 -t4 0x301552A5 -t4 0x00000075 -t4 0xD0027130 -t4 0xAD7DAFE4 -t4 0x40653550 -t4 0x5A5E2559 -t2 0xA128 -i 0x00 -r4 0x11030056 -r4 0x1CEA0000 -o 0x60"); end
            6: begin $display(""); $display("-- 7. cloned tag: seen 40 km away 30 s ago -> CLONE, camera + alarm"); $display("$ ./emu -d 0xF0 -t4 0x020347A5 -t4 0x9AC60190 -t4 0xF91153A5 -t4 0xCE5BEDFF -t4 0x83BEFF60 -t4 0x02B913A3 -t4 0x00000000 -t2 0x380D -i 0x01 -t4 0x301552A5 -t4 0x00000075 -t4 0xEDFFF930 -t4 0xFF60CE5B -t4 0x13A383BE -t4 0x5AFC67B9 -t2 0x11AB -i 0x00 -r4 0x11040056 -r4 0x4DC70000 -o 0x60"); end
            7: begin $display(""); $display("-- 8. radio-corrupted tag (bad Gen2 CRC) -> NO TAG, camera"); $display("$ ./emu -d 0xF0 -i 0x01 -t4 0x301552A5 -t4 0x00000075 -t4 0x8E165130 -t4 0x75494A89 -t4 0xB4A5E024 -t4 0x5A207FB7 -t2 0x063C -i 0x00 -r4 0x17010056 -r4 0x43220000 -o 0x20"); end
            8: begin $display(""); $display("-- 9. adjacent lane's weak read below the RSSI floor -> NO TAG"); $display("$ ./emu -d 0xF0 -t4 0x1E0A50A5 -t4 0x0BB801F4 -t4 0x004000FA -t2 0xCD00 -t1 0xC8 -i 0x01 -t4 0x301552A5 -t4 0x00000075 -t4 0x064F9130 -t4 0x5D5EB5D9 -t4 0x66176C76 -t4 0x145724E4 -t2 0x282A -i 0x00 -r4 0x17010056 -r4 0x43220000 -o 0x20"); end
            9: begin $display(""); $display("-- 10. lane closed (P3) -> LANE CLOSED, P7 stays on while closed"); $display("$ ./emu -d 0xF0 -i 0x09 -t4 0x301552A5 -t4 0x00000075 -t4 0x80511930 -t4 0xDCA583F3 -t4 0x39E21AF3 -t4 0x5A6ECCE5 -t2 0xF592 -i 0x08 -r4 0x17060056 -r4 0x120F0000 -o 0x80"); end
            10: begin $display(""); $display("-- 11. identify: the chip reads its own ROM and reports its size and CRC"); $display("$ ./emu -d 0xF0 -t4 0x5B0049A5 -t1 0xAA -r4 0x0AD60349 -r4 0xD521ED3D"); end
        endcase
    endtask

    integer i, k, n, t, ptr, run = 0, pass = 0, fail = 0;
    reg [31:0] v, got;
    reg [8*8-1:0] hs, he;
    reg [7:0]  op, expect;
    reg        stopped, started;
    initial begin
        $display("============================================================");
        $display(" Emulator preview: ./emu command lines played on RVBL-2");
        $display(" UART 115200 bps, %0d cycles of silence after each emu access", GAP);
        $display("============================================================");
        i = 0;
        while (i < N_EV) begin
            op = ev[i]; n = ev[i + 1];
            v = 0;
            for (k = 0; k < n; k = k + 1) v = v | (ev[i + 2 + k] << (8 * k));
            if (op == "S") begin                     // a new emu run
                expect = ev[i + 2];
                stopped = 1'b0; started = 1'b0;
                if (LINE != 0 && LINE != run + 1) begin    // skip to this run's end
                    while (ev[i] != "E") i = i + 2 + ev[i + 1];
                    stopped = 1'b1; n = -2;                // so the loop lands on the E
                end else begin
                    show_cmd(run);
                    rst = 1'b1; emu_dir = 8'h01; emu_in = 8'h00; rx_n = 0; ptr = 0;
                    repeat (20) @(posedge clk);
                    $display("[ok] RISC-V started!");
                end
            end else if (op == "E") begin
                if (!(LINE != 0 && LINE != run + 1)) begin
                    if (expect != 0 && !stopped) begin
                        fail = fail + 1;
                        $display("FAIL line %0d: emu was expected to stop at -%s, but every comparison passed", run + 1, expect == "O" ? "o" : "r");
                    end else if (expect == 0 && stopped) begin
                        fail = fail + 1;
                        $display("FAIL line %0d", run + 1);
                    end else begin
                        pass = pass + 1;
                        if (expect != 0) $display("PASS line %0d: emu stops at -%s, as expected", run + 1, expect == "O" ? "o" : "r");
                        else             $display("PASS line %0d", run + 1);
                    end
                end
                run = run + 1;
            end else if (!stopped) begin
                // emu's first -d comes before the core runs its first instruction here; on
                // the F2 it follows the reset (the firmware sets its own pin directions)
                if (!started && op != "D") begin
                    started = 1'b1;
                    rst = 1'b0; repeat (BOOT) @(posedge clk);
                end
                case (op)
                    "D": begin emu_dir = v; $display("[ok] Written 0x%s to DIRECTION", hexs(v, 4)); end
                    "I": begin emu_in = v; $display("[ok] Written 0x%s to INPUT PINS", hexs(v, 4));
                               repeat (GAP) @(posedge clk); end
                    "T": begin
                        for (k = 0; k < n; k = k + 1) begin uart_send(ev[i + 2 + k]); repeat (GAP) @(posedge clk); end
                        hs = hexs(v, n);
                        case (n) 1: $display("[ok] Written 0x%s to UART RX", hs[15:0]);
                                 2: $display("[ok] Written 0x%s to UART RX", hs[31:0]);
                           default: $display("[ok] Written 0x%s to UART RX", hs); endcase
                    end
                    "R": begin
                        t = 0;
                        while (rx_n < ptr + n && t < TIMEOUT) begin @(posedge clk); t = t + 1; end
                        got = 0;
                        for (k = 0; k < n; k = k + 1)
                            if (ptr + k < rx_n && ptr + k < 8) got = got | (rxbuf[ptr + k] << (8 * k));
                        ptr = ptr + n;
                        hs = hexs(got, n); he = hexs(v, n);
                        if (got === v) case (n)
                            1: $display("[ok] Read 0x%s from UART TX", hs[15:0]);
                            2: $display("[ok] Read 0x%s from UART TX", hs[31:0]);
                            default: $display("[ok] Read 0x%s from UART TX", hs);
                        endcase else begin
                            case (n)
                                1: $display("[error] UART read error. Expected 0x%s. Got 0x%s", he[15:0], hs[15:0]);
                                2: $display("[error] UART read error. Expected 0x%s. Got 0x%s", he[31:0], hs[31:0]);
                                default: $display("[error] UART read error. Expected 0x%s. Got 0x%s", he, hs);
                            endcase
                            stopped = 1'b1;
                        end
                    end
                    "O": begin
                        repeat (GAP) @(posedge clk);
                        got = {24'd0, pins & emu_dir};
                        if (got === v) $display("[ok] Read 0x%s from OUTPUT PINS", hexs(got, 4));
                        else begin
                            $display("[error] OUT read error. Expected 0x%s. Got 0x%s", hexs(v, 4), hexs(got, 4));
                            stopped = 1'b1;
                        end
                    end
                endcase
                if (stopped && expect != 0 && expect != op) begin
                    $display("(stopped at -%s, not at the expected -%s)", op == "O" ? "o" : "r", expect == "O" ? "o" : "r");
                    expect = 0;                          // counts as a failure at E
                end
            end
            i = i + 2 + n;
        end
        $display("");
        $display("==== tb_emu_preview: %0d passed, %0d failed ====", pass, fail);
        if (fail == 0) $display("EMULATOR PREVIEW: ALL TESTS PASSED");
        else           $display("EMULATOR PREVIEW: FAILURES PRESENT");
        $finish;
    end
endmodule
