#!/usr/bin/env python3
"""Generate the application's testbenches for the ChipInventor platform
simulator (and the local mirror):

  chipinventor/app/tb_app_ci.v       the chip exactly as taped out: UART at
                                     115,200 bps (263 clocks per bit). Touches
                                     only pins, so it runs on any export as-is.
  chipinventor/app/tb_app_ci_fast.v  the same chip and firmware with the UART's
                                     BAUD_RATE overridden to 921,600 (33 clocks
                                     per bit) by one defparam and a shorter exit
                                     hold-off sent in the 'P' frame, the demo cut
                                     into three runs that each fit the platform's
                                     simulation window. It names the UART
                                     instance, so run_ci.sh writes
                                     build/tb_app_platform.v from it with the
                                     export's instance names (paste that).

The platform has no filesystem, so the stimulus and the golden model's
expected records are embedded as initialised arrays. Both print every record
the chip transmits, as it arrives, with the cycle it finished on:

    REC <n> @<cycle> <16 hex digits> ok|MISMATCH
    PINS <vehicle> @<cycle> <p7 p6 p5 p4> ok|MISMATCH

That transcript is the chip's own output, captured at its tx_o pin by the
platform's simulator; the replay page (application/replay) takes it
pasted in - one run's log or several one after another - decodes it, and
verifies every CRC and Chaskey-12 tag itself.

SCEN selects the run; DESCRIBE lists them.

    python application/testbench/gen_platform_tb.py            # write both
    python application/testbench/gen_platform_tb.py --check    # fail if either is stale
"""

import argparse
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lane_model as L  # noqa: E402

OUT = os.path.join(ROOT, "chipinventor", "app", "tb_app_ci.v")
OUT_FAST = os.path.join(ROOT, "chipinventor", "app", "tb_app_ci_fast.v")
CLK_HZ = 30303030

MODES = {
    # gap: idle bits after each 'B' line; settle after a car arrives / leaves
    # (see tb_app.v - no scenario here has cut-off frames, so an arrival
    # needs only the pin synchroniser's few cycles; a departure's settle covers
    # the whole decision, so no byte arrives while it runs).
    "true": dict(baud=115200, gap_bits=20, rise=2000, fall=16000, hold=64,
                 attest_wait=L.ATTEST_WAIT, drain=40),
    "fast": dict(baud=921600, gap_bits=30, rise=1000, fall=9000, hold=8,
                 attest_wait=50000, drain=40),
}

DESCRIBE = {
    "showcase": "the demo: 'I', key, seven vehicles, one of each outcome, each\n"
                "//                authenticated; an 'E'; stats",
    "smoke": "six vehicles, one of each main outcome, no key",
    "lane-a": "key; a charged car, a class mismatch and the adjacent lane's\n"
              "//                weak read, authenticated; a corrupted frame and its 'E'; stats",
    "lane-b": "key, gantry 2, a stolen tag and a clone sighting; the stolen\n"
              "//                car and the clone, authenticated",
    "identity": "the chip measures its own ROM ('I'); key; a taxi, authenticated",
}


def scen_list(mode):
    """The taped-out rate runs the whole showcase (and smoke); the fast mode
    splits the demo in three so each run fits the platform's window."""
    m = MODES[mode]
    if mode == "fast":
        return L.platform_scenarios(hold=m["hold"], attest_wait=m["attest_wait"])
    return [("showcase", L.showcase_scenario(hold=m["hold"], attest_wait=m["attest_wait"])),
            ("smoke", L.smoke_scenario())]


def ident(name):
    return name.replace("-", "_")


def arrays(sc):
    m = sc.run()
    ev = []
    for kind, v in sc.ev:
        if kind == "G":
            ev += [ord("G"), 1, v]
        elif kind == "W":
            ev += [ord("W"), 4] + list(struct.pack("<I", v))
        else:
            ev += [ord(kind), len(v)] + list(v)
    recs = [bytes(m.out[i:i + 8]) for i in range(0, len(m.out), 8)]
    vp = iter(m.vehicle_pins)
    pins = [next(vp) if r[0] == 0x56 else 0xFF for r in recs]
    return ev, recs, pins


def render(mode):
    m = MODES[mode]
    nb = (CLK_HZ + m["baud"] // 2) // m["baud"]
    scen = scen_list(mode)
    data = [arrays(s) for _, s in scen]
    fast = mode == "fast"
    out = []
    w = out.append
    w("""`timescale 1ns/1ps
// ============================================================================
// %(file)s - GENERATED by application/testbench/gen_platform_tb.py; do not edit.
//
// The Stage 3 application (the free-flow toll lane controller) on the canvas
// chip `top`, checked against the golden model (application/testbench/lane_model.py).
// Use it with the APPLICATION ROM: paste chipinventor/app/imem_app.v into the
// imem block's Code field (the validation ROM stays in chipinventor/blocks/).
//
// Plays a scenario - frames into rx_i, vehicle presence / class / lane-closed
// on pins 3:0 - and prints every 8-byte record the chip sends on tx_o, as it
// arrives, with the model's verdict:
//     REC <n> @<cycle> <record, 16 hex digits> ok|MISMATCH
//     PINS <vehicle> @<cycle> <p7 p6 p5 p4> ok|MISMATCH
// Paste the log into the replay page to watch the chip's decisions; the page
// decodes those bytes and checks every CRC and Chaskey-12 tag itself.
//
// Set SCEN (below) to choose the run:
%(names)s// Pass: "TB_APP_CI: ALL TESTS PASSED".
""" % {"file": os.path.basename(OUT_FAST if fast else OUT),
       "names": "".join("//   %d  %-9s %s\n" % (i, n, DESCRIBE[n]) for i, (n, _) in enumerate(scen))})
    if fast:
        w("""//
// FAST: the UART's BAUD_RATE is overridden to 921,600 bps (33 clocks per bit
// instead of 263) and the 'P' frame sets an 8-iteration exit hold-off, so each
// run fits the platform's simulation window. Same chip, same firmware;
// chipinventor/scripts/run_ci.sh runs all three on the mirror and the export
// before you paste, and tb_app.v runs the showcase at both rates. The override
// names the UART instance: paste build/tb_app_platform.v, which run_ci.sh
// writes from this file with your export's instance names.
""")
    w("""// ============================================================================
module testbench;   // the platform runs the module named testbench
    parameter SCEN = 0;
    localparam integer NB = %(nb)d;              // clocks per bit: 30.303 MHz / %(baud)d
    localparam integer GAP = %(gap)d * NB;        // idle after each frame
    localparam integer SETTLE_RISE = %(rise)d;   // after a car arrives
    localparam integer SETTLE_FALL = %(fall)d;  // after it leaves (> the whole decision)

    reg clk = 0, rst = 1;
    always #16.5 clk = ~clk;
    integer cycles = 0;
    always @(posedge clk) cycles = cycles + 1;

    reg  [3:0] pin_in = 4'h0;
    reg        rx = 1'b1;
    wire       tx;
    wire p0, p1, p2, p3, p4, p5, p6, p7;
    assign p0 = pin_in[0];
    assign p1 = pin_in[1];
    assign p2 = pin_in[2];
    assign p3 = pin_in[3];
    assign (weak0, weak1) p4 = 1'b0;
    assign (weak0, weak1) p5 = 1'b0;
    assign (weak0, weak1) p6 = 1'b0;
    assign (weak0, weak1) p7 = 1'b0;

    top dut (
        .clk_i(clk), .rst_i(rst),
        .pins_io_0(p0), .pins_io_1(p1), .pins_io_2(p2), .pins_io_3(p3),
        .pins_io_4(p4), .pins_io_5(p5), .pins_io_6(p6), .pins_io_7(p7),
        .tx_o(tx), .rx_i(rx));
""" % dict(nb=nb, baud=m["baud"], gap=m["gap_bits"], rise=m["rise"], fall=m["fall"]))
    if fast:
        w("""
// Instance names from the export; run_ci.sh regenerates this block.
// >>> BEGIN GENERATED ALIASES
// <<< END GENERATED ALIASES
    defparam `UART.BAUD_RATE = %d;
""" % m["baud"])
    for (name, _), (ev, recs, pins) in zip(scen, data):
        w("\n    // ---- scenario %s: %d event bytes, %d records ----\n" % (name, len(ev), len(recs)))
        name = ident(name)
        w("    reg [7:0]  %s_ev  [0:%d];\n" % (name, len(ev) - 1))
        w("    reg [63:0] %s_rec [0:%d];\n" % (name, len(recs) - 1))
        w("    reg [7:0]  %s_pin [0:%d];\n" % (name, len(recs) - 1))
    w("\n    initial begin\n")
    for (name, _), (ev, recs, pins) in zip(scen, data):
        name = ident(name)
        for i in range(0, len(ev), 8):
            w("        " + " ".join("%s_ev[%d]=8'h%02x;" % (name, i + k, b)
                                   for k, b in enumerate(ev[i:i + 8])) + "\n")
        for i, (r, p) in enumerate(zip(recs, pins)):
            w("        %s_rec[%d]=64'h%s; %s_pin[%d]=8'h%02x;\n" % (name, i, r.hex(), name, i, p))
    w("    end\n")

    def pick(values):
        """N_EV / N_REC for the SCEN chosen."""
        return " : ".join(["(SCEN == %d) ? %d" % (i, v) for i, v in enumerate(values[:-1])] + [str(values[-1])])

    def select(fn, width, arr, default):
        """ev_at / rec_at / pin_at: element i of the SCEN chosen's array."""
        arms = "".join("            %d: %s = %s_%s[i];\n" % (i, fn, ident(n), arr) for i, (n, _) in enumerate(scen))
        return ("    function [%d:0] %s(input integer i);\n        case (SCEN)\n%s"
                "            default: %s = %s;\n        endcase\n    endfunction\n"
                % (width - 1, fn, arms, fn, default))

    w("\n    localparam integer N_EV  = %s;\n" % pick([len(d[0]) for d in data]))
    w("    localparam integer N_REC = %s;\n" % pick([len(d[1]) for d in data]))
    w(select("ev_at", 8, "ev", "8'h00"))
    w(select("rec_at", 64, "rec", "64'h0"))
    w(select("pin_at", 8, "pin", "8'hFF"))
    banner = "".join('            %d: $display("LANE LaneX toll lane controller on RVBL-2 SCEN=%d %s UART %%0d clocks/bit", NB);\n'
                     % (i, i, n) for i, (n, _) in enumerate(scen))
    w("""
    integer pass = 0, fail = 0;
    task chk(input ok, input [8*48-1:0] what);
        begin
            if (ok) pass = pass + 1;
            else begin fail = fail + 1; $display("FAIL %%0s", what); end
        end
    endtask

    // receiver on tx_o: every 8 bytes is one record
    reg [63:0] got = 0;
    integer nb = 0, n_got = 0, ferr = 0, k;
    reg [7:0] b;
    always begin
        @(negedge tx);
        repeat (NB / 2) @(posedge clk);
        if (tx !== 1'b0) ferr = ferr + 1;
        for (k = 0; k < 8; k = k + 1) begin repeat (NB) @(posedge clk); b[k] = tx; end
        repeat (NB) @(posedge clk);
        if (tx !== 1'b1) ferr = ferr + 1;
        got = {got[55:0], b};
        nb = nb + 1;
        if (nb == 8) begin
            nb = 0;
            if (n_got >= N_REC) begin
                chk(0, "more records than the model");
                $display("REC %%0d @%%0d %%h MISMATCH", n_got, cycles, got);
            end else begin
                chk(got === rec_at(n_got), "record equals the model's");
                $display("REC %%0d @%%0d %%h %%0s", n_got, cycles, got,
                         got === rec_at(n_got) ? "ok" : "MISMATCH");
            end
            n_got = n_got + 1;
        end
    end

    task send_byte(input [7:0] d);
        integer j;
        begin
            rx = 1'b0; repeat (NB) @(posedge clk);
            for (j = 0; j < 8; j = j + 1) begin rx = d[j]; repeat (NB) @(posedge clk); end
            rx = 1'b1; repeat (NB) @(posedge clk);
        end
    endtask

    integer i, j, len, vi = 0, vn = 0;
    reg [3:0] prev_in;
    reg [7:0] want;
    initial begin
        case (SCEN)
%(banner)s        endcase
        repeat (5) @(posedge clk);
        rst = 1'b0;
        repeat (2000) @(posedge clk);
        i = 0;
        while (i < N_EV) begin
            len = ev_at(i + 1);
            if (ev_at(i) == "W") begin
                repeat ({ev_at(i + 5), ev_at(i + 4), ev_at(i + 3), ev_at(i + 2)}) @(posedge clk);
            end else if (ev_at(i) == "G") begin
                prev_in = pin_in;
                pin_in = ev_at(i + 2);
                if (prev_in[0] && !pin_in[0]) repeat (SETTLE_FALL) @(posedge clk);
                else                          repeat (SETTLE_RISE) @(posedge clk);
                if (prev_in[0] && !pin_in[0]) begin    // a car has just left
                    while (vi < N_REC && pin_at(vi) == 8'hFF) vi = vi + 1;   // skip non-vehicle records
                    want = pin_at(vi) >> 4;
                    chk({4'b0000, p7, p6, p5, p4} === want, "pins 7:4 after a vehicle leaves");
                    $display("PINS %%0d @%%0d %%b %%0s", vn, cycles, {p7, p6, p5, p4},
                             {4'b0000, p7, p6, p5, p4} === want ? "ok" : "MISMATCH");
                    vi = vi + 1;
                    vn = vn + 1;
                end
            end else begin
                for (j = 0; j < len; j = j + 1) send_byte(ev_at(i + 2 + j));
                if (ev_at(i) == "B") repeat (GAP) @(posedge clk);
            end
            i = i + 2 + len;
        end
        repeat (%(drain)d * 10 * NB) @(posedge clk);
        chk(n_got == N_REC, "record count equals the model's");
        chk(ferr == 0, "no framing errors on tx_o");
        $display("==== tb_app_ci (scenario %%0d): %%0d passed, %%0d failed, %%0d cycles ====",
                 SCEN, pass, fail, cycles);
        if (fail == 0) $display("TB_APP_CI: ALL TESTS PASSED");
        else           $display("TB_APP_CI: FAILURES PRESENT");
        $finish;
    end
endmodule
""" % dict(banner=banner, drain=m["drain"]))
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    for mode, path in (("true", OUT), ("fast", OUT_FAST)):
        text = render(mode)
        rel = os.path.relpath(path, ROOT)
        if a.check:
            cur = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
            if cur != text:
                sys.exit("FAIL %s is stale: run python application/testbench/gen_platform_tb.py" % rel)
            print("OK   %s is current" % rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print("wrote %s (%d lines)" % (rel, text.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
